In [3]:
import polars as pl

# 1. 데이터 경로 설정
input_path = "/Users/hajiyoon/workspace/data/processed/최종_상품단위_데이터셋.csv"
output_path = "pareto_processed_results_v3.csv"

# 2. 데이터 로딩 (LazyFrame 사용)
lf = pl.scan_csv(input_path)

# 3. 데이터 전처리 및 필터링
df = lf.select([
    pl.col("상품중분류명").alias("중분류명"),
    pl.col("상품명"),
    pl.col("총_매출금액").alias("총매출금액")
]).filter(
    pl.col("중분류명") != "생수"  # '생수' 중분류 삭제
).collect()

# ① 중분류별 총 매출액 계산 및 병합
df = df.with_columns([
    pl.col("총매출금액").sum().over("중분류명").alias("중분류총매출금액")
])

# ② 중분류 내 내림차순 정렬 및 누적 비율 계산
df = df.sort(["중분류명", "총매출금액"], descending=[False, True])

df = df.with_columns([
    (pl.col("총매출금액").cum_sum().over("중분류명") / pl.col("중분류총매출금액")).alias("누적비율"),
    (pl.col("총매출금액") / pl.col("중분류총매출금액")).alias("중분류총매출금액중비율")
])

# ③ 파레토(80%) 필터링
df_filtered = df.filter(pl.col("누적비율") < 0.8)

# ④ PB 상품 기준 중분류 추출
pb_categories = (
    df_filtered.filter(pl.col("상품명").str.contains("PB"))
    .select("중분류명")
    .unique()
    .to_series()
    .to_list()
)

# ⑤ 특별 구제(예외) 조건 딕셔너리 설정
exception_mapping = {
    '기타전통주': '롯데)', '삼각김밥': '롯데)', '떡': '유라가)',
    '햄버거': '롯데)', '냉장피자': '안유성)', '호빵': 'KBO)',
    '국산맥주': '신동엽)', '양주': '신동엽)', '샌드위치': '롯데)',
    '김밥': '롯데)', '와인': '지비)', '초밥류': '롯데)',
    '도시락': '롯데)', '하이볼': '세븐브로이)', '고급': 'G)',
    '냉동디저트': '시원)'
}

# 예외 조건에 맞는 중분류 찾기
exception_categories = []
for cat, keyword in exception_mapping.items():
    # 해당 중분류명이고, 상품명에 키워드가 있는 상품이 1개라도 있는지 확인 (literal=True로 괄호 문자 그대로 인식)
    match_count = df_filtered.filter(
        (pl.col("중분류명") == cat) & (pl.col("상품명").str.contains(keyword, literal=True))
    ).height
    
    if match_count > 0:
        exception_categories.append(cat)

# 살려둘 최종 중분류 목록 (PB 포함 + 예외 조건 포함, 중복 제거)
categories_to_keep = list(set(pb_categories + exception_categories))

# 최종 결과 필터링
final_df = df_filtered.filter(pl.col("중분류명").is_in(categories_to_keep))

# 4. 결과 CSV 저장
final_columns = ['중분류명', '상품명', '총매출금액', '중분류총매출금액중비율', '중분류총매출금액']
final_df.select(final_columns).write_csv(output_path)

# 5. 마지막 출력 (PB 유무 + 구제된 중분류 확인)
# (요청했던 대로 원본 기준으로 출력하되, 구제된 애들도 알 수 있게 살짝 다듬었어!)
all_categories = df.select("중분류명").unique().to_series().to_list()

pb_check = df.group_by("중분류명").agg([
    pl.col("상품명").str.contains("PB").any().alias("has_pb")
])

pb_list = pb_check.filter(pl.col("has_pb")).select("중분류명").to_series().to_list()
non_pb_list = pb_check.filter(~pl.col("has_pb")).select("중분류명").to_series().to_list()

print(f"pb라는 문자열이 있는 중분류 : {pb_list} / 총 {len(pb_list)}개")
print(f"없는 중분류: {non_pb_list} / 총 {len(non_pb_list)}개")
print(f"💡 그 중 예외로 구제되어 살아남은 중분류: {exception_categories} / 총 {len(exception_categories)}개")

pb라는 문자열이 있는 중분류 : ['컵커피', '냉장안주', '냉장간편식', '샐러드', '기능성드링크', '오징어', '가공미반류', '젤리', '캔', '조리냉동', '흰우유', '냉동간편식', '농산안주', '전통음료', '얼음', '노벨티', '용기면', '스포츠음료', '프로틴 음료', '스낵류', '비스킷류', '육포', '건해산물', '프로틴/시리얼', '초콜릿', '냉장베이커리', '세븐카페', '차음료', '커피음료', '너트류', '냉장주스', '껌', '상온간편식', '간식빵', '파우치', '가공우유', '냉동만두', '젤리류', '원컵', '차', '주스', '구움과자', '스낵안주', '컨셉카페', '냉장간식', '캔디류', '요구르트'] / 총 47개
없는 중분류: ['조미료', '과일', '리쿼', '푸드 간편식', '즉석간식', '기능성우유', '소주', '국산맥주', '건강/이너뷰티', '시즌케익', '장류', '샐러드모닝랩', '도시락', '수입맥주', '즉석치킨', '식빵', '봉지면', '프리미엄', '쌀/잡곡', '분말가루', '신선냉동', '탄산음료', '생선류', '기타', '떡', '숙취해소제', '하이볼', '쨈/꿀', '고급', '냉동디저트', '기타전통주', '식용유지', '선물세트', '야채', '홈타입', '커피', '삼각김밥', '냉장피자', '소스류', '햄버거', '김밥', '양주', '유제품', '막걸리', '즉석조리', '수축산/계란', '두유', '와인', '초밥류', '샌드위치', '호빵', '무알콜맥주'] / 총 52개
💡 그 중 예외로 구제되어 살아남은 중분류: ['기타전통주', '삼각김밥', '떡', '햄버거', '냉장피자', '국산맥주', '양주', '샌드위치', '김밥', '와인', '초밥류', '도시락', '하이볼', '고급', '냉동디저트'] / 총 15개

In [4]:
import polars as pl

# 1. 데이터 경로 설정
input_path = "/Users/hajiyoon/workspace/data/processed/pareto_processed_results.csv"
output_path = "/Users/hajiyoon/workspace/data/processed/pareto_processed_results_v2.csv"

# 2. 데이터 읽기
df = pl.read_csv(input_path)

# 3. '상품명' 컬럼 왼쪽에 '세븐일레븐 ' 추가하기
# pl.lit()은 리터럴(고정된 문자열)을 의미해! 
# 고정 문자열과 기존 컬럼을 더하기(+)만 하면 바로 합쳐져.
df = df.with_columns(
    (pl.lit("세븐일레븐 ") + pl.col("상품명")).alias("상품명")
)

# 4. 수정된 데이터 저장
df.write_csv(output_path)

print(f"✅ 처리가 완료되었어! 결과는 '{output_path}'에 저장됐어.")

✅ 처리가 완료되었어! 결과는 '/Users/hajiyoon/workspace/data/processed/pareto_processed_results_v2.csv'에 저장됐어.

In [10]:
import os
import time
import random
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote

# 1. 환경 변수 및 API 설정
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")

# 2. 고정 설정 값
INPUT_PATH = '/Users/hajiyoon/workspace/data/processed/pareto_processed_results.csv'
OUTPUT_PATH = 'seven_eleven_full_reviews.csv'
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

def get_blog_content(url):
    """
    네이버 블로그의 복잡한 구조를 분석하여 본문 텍스트를 추출합니다.
    """
    try:
        # 1차 접속: iframe의 src 주소 추출
        response = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        iframe = soup.find('iframe', id='mainFrame')
        if not iframe:
            return "본문 추출 실패 (iframe 없음)"
        
        # ✅ 수정 1: iframe src 절대경로 여부 분기 처리
        src = iframe['src']
        if src.startswith('http'):
            inner_url = src  # 이미 절대경로이면 그대로 사용
        else:
            inner_url = "https://blog.naver.com" + src  # 상대경로이면 도메인 붙이기
        
        # 2차 접속 전 짧은 대기 (안정성 확보)
        time.sleep(random.uniform(0.5, 1))
        
        # 2차 접속: 실제 본문 페이지 파싱
        inner_response = requests.get(inner_url, headers=HEADERS, timeout=10)
        inner_soup = BeautifulSoup(inner_response.text, 'html.parser')
        
        # 본문 태그 순차 탐색 (신버전 -> 구버전 -> 아주 오래된 버전 -> 모바일)
        # 1순위: div.se-main-container (신버전 스마트에디터 ONE)
        content_area = inner_soup.select_one('div.se-main-container')
        
        # 2순위: div#postViewArea (구버전 스마트에디터 2.0)
        if not content_area:
            content_area = inner_soup.select_one('div#postViewArea')
            
        # 3순위: div[id^='post-view'] (아주 오래된 구버전)
        if not content_area:
            content_area = inner_soup.select_one("div[id^='post-view']")
            
        # 4순위: div.se-viewer (모바일/기타)
        if not content_area:
            content_area = inner_soup.select_one('div.se-viewer')
            
        # 텍스트 추출 및 정제
        if content_area:
            text = content_area.get_text(separator='\n', strip=True)
            return text if text else "본문 추출 실패 (텍스트 없음)"
        else:
            return "본문 추출 실패 (JS 렌더링 필요)"
            
    except Exception as e:
        return f"크롤링 오류: {str(e)}"

def main():
    # .env 파일 체크
    if not CLIENT_ID or not CLIENT_SECRET:
        print("경고: .env 파일에 NAVER_CLIENT_ID 또는 NAVER_CLIENT_SECRET이 설정되지 않았습니다.")
        if not os.path.exists('.env'):
            with open('.env', 'w') as f:
                f.write("NAVER_CLIENT_ID=\nNAVER_CLIENT_SECRET=\n")
            print(".env 파일 템플릿을 생성했습니다. API 키를 입력 후 다시 실행해 주세요.")
        return

    # 데이터 로드
    if not os.path.exists(INPUT_PATH):
        print(f"오류: '{INPUT_PATH}' 경로에 파일이 존재하지 않습니다.")
        return

    df = pd.read_csv(INPUT_PATH)
    
    # ✅ 수정 2: 변수명 items → product_list (API 응답의 'items'와 충돌 방지)
    product_list = df['상품명'].dropna().unique()
    
    results = []
    print(f"총 {len(product_list)}개의 검색 키워드에 대해 크롤링을 수행합니다.")

    for i, item in enumerate(product_list, 1):
        search_query = f"세븐일레븐 {item}"
        print(f"[{i}/{len(product_list)}] 검색어: {search_query}")
        
        # 네이버 블로그 검색 API 호출 (상위 3개, 관련도순)
        api_url = f"https://openapi.naver.com/v1/search/blog.json?query={quote(search_query)}&display=3&sort=sim"
        api_headers = {
            "X-Naver-Client-Id": CLIENT_ID,
            "X-Naver-Client-Secret": CLIENT_SECRET
        }
        
        try:
            api_res = requests.get(api_url, headers=api_headers)
            if api_res.status_code != 200:
                print(f"  - API 호출 실패 (상태 코드: {api_res.status_code})")
                continue
            
            items_list = api_res.json().get('items', [])
            
            for blog in items_list:
                # 제목 HTML 태그 제거
                title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                link = blog['link']
                
                print(f"  - 크롤링 중: {title[:25]}...")
                content = get_blog_content(link)
                
                results.append({
                    '검색어': search_query,
                    '블로그제목': title,
                    '블로그링크': link,
                    '본문내용': content
                })
                
                # 블로그 크롤링 간 랜덤 대기 (1~3초)
                time.sleep(random.uniform(1, 3))
                
        except Exception as e:
            print(f"  - 검색 처리 중 오류: {e}")
            continue

    # 결과물 저장
    if results:
        result_df = pd.DataFrame(results)
        result_df.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
        print(f"\n작업 완료! 결과가 {OUTPUT_PATH}에 저장되었습니다. (총 {len(results)}건)")
    else:
        print("\n수집된 결과가 없습니다.")

if __name__ == "__main__":
    main()

총 1084개의 검색 키워드에 대해 크롤링을 수행합니다.
[1/1084] 검색어: 세븐일레븐 CJ)둥근햇반210g
  - 크롤링 중: [무료배송]CJ제일제당 둥근 햇반 210g 3...
  - 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 크롤링 중: 홈플러스-CJ 둥근 햇반 210G*10입...
[2/1084] 검색어: 세븐일레븐 CJ)큰햇반300g
  - 크롤링 중: CJ 햇반 큰공기 300g 18개 최신세일중특...
  - 크롤링 중: CJ 햇반 큰공기, 18개, 300g 특별베스...
  - 크롤링 중: CJ 햇반 백미 큰공기 300gX30개, 30...
[3/1084] 검색어: 세븐일레븐 오뚜기)오뚜기밥210g
  - 크롤링 중: 오뚜기 든든쌀밥 210g 36개...
  - 크롤링 중: 오뚜기밥 210g 24개 칼로리 장단점 최저가...
  - 크롤링 중: 즉석밥 비교 햇반 오뚜기밥 더미식밥 210g ...
[4/1084] 검색어: 세븐일레븐 CJ)작은햇반130g
  - 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 크롤링 중: 햇반 백미 작은공기 130g 추천, CJ 즉석...
  - 크롤링 중: 제일제당 CJ 햇반 작은공기 130g X 24...
[5/1084] 검색어: 세븐일레븐 오뚜기)맛있는큰밥300g
  - 크롤링 중: 오뚜기 맛있는 오뚜기밥 큰밥 300g 18개 ...
  - 크롤링 중: 오뚜기 맛있는 오뚜기밥 큰밥 300g 4개 맞...
  - 크롤링 중: 지은 밥맛 그대로! 오뚜기 큰밥 300g 24...
[6/1084] 검색어: 세븐일레븐 CJ)햇반미역국밥(컵반)
  - 크롤링 중: [세븐일레븐 편의점] cj 햇반 컵반 미역국밥...
  - 크롤링 중: CJ 햇반 컵반 미역국밥 후기｜전자레인지로 먹...
  - 크롤링 중: 식품) cj 햇반 컵반 미역국밥 훅이...
[7/1084] 검색어: 세븐일레븐 동원)양반전복죽285g
  - 크롤링 중: 동원F&B 양반 전복죽 285g...
  - 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 크롤링 중: 타임! ...동원 양반 단호박죽 285g 용기...
[8/1084] 검색어: 세븐일레븐 동원)양반쇠고기죽285g
  - 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 크롤링 중: 타임! ...동원 양반 단호박죽 285g 용기...
  - 크롤링 중: gs25 편의점 죽 양반 누룽지 닭죽 양반 쇠...
[9/1084] 검색어: 세븐일레븐 CJ)햇반발아현미밥210g
  - 크롤링 중: 햇반 발아현미밥 210g 24개 영양 만점 편...
  - 크롤링 중: 햇반 발아현미밥 210g, 3개 솔직 리뷰...
  - 크롤링 중: 햇반 현미밥 먹어보니.. / CJ 햇반 컵반 ...
[10/1084] 검색어: 세븐일레븐 동원)양반누룽지닭죽285g
  - 크롤링 중: 내돈내산 동원 양반 누룽지닭죽 후기...
  - 크롤링 중: gs25 편의점 죽 양반 누룽지 닭죽 양반 쇠...
  - 크롤링 중: 편의점 죽 / 동원 양반 단호박죽 전복죽 소고...
[11/1084] 검색어: 세븐일레븐 동원)양반야채죽285g
  - 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 크롤링 중: 동원 양반 야채죽 세븐일레븐...
  - 크롤링 중: 타임! ...동원 양반 단호박죽 285g 용기...
[12/1084] 검색어: 세븐일레븐 동원)양반단호박죽285g
  - 크롤링 중: 타임! ...동원 양반 단호박죽 285g 용기...
  - 크롤링 중: #광고 양반 단호박죽, 285g, 12개...
  - 크롤링 중: 동원 )양반죽 285g 1+1행사중...
[13/1084] 검색어: 세븐일레븐 CJ)햇반흑미밥210g
  - 크롤링 중: [CJ]햇반 흑미밥 210g...
  - 크롤링 중: CJ제일제당 햇반 흑미밥 210g 리뷰: 맛과...
  - 크롤링 중: CJ제일제당 햇반 흑미밥 210g 리뷰...
[14/1084] 검색어: 세븐일레븐 동원)양반참치죽285g
  - 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 크롤링 중: 타임! ...동원 양반 단호박죽 285g 용기...
  - 크롤링 중: 동원F&B 양반 전복죽 285g...
[15/1084] 검색어: 세븐일레븐 오뚜기)발아현미밥210g
  - 크롤링 중: 오뚜기 발아현미밥 210g 솔직 후기...
  - 크롤링 중: 오뚜기 맛있는 오뚜기밥 발아현미 210g, 3...
  - 크롤링 중: 오뚜기 맛있는 오뚜기밥 발아현미 210g, 3...
[16/1084] 검색어: 세븐일레븐 CJ)스팸마요덮밥(컵반)
  - 크롤링 중: CJ제일제당 햇반컵반 big컵반 치킨마요덮밥,...
  - 크롤링 중: 햇반컵밥 스팸마요덮밥 자취 간편요리 컵반 후기...
  - 크롤링 중: [GS25 편의점 추천메뉴] CJ 햇반 컵반 ...
[17/1084] 검색어: 세븐일레븐 CJ)햇반황태국밥(컵반)
  - 크롤링 중: 아침에 간편한 황태콩나물국밥, CJ 햇반 컵반...
  - 크롤링 중: CJ 햇반 컵반 황태국밥 포함 25종, 간편식...
  - 크롤링 중: CJ 햇반컵반 황태국밥...
[18/1084] 검색어: 세븐일레븐 오뚜기)발아흑미밥210g
  - 크롤링 중: 오뚜기 발아흑미 즉석잡곡밥, 210g, 12개...
  - 크롤링 중: 300g 오뚜기밥 흰밥 작은밥 150g 큰밥 ...
  - 크롤링 중: 오뚜기 발아흑미 즉석잡곡밥 210g 12개...
[19/1084] 검색어: 세븐일레븐 PB)우리쌀누룽지(큰컵)
  - 크롤링 중: 세븐일레븐 PB상품 우리쌀누룽지...
  - 크롤링 중: 편의점 누룽지 세븐일레븐 PB상품 우리쌀누룽지...
  - 크롤링 중: 일본 편의점 추천 세븐일레븐 빵 과자 라면 술...
[20/1084] 검색어: 세븐일레븐 오뚜기)카레컵밥
  - 크롤링 중: 세븐일레븐 편의점 햇반 컵반 할인 오뚜기 컵밥...
  - 크롤링 중: [24.08.10] 오뚜기 카레 컵밥이 땡겼던...
  - 크롤링 중: 컵밥 할인 1+1, 2+1, CU, GS25,...
[21/1084] 검색어: 세븐일레븐 CJ)작은햇반100%현미밥130g
  - 크롤링 중: CJ햇반 100% 현미밥 구매 후기(130g ...
  - 크롤링 중: [집사밥리뷰]동원 양반 100%밥 130g현미...
  - 크롤링 중: 다이어트에 효과적인 CJ 햇반 ‘100% 현미...
[22/1084] 검색어: 세븐일레븐 CJ)스팸김치덮밥(컵반)
  - 크롤링 중: CJ햇반컵반 스팸김치덮밥 내돈내산후기...
  - 크롤링 중: CJ 햇반 컵반 스팸김치덮밥 가격 칼로리 컵밥...
  - 크롤링 중: CJ 컵반 빅 스팸 김치 덮밥 컵밥 두번 째 ...
[23/1084] 검색어: 세븐일레븐 CJ)햇반치킨마요덮밥컵반
  - 크롤링 중: [CJ 햇반 치킨마요 덮밥]... 고소한 마요...
  - 크롤링 중: CJ제일제당 햇반컵반 big컵반 치킨마요덮밥,...
  - 크롤링 중: CJ 햇반 컵반 치킨 마요 덮밥....
[24/1084] 검색어: 세븐일레븐 오뚜기)쇠고기미역국밥컵밥
  - 크롤링 중: 오뚜기 진한 쇠고기미역국밥 컵밥 후기 가족 여...
  - 크롤링 중: 세븐일레븐-맛있는 오뚜기 컵밥 옛날 진한 쇠고...
  - 크롤링 중: 컵밥 추천 내돈내산 차돌강된장 보리밥 쇠고기 ...
[25/1084] 검색어: 세븐일레븐 오뚜기)김치참치덮밥(컵밥)
  - 크롤링 중: 오뚜기 김치참치덮밥... 계란국까지 즐길 수 ...
  - 크롤링 중: 오뚜기 컵밥 : 김치참치 덮밥 오삼불고기 덮밥...
  - 크롤링 중: 오뚜기 김치참치덮밥 컵밥 vs 무인양품 김치참...
[26/1084] 검색어: 세븐일레븐 오뚜기)톡톡김치알밥(컵밥)
  - 크롤링 중: 세븐일레븐 할인행사 오뚜기톡톡김치알밥 컵밥 소...
  - 크롤링 중: 오뚜기 컵밥 톡톡 김치알밥 계란국이 맛있었다...
  - 크롤링 중: 오뚜기 톡톡김치알밥 컵밥 추천 순위 1위 먹어...
[27/1084] 검색어: 세븐일레븐 CJ)강된장보리비빔밥(컵반)
  - 크롤링 중: 강된장보리밥과 비교해보는 cj햇반컵반 강된장보...
  - 크롤링 중: 전주돌솥비빔밥, CJ 햇반 컵반 강된장보리비빔...
  - 크롤링 중: 세븐일레븐 편의점 CJ 햇반컵반 강된장보리비빔...
[28/1084] 검색어: 세븐일레븐 CJ)햇반매일잡곡밥210g
  - 크롤링 중: [CJ]햇반 매일잡곡밥 210g...
  - 크롤링 중: CJ제일제당 햇반 매일잡곡밥 210g 사용 후...
  - 크롤링 중: CJ제일제당 햇반 매일찰잡곡밥 210g - 편...
[29/1084] 검색어: 세븐일레븐 오뚜기)작은밥150g
  - 크롤링 중: 세븐일레븐 할인행사 오뚜기톡톡김치알밥 컵밥 소...
  - 크롤링 중: 오뚜기 맛있는 오뚜기밥 작은밥 150g 30개...
  - 크롤링 중: 일상 속 한 끼 고민 해결! 오뚜기 작은밥 1...
[30/1084] 검색어: 세븐일레븐 삼양)까르보불닭떡볶이(컵)
  - 크롤링 중: 삼양 - 까르보 불닭떡볶이...
  - 크롤링 중: 까르보불닭 떡볶이, 별로안매운데?...
  - 크롤링 중: 편의점 떡볶이. 세븐일레븐 추천메뉴 (삼양 까...
[31/1084] 검색어: 세븐일레븐 오뚜기)차돌강된장보리밥컵밥
  - 크롤링 중: 오뚜기컵밥 차돌강된장보리밥 뜯었더니 안에 이게...
  - 크롤링 중: 오뚜기 컵밥 차돌강된장보리밥 먹어봄...
  - 크롤링 중: 컵밥 중 제일 맛있는 최애 오뚜기 차돌강된장 ...
[32/1084] 검색어: 세븐일레븐 CJ)김치날치알밥(컵반)
  - 크롤링 중: cj 햇반 컵반 추천 "김치날치알밥" 라면이랑...
  - 크롤링 중: CJ제일제당 햇반컵반 BIG 김치날치알밥...
  - 크롤링 중: CJ 컵반 김치날치알밥/치컨커리덮밥 후기...
[33/1084] 검색어: 세븐일레븐 CJ)햇반누룽지닭백숙죽267g
  - 크롤링 중: CJ 햇반 누룽지닭백숙죽 267g  내돈내산 ...
  - 크롤링 중: CJ햇반듬뿍누룽지닭백숙죽 VS CJ햇반전복내장...
  - 크롤링 중: CJ 햇반죽 소고기죽 누룽지닭백숙죽 내돈내산 ...
[34/1084] 검색어: 세븐일레븐 CJ)버터장조림비빔밥(컵반)
  - 크롤링 중: CJ 햇반 컵반 버터장조림 비빔밥 칼로리, 영...
  - 크롤링 중: CJ 햇반 컵반 버터 장조림 비빔밥....
  - 크롤링 중: CJ 제일제당 햇반 컵반 버터 장조림 비빔밥...
[35/1084] 검색어: 세븐일레븐 CJ)햇반200g*3입
  - 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 크롤링 중: 민생회복 지원금 소비쿠폰 사용처 GS25 CU...
  - 크롤링 중: CJ 햇반 솥반 전복내장영양밥 조금 아쉬운 후...
[36/1084] 검색어: 세븐일레븐 CJ)작은햇반발아현미밥130g
  - 크롤링 중: 발아현미 즉석밥 추천, CJ 햇반 발아현미 작...
  - 크롤링 중: CJ 제일제당 햇반 발아현미밥 130g x 3...
  - 크롤링 중: CJ 햇반 발아현미 작은공기 130g 6개 즉...
[37/1084] 검색어: 세븐일레븐 CJ)햇반전복죽267g
  - 크롤링 중: CJ 햇반 누룽지닭백숙죽 267g  내돈내산 ...
  - 크롤링 중: 햇반 전복내장죽267G 8개 13,900원 @...
  - 크롤링 중: 햇반 맞춤토핑 전복내장죽, 소고기죽...
[38/1084] 검색어: 세븐일레븐 오뚜기)참치마요덮밥(컵밥)
  - 크롤링 중: 세븐일레븐-오뚜기 참치마요 덮밥-서울 언주역 ...
  - 크롤링 중: 오뚜기컵밥 계란국 포함 참치마요 덮밥 후기...
  - 크롤링 중: 오뚜기 컵밥 종류 참치마요덮밥, 진짬뽕밥 라밥...
[39/1084] 검색어: 세븐일레븐 오뚜기)골드치킨마요덮밥(컵밥)
  - 크롤링 중: [오뚜기]신제품 골드치킨마요 컵밥 후기~...
  - 크롤링 중: 오뚜기 골드 치킨마요컵밥...
  - 크롤링 중: 오뚜기 골드 치킨마요 컵밥...
[40/1084] 검색어: 세븐일레븐 빙그레)바나나우유240ml
  - 크롤링 중: [세븐일레븐신상 빙그레 무가당 바나나맛우유] ...
  - 크롤링 중: 병오년은 세븐일레븐 유부초밥과 빙그레바나나우유...
  - 크롤링 중: 세븐일레븐 디저트39 바나나우유 솔직리뷰...
[41/1084] 검색어: 세븐일레븐 서울)커피우유300ml
  - 크롤링 중: (세븐일레븐 2+1) 서울우유 딸기우유 커피우...
  - 크롤링 중: 서울우유 검은콩 블랙라벨 세븐일레븐 4월행사 ...
  - 크롤링 중: 세븐일레븐 커피우유:)...
[42/1084] 검색어: 세븐일레븐 빙그레)딸기맛우유240ml
  - 크롤링 중: 편의점 딸기우유 빙그레 딸기맛우유 240ml ...
  - 크롤링 중: 빙그레 딸기맛 우유 240ml 바코드...
  - 크롤링 중: 빙그레 단지우유... 바나나우유 딸기우유 반반...
[43/1084] 검색어: 세븐일레븐 서울)초코우유300ml
  - 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 300ml 1...
  - 크롤링 중: 세븐일레븐 초코우유...
  - 크롤링 중: 세븐일레븐 디저트39 초코우유 솔직리뷰(초코바...
[44/1084] 검색어: 세븐일레븐 서울)딸기우유300ml
  - 크롤링 중: [편의점우유] 세븐일레븐 딸기우유...
  - 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말차와 딸기...
  - 크롤링 중: (세븐일레븐 2+1) 서울우유 딸기우유 커피우...
[45/1084] 검색어: 세븐일레븐 남양)초코에몽190ml
  - 크롤링 중: 간식 추천 편의점 음료 회사 간식 초코우유 초...
  - 크롤링 중: 남양유업 말차에몽 190ml 성분 분석 및 칼...
  - 크롤링 중: 남양 말차에몽 후기 초코에몽·딸기에몽과 맛 비...
[46/1084] 검색어: 세븐일레븐 빙그레)바나나우유무가당240ml
  - 크롤링 중: [세븐일레븐신상 빙그레 무가당 바나나맛우유] ...
  - 크롤링 중: 빙그레 바나나우유 유리컵... vs 무가당 맛...
  - 크롤링 중: (대영) 빙그레 바나나우유 무가당 no sug...
[47/1084] 검색어: 세븐일레븐 매일)허쉬초코팩235ml
  - 크롤링 중: [음료] 매일유업 허쉬초콜릿드링크 프로틴 23...
  - 크롤링 중: [이벤트] 영어듣기능력평가 대비 리스닝 이벤트...
  - 크롤링 중: 4월 편의점 음료 할인 행사 총정리(세븐일레븐...
[48/1084] 검색어: 세븐일레븐 빙그레)바나나라이트240ml
  - 크롤링 중: (세븐일레븐 2+1) 빙그레 바나나 라이트 2...
  - 크롤링 중: 빙그레 단지우유 무가당 바나나맛우유 240ml...
  - 크롤링 중: 빙그레 단지우유 바나나우유라이트 240ml 8...
[49/1084] 검색어: 세븐일레븐 서울)커피우유200ml
  - 크롤링 중: 서울우유 커피 200ml 8개...
  - 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말차와 딸기...
  - 크롤링 중: 쿠팡 로켓 배송 서울우유 커피, 200ml, ...
[50/1084] 검색어: 세븐일레븐 빙그레)사이즈업아메리카노350ml
  - 크롤링 중: 빙그레 아카페라 사이즈업 디카페인 아메리카노(...
  - 크롤링 중: 디카페인 아메리카노, 350ml... 잡은 빙...
  - 크롤링 중: 블랙 무라벨 370ml, 빙그레 아카페라 사이...
[51/1084] 검색어: 세븐일레븐 빙그레)메로나맛우유240ml
  - 크롤링 중: 빙그레 메로나맛우유 240ml 바코드...
  - 크롤링 중: 빙그레 단지우유240ml 3종 12개바나나4개...
  - 크롤링 중: 빙그레 메로나맛 우유 칼로리, 당 아이 간식으...
[52/1084] 검색어: 세븐일레븐 서울)초코우유200ml
  - 크롤링 중: 세븐일레븐편의점우유후기... 백제신라고구마라떼...
  - 크롤링 중: 세븐일레븐 키티 스트로베리 :: 초코에 빠진딸...
  - 크롤링 중: [세븐일레븐우유3총사]... 만든 딸기우유 초...
[53/1084] 검색어: 세븐일레븐 서울)딸기우유200ml
  - 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말차와 딸기...
  - 크롤링 중: [세븐일레븐우유3총사] 각기다른원유로 만든 딸...
  - 크롤링 중: 세븐일레븐 키티 스트로베리 :: 초코에 빠진딸...
[54/1084] 검색어: 세븐일레븐 빙그레)사이즈업라떼350ml
  - 크롤링 중: 세븐일레븐 빙그레 비비빅라떼 vs 롯데 마시는...
  - 크롤링 중: 비비빅 라떼 / 롯데푸드 마시는 빠삐코 초코우...
  - 크롤링 중: 빙그레 아카페라 사이즈업 돌체(연유)라떼 35...
[55/1084] 검색어: 세븐일레븐 PB)오구초코타임200ml
  - 크롤링 중: [알뜰 정보] 세븐일레븐 세이브 세일 4월 1...
  - 크롤링 중: [CU/GS25/세븐일레븐] 4월 2주차 편의...
  - 크롤링 중: [CU/GS25/세븐일레븐] 3월 5주차 편의...
[56/1084] 검색어: 세븐일레븐 매일)바리스타라떼PET475ml
  - 크롤링 중: 수혈은 이걸로? 바리스타룰스 그란데 라떼 내돈...
  - 크롤링 중: 세븐일레븐 커피 바리스타룰스 그란데 아메리카노...
  - 크롤링 중: [내돈내산] 매일유업 바리스타룰스 그란데 라떼...
[57/1084] 검색어: 세븐일레븐 덴마크)딸기딸기우유300ml
  - 크롤링 중: 동원 덴마크 라이트&저지방... 딸기딸기우유 ...
  - 크롤링 중: 세븐일레븐 : 개콘 덴마크 픽미 딸기 우유 후...
  - 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 300ml 1...
[58/1084] 검색어: 세븐일레븐 남양)초코에몽250ml
  - 크롤링 중: (세븐일레븐2+1)남양 초코에몽 250ml...
  - 크롤링 중: [11번가] 세븐일레븐 남양 초코에몽250ml...
  - 크롤링 중: 7월 세븐일레븐 편의점 행사 세븐데이 세븐득득...
[59/1084] 검색어: 세븐일레븐 매일)바리스타아메리카노PET475m
  - 크롤링 중: 몽베스트 생수 500ml 내추럴 미네랄워터 드...
  - 크롤링 중: 세븐일레븐 8월행사 추천 1+1 2+1 이번에...
  - 크롤링 중: 세븐일레븐 7월행사 추천 7ELEVEN 이번 ...
[60/1084] 검색어: 세븐일레븐 빙그레)사이즈업바닐라라떼350ml
  - 크롤링 중: 빙그레 아카페라 사이즈업 바닐라 라떼 350m...
  - 크롤링 중: 빙그레 아카페라 바닐라 라떼 사이즈업 350m...
  - 크롤링 중: 빙그레 아카페라 사이즈업 바닐라 라떼 350m...
[61/1084] 검색어: 세븐일레븐 덴마크)초코초코우유300ml
  - 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 300ml 1...
  - 크롤링 중: 세븐일레븐편의점우유후기... 백제신라고구마라떼...
  - 크롤링 중: 세븐일레븐 초코우유...
[62/1084] 검색어: 세븐일레븐 빙그레)스페셜티예가체프460ml
  - 크롤링 중: 빙그레 아카페라 스페셜티 에티오피아 예가체프 ...
  - 크롤링 중: 아카페라 스페셜티 에티오피아 예가체프 460m...
  - 크롤링 중: 예가체프] 스페셜티 등급... 가성비까지 잡은...
[63/1084] 검색어: 세븐일레븐 삼립)신선가득꿀호떡200g
  - 크롤링 중: 삼립)신선가득꿀호떡 1+1행사...
  - 크롤링 중: [삼립] 편의점 삼립호떡 미니 꿀호떡 200g...
  - 크롤링 중: 서진이네2 삼립호떡 쌀커스터드 바닐라크림 꿀호...
[64/1084] 검색어: 세븐일레븐 삼립)신선한치즈후레쉬팡140g
  - 크롤링 중: 편의점 음식 리뷰 - GS25 삼립 신선한 치...
  - 크롤링 중: 플레인,세븐일레븐 쫀쫀 크림... 순삭 크림롤...
  - 크롤링 중: 세븐일레븐 샌드위치 삼립)NEW프리미엄햄에그샌...
[65/1084] 검색어: 세븐일레븐 삼립)정통보름달88g
  - 크롤링 중: [SPC 삼립 보름달 달토끼 방앗간 쑥임자 8...
  - 크롤링 중: 보름달 빵 연단팥 편의점 삼립 신상 후기...
  - 크롤링 중: [삼립] 정통 보름달 딸기 시식기 : "흰 우...
[66/1084] 검색어: 세븐일레븐 PB)쏘스윗카스테라160g
  - 크롤링 중: 세븐일레븐 모닝콤보 AM 7~11시 핫아메리카...
  - 크롤링 중: 세븐일레븐 디저트 폭신 달콤한 쏘스윗 카스테라...
  - 크롤링 중: 세븐일레븐&롯데웰푸드 쏘스윗 카스테라 편의점 ...
[67/1084] 검색어: 세븐일레븐 삼립)로켓단초코롤85g
  - 크롤링 중: 삼립 포켓몬 돌아온 로켓단 초코롤, 2개, 8...
  - 크롤링 중: 삼립 돌아온 로켓단 초코롤 후기 라떼 참 맛있...
  - 크롤링 중: 돌아온 로켓단 초코롤 후기 (scp 삼립 빵)...
[68/1084] 검색어: 세븐일레븐 삼립)주종발효단팥크림빵115g
  - 크롤링 중: 세븐일레븐 주종 발효 단팥 크림빵 반갈샷, 전...
  - 크롤링 중: [빵/간식] 안이 빵빵한 삼립 '주종발효 단팥...
  - 크롤링 중: 삼립빵 시리즈 빵추천 주종발효 단팥크림빵 맛있...
[69/1084] 검색어: 세븐일레븐 롯데)미니땅콩크림샌드(5입)
  - 크롤링 중: 롯데자이언츠 쌔리라 빠지락라면 메이플볼 마롱미...
  - 크롤링 중: 롯데 미니샌드 땅콩크림 CU편의점 구매후기...
  - 크롤링 중: 20241226_롯데_미니샌드 땅콩크림...
[70/1084] 검색어: 세븐일레븐 삼립)크림빵75g
  - 크롤링 중: 삼립 대왕크림빵 크림대빵 파는곳 가격 칼로리 ...
  - 크롤링 중: 삼립 대왕크림빵 크리미대빵 맛보기...
  - 크롤링 중: GS 크림대빵 가격 편의점 삼립 크림빵 대왕 ...
[71/1084] 검색어: 세븐일레븐 엔제이)훈와리밀크카스테라
  - 크롤링 중: 세븐일레븐 편의점 일본 간식 훈와리밀크카스테라...
  - 크롤링 중: 프로틴, 오트몬드 프로틴, 훈와리 밀크 계란 ...
  - 크롤링 중: 세븐일레븐 훈와리 밀크 카스테라 칼로리 성분 ...

KeyboardInterrupt:

In [13]:
import os
import time
import random
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote

# Selenium 관련 임포트
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# 1. 환경 변수 및 API 설정
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")

# 2. 고정 설정 값
INPUT_PATH = '/Users/hajiyoon/workspace/data/processed/pareto_processed_results.csv'
OUTPUT_PATH = 'seven_eleven_full_reviews_selenium.csv'


def get_blog_content(driver, url):
    """
    Selenium을 사용하여 네이버 블로그 본문을 추출합니다.
    """
    try:
        # ✅ 수정 2: 함수 시작 시 항상 default_content로 초기화 (frame 꼬임 방지)
        driver.switch_to.default_content()

        # 페이지 접속
        driver.get(url)

        # iframe(mainFrame) 전환 대기 및 이동
        try:
            wait = WebDriverWait(driver, 10)
            wait.until(EC.presence_of_element_located((By.ID, "mainFrame")))
            driver.switch_to.frame("mainFrame")
        except:
            return "본문 추출 실패 (iframe 미확인)"

        # ✅ 수정 5: 페이지 body 로딩을 한 번만 대기한 뒤, find_elements로 즉시 탐색
        #           (셀렉터마다 3초씩 대기하던 방식 → 최대 12초 소요 문제 해결)
        try:
            WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.TAG_NAME, "body"))
            )
        except:
            return "본문 추출 실패 (페이지 로딩 타임아웃)"

        # 본문 태그 후보군 (순서대로 즉시 탐색)
        selectors = [
            "div.se-main-container",  # 신버전 스마트에디터 ONE
            "div#postViewArea",       # 구버전 스마트에디터 2.0
            "div[id^='post-view']",   # 아주 오래된 구버전
            "div.se-viewer"           # 모바일/기타
        ]

        for selector in selectors:
            elements = driver.find_elements(By.CSS_SELECTOR, selector)
            if elements:
                content_text = elements[0].text.strip()
                if content_text:
                    return content_text

        return "본문 추출 실패 (구조 미확인)"

    except Exception as e:
        return f"크롤링 오류: {str(e)}"
    finally:
        # iframe에서 기본 컨텐츠로 복귀 (다음 크롤링을 위해 중요)
        try:
            driver.switch_to.default_content()
        except:
            pass


def setup_driver():
    """
    Mac M1/M2 환경에 최적화된 Selenium Chrome 드라이버를 설정합니다.
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument(
        "user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)
    return driver


def main():
    # .env 파일 체크
    if not CLIENT_ID or not CLIENT_SECRET:
        print("오류: .env 파일에 NAVER_CLIENT_ID 및 NAVER_CLIENT_SECRET이 필요합니다.")
        return

    # 데이터 로드
    if not os.path.exists(INPUT_PATH):
        print(f"오류: '{INPUT_PATH}' 파일을 찾을 수 없습니다.")
        return

    df = pd.read_csv(INPUT_PATH)

    # ✅ 수정 1: 변수명 items → product_list (API 응답의 'items'와 혼동·충돌 방지)
    product_list = df['상품명'].dropna().unique()

    results = []

    # ✅ 수정 6: API 호출 횟수 카운팅 초기화 (하루 25,000건 한도 추적)
    api_call_count = 0

    print("크롬 드라이버를 시작합니다 (Headless 모드)...")
    driver = setup_driver()

    try:
        print(f"총 {len(product_list)}개의 상품 키워드 크롤링 시작...")

        for i, item in enumerate(product_list, 1):
            search_query = f"세븐일레븐 {item}"
            print(f"[{i}/{len(product_list)}] 검색어: {search_query}")

            # 네이버 블로그 검색 API 호출
            api_url = (
                f"https://openapi.naver.com/v1/search/blog.json"
                f"?query={quote(search_query)}&display=3&sort=sim"
            )
            api_headers = {
                "X-Naver-Client-Id": CLIENT_ID,
                "X-Naver-Client-Secret": CLIENT_SECRET
            }

            try:
                res = requests.get(api_url, headers=api_headers)

                # ✅ 수정 6: API 호출마다 카운트 증가 및 출력
                api_call_count += 1
                print(f"  - 누적 API 호출 횟수: {api_call_count}건 / 일일 한도 25,000건")

                if res.status_code != 200:
                    print(f"  - API 호출 실패 (Code: {res.status_code})")
                    continue

                blog_items = res.json().get('items', [])

                for blog in blog_items:
                    title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                    link = blog['link']

                    # ✅ 수정 3: 네이버 블로그 외 링크 사전 필터링 (불필요한 Selenium 호출 방지)
                    if 'blog.naver.com' not in link:
                        print(f"  - 네이버 블로그 외 링크 제외: {link}")
                        results.append({
                            '검색어': search_query,
                            '블로그제목': title,
                            '블로그링크': link,
                            '본문내용': '네이버 블로그 외 링크 제외'
                        })
                        continue

                    print(f"  - 셀레니움 크롤링 중: {title[:20]}...")
                    content = get_blog_content(driver, link)

                    results.append({
                        '검색어': search_query,
                        '블로그제목': title,
                        '블로그링크': link,
                        '본문내용': content
                    })

                    time.sleep(random.uniform(1, 3))

            except Exception as e:
                print(f"  - 처리 중 예외 발생: {e}")
                continue

            # ✅ 수정 4: 10개 상품마다 중간 저장 (오류 발생 시 데이터 유실 방지)
            if i % 10 == 0 and results:
                pd.DataFrame(results).to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
                print(f"  - 중간 저장 완료 ({i}번째 / 누적 {len(results)}건)")

    finally:
        print("\n드라이버를 종료합니다.")
        driver.quit()

    # 최종 결과물 저장
    if results:
        result_df = pd.DataFrame(results)
        result_df.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
        print(f"\n작업 완료! 결과가 {OUTPUT_PATH}에 저장되었습니다. (총 {len(results)}건)")
        print(f"총 API 호출 횟수: {api_call_count}건")
    else:
        print("\n수집된 데이터가 없습니다.")


if __name__ == "__main__":
    main()

크롬 드라이버를 시작합니다 (Headless 모드)...
총 1084개의 상품 키워드 크롤링 시작...
[1/1084] 검색어: 세븐일레븐 CJ)둥근햇반210g
  - 누적 API 호출 횟수: 1건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [무료배송]CJ제일제당 둥근 햇반 2...
  - 셀레니움 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 셀레니움 크롤링 중: 홈플러스-CJ 둥근 햇반 210G*1...
[2/1084] 검색어: 세븐일레븐 CJ)큰햇반300g
  - 누적 API 호출 횟수: 2건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ 햇반 큰공기 300g 18개 최...
  - 셀레니움 크롤링 중: CJ 햇반 큰공기, 18개, 300g...
  - 셀레니움 크롤링 중: CJ 햇반 백미 큰공기 300gX30...
[3/1084] 검색어: 세븐일레븐 오뚜기)오뚜기밥210g
  - 누적 API 호출 횟수: 3건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 든든쌀밥 210g 36개...
  - 셀레니움 크롤링 중: 오뚜기밥 210g 24개 칼로리 장단...
  - 셀레니움 크롤링 중: 즉석밥 비교 햇반 오뚜기밥 더미식밥 ...
[4/1084] 검색어: 세븐일레븐 CJ)작은햇반130g
  - 누적 API 호출 횟수: 4건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 셀레니움 크롤링 중: 햇반 백미 작은공기 130g 추천, ...
  - 셀레니움 크롤링 중: 제일제당 CJ 햇반 작은공기 130g...
[5/1084] 검색어: 세븐일레븐 오뚜기)맛있는큰밥300g
  - 누적 API 호출 횟수: 5건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 맛있는 오뚜기밥 큰밥 300g...
  - 셀레니움 크롤링 중: 오뚜기 맛있는 오뚜기밥 큰밥 300g...
  - 셀레니움 크롤링 중: 지은 밥맛 그대로! 오뚜기 큰밥 30...
[6/1084] 검색어: 세븐일레븐 CJ)햇반미역국밥(컵반)
  - 누적 API 호출 횟수: 6건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐 편의점] cj 햇반 컵반...
  - 셀레니움 크롤링 중: CJ 햇반 컵반 미역국밥 후기｜전자레...
  - 셀레니움 크롤링 중: 식품) cj 햇반 컵반 미역국밥 훅이...
[7/1084] 검색어: 세븐일레븐 동원)양반전복죽285g
  - 누적 API 호출 횟수: 7건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 동원F&B 양반 전복죽 285g...
  - 셀레니움 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 셀레니움 크롤링 중: 타임! ...동원 양반 단호박죽 28...
[8/1084] 검색어: 세븐일레븐 동원)양반쇠고기죽285g
  - 누적 API 호출 횟수: 8건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 셀레니움 크롤링 중: 타임! ...동원 양반 단호박죽 28...
  - 셀레니움 크롤링 중: gs25 편의점 죽 양반 누룽지 닭죽...
[9/1084] 검색어: 세븐일레븐 CJ)햇반발아현미밥210g
  - 누적 API 호출 횟수: 9건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 햇반 발아현미밥 210g 24개 영양...
  - 셀레니움 크롤링 중: 햇반 발아현미밥 210g, 3개 솔직...
  - 셀레니움 크롤링 중: 햇반 현미밥 먹어보니.. / CJ 햇...
[10/1084] 검색어: 세븐일레븐 동원)양반누룽지닭죽285g
  - 누적 API 호출 횟수: 10건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 내돈내산 동원 양반 누룽지닭죽 후기...
  - 셀레니움 크롤링 중: gs25 편의점 죽 양반 누룽지 닭죽...
  - 셀레니움 크롤링 중: 편의점 죽 / 동원 양반 단호박죽 전...
  - 중간 저장 완료 (10번째 / 누적 30건)
[11/1084] 검색어: 세븐일레븐 동원)양반야채죽285g
  - 누적 API 호출 횟수: 11건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 셀레니움 크롤링 중: 동원 양반 야채죽 세븐일레븐...
  - 셀레니움 크롤링 중: 타임! ...동원 양반 단호박죽 28...
[12/1084] 검색어: 세븐일레븐 동원)양반단호박죽285g
  - 누적 API 호출 횟수: 12건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 타임! ...동원 양반 단호박죽 28...
  - 셀레니움 크롤링 중: #광고 양반 단호박죽, 285g, 1...
  - 셀레니움 크롤링 중: 동원 )양반죽 285g 1+1행사중...
[13/1084] 검색어: 세븐일레븐 CJ)햇반흑미밥210g
  - 누적 API 호출 횟수: 13건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [CJ]햇반 흑미밥 210g...
  - 셀레니움 크롤링 중: CJ제일제당 햇반 흑미밥 210g 리...
  - 셀레니움 크롤링 중: CJ제일제당 햇반 흑미밥 210g 리...
[14/1084] 검색어: 세븐일레븐 동원)양반참치죽285g
  - 누적 API 호출 횟수: 14건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 동원 )양반죽 285g 1+1행사중...
  - 셀레니움 크롤링 중: 타임! ...동원 양반 단호박죽 28...
  - 셀레니움 크롤링 중: 동원F&B 양반 전복죽 285g...
[15/1084] 검색어: 세븐일레븐 오뚜기)발아현미밥210g
  - 누적 API 호출 횟수: 15건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 발아현미밥 210g 솔직 후기...
  - 셀레니움 크롤링 중: 오뚜기 맛있는 오뚜기밥 발아현미 21...
  - 셀레니움 크롤링 중: 오뚜기 맛있는 오뚜기밥 발아현미 21...
[16/1084] 검색어: 세븐일레븐 CJ)스팸마요덮밥(컵반)
  - 누적 API 호출 횟수: 16건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ제일제당 햇반컵반 big컵반 치킨...
  - 셀레니움 크롤링 중: 햇반컵밥 스팸마요덮밥 자취 간편요리 ...
  - 셀레니움 크롤링 중: [GS25 편의점 추천메뉴] CJ 햇...
[17/1084] 검색어: 세븐일레븐 CJ)햇반황태국밥(컵반)
  - 누적 API 호출 횟수: 17건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 아침에 간편한 황태콩나물국밥, CJ ...
  - 셀레니움 크롤링 중: CJ 햇반 컵반 황태국밥 포함 25종...
  - 셀레니움 크롤링 중: CJ 햇반컵반 황태국밥...
[18/1084] 검색어: 세븐일레븐 오뚜기)발아흑미밥210g
  - 누적 API 호출 횟수: 18건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 발아흑미 즉석잡곡밥, 210g...
  - 셀레니움 크롤링 중: 300g 오뚜기밥 흰밥 작은밥 150...
  - 셀레니움 크롤링 중: 오뚜기 발아흑미 즉석잡곡밥 210g ...
[19/1084] 검색어: 세븐일레븐 PB)우리쌀누룽지(큰컵)
  - 누적 API 호출 횟수: 19건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 PB상품 우리쌀누룽지...
  - 셀레니움 크롤링 중: 편의점 누룽지 세븐일레븐 PB상품 우...
  - 셀레니움 크롤링 중: 일본 편의점 추천 세븐일레븐 빵 과자...
[20/1084] 검색어: 세븐일레븐 오뚜기)카레컵밥
  - 누적 API 호출 횟수: 20건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 편의점 햇반 컵반 할인 오...
  - 셀레니움 크롤링 중: [24.08.10] 오뚜기 카레 컵밥...
  - 셀레니움 크롤링 중: 컵밥 할인 1+1, 2+1, CU, ...
  - 중간 저장 완료 (20번째 / 누적 60건)
[21/1084] 검색어: 세븐일레븐 CJ)작은햇반100%현미밥130g
  - 누적 API 호출 횟수: 21건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ햇반 100% 현미밥 구매 후기(...
  - 셀레니움 크롤링 중: [집사밥리뷰]동원 양반 100%밥 1...
  - 셀레니움 크롤링 중: 다이어트에 효과적인 CJ 햇반 ‘10...
[22/1084] 검색어: 세븐일레븐 CJ)스팸김치덮밥(컵반)
  - 누적 API 호출 횟수: 22건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ햇반컵반 스팸김치덮밥 내돈내산후기...
  - 셀레니움 크롤링 중: CJ 햇반 컵반 스팸김치덮밥 가격 칼...
  - 셀레니움 크롤링 중: CJ 컵반 빅 스팸 김치 덮밥 컵밥 ...
[23/1084] 검색어: 세븐일레븐 CJ)햇반치킨마요덮밥컵반
  - 누적 API 호출 횟수: 23건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [CJ 햇반 치킨마요 덮밥]... 고...
  - 셀레니움 크롤링 중: CJ제일제당 햇반컵반 big컵반 치킨...
  - 셀레니움 크롤링 중: CJ 햇반 컵반 치킨 마요 덮밥....
[24/1084] 검색어: 세븐일레븐 오뚜기)쇠고기미역국밥컵밥
  - 누적 API 호출 횟수: 24건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 진한 쇠고기미역국밥 컵밥 후기...
  - 셀레니움 크롤링 중: 세븐일레븐-맛있는 오뚜기 컵밥 옛날 ...
  - 셀레니움 크롤링 중: 컵밥 추천 내돈내산 차돌강된장 보리밥...
[25/1084] 검색어: 세븐일레븐 오뚜기)김치참치덮밥(컵밥)
  - 누적 API 호출 횟수: 25건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기 김치참치덮밥... 계란국까지 ...
  - 셀레니움 크롤링 중: 오뚜기 컵밥 : 김치참치 덮밥 오삼불...
  - 셀레니움 크롤링 중: 오뚜기 김치참치덮밥 컵밥 vs 무인양...
[26/1084] 검색어: 세븐일레븐 오뚜기)톡톡김치알밥(컵밥)
  - 누적 API 호출 횟수: 26건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 할인행사 오뚜기톡톡김치알밥...
  - 셀레니움 크롤링 중: 오뚜기 컵밥 톡톡 김치알밥 계란국이 ...
  - 셀레니움 크롤링 중: 오뚜기 톡톡김치알밥 컵밥 추천 순위 ...
[27/1084] 검색어: 세븐일레븐 CJ)강된장보리비빔밥(컵반)
  - 누적 API 호출 횟수: 27건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 강된장보리밥과 비교해보는 cj햇반컵반...
  - 셀레니움 크롤링 중: 전주돌솥비빔밥, CJ 햇반 컵반 강된...
  - 셀레니움 크롤링 중: 세븐일레븐 편의점 CJ 햇반컵반 강된...
[28/1084] 검색어: 세븐일레븐 CJ)햇반매일잡곡밥210g
  - 누적 API 호출 횟수: 28건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [CJ]햇반 매일잡곡밥 210g...
  - 셀레니움 크롤링 중: CJ제일제당 햇반 매일잡곡밥 210g...
  - 셀레니움 크롤링 중: CJ제일제당 햇반 매일찰잡곡밥 210...
[29/1084] 검색어: 세븐일레븐 오뚜기)작은밥150g
  - 누적 API 호출 횟수: 29건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 할인행사 오뚜기톡톡김치알밥...
  - 셀레니움 크롤링 중: 오뚜기 맛있는 오뚜기밥 작은밥 150...
  - 셀레니움 크롤링 중: 일상 속 한 끼 고민 해결! 오뚜기 ...
[30/1084] 검색어: 세븐일레븐 삼양)까르보불닭떡볶이(컵)
  - 누적 API 호출 횟수: 30건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼양 - 까르보 불닭떡볶이...
  - 셀레니움 크롤링 중: 까르보불닭 떡볶이, 별로안매운데?...
  - 셀레니움 크롤링 중: 편의점 떡볶이. 세븐일레븐 추천메뉴 ...
  - 중간 저장 완료 (30번째 / 누적 90건)
[31/1084] 검색어: 세븐일레븐 오뚜기)차돌강된장보리밥컵밥
  - 누적 API 호출 횟수: 31건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 오뚜기컵밥 차돌강된장보리밥 뜯었더니 ...
  - 셀레니움 크롤링 중: 오뚜기 컵밥 차돌강된장보리밥 먹어봄...
  - 셀레니움 크롤링 중: 컵밥 중 제일 맛있는 최애 오뚜기 차...
[32/1084] 검색어: 세븐일레븐 CJ)김치날치알밥(컵반)
  - 누적 API 호출 횟수: 32건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: cj 햇반 컵반 추천 "김치날치알밥"...
  - 셀레니움 크롤링 중: CJ제일제당 햇반컵반 BIG 김치날치...
  - 셀레니움 크롤링 중: CJ 컵반 김치날치알밥/치컨커리덮밥 ...
[33/1084] 검색어: 세븐일레븐 CJ)햇반누룽지닭백숙죽267g
  - 누적 API 호출 횟수: 33건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ 햇반 누룽지닭백숙죽 267g  ...
  - 셀레니움 크롤링 중: CJ햇반듬뿍누룽지닭백숙죽 VS CJ햇...
  - 셀레니움 크롤링 중: CJ 햇반죽 소고기죽 누룽지닭백숙죽 ...
[34/1084] 검색어: 세븐일레븐 CJ)버터장조림비빔밥(컵반)
  - 누적 API 호출 횟수: 34건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ 햇반 컵반 버터장조림 비빔밥 칼...
  - 셀레니움 크롤링 중: CJ 햇반 컵반 버터 장조림 비빔밥....
  - 셀레니움 크롤링 중: CJ 제일제당 햇반 컵반 버터 장조림...
[35/1084] 검색어: 세븐일레븐 CJ)햇반200g*3입
  - 누적 API 호출 횟수: 35건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 cj 햇반 클린 식단...
  - 셀레니움 크롤링 중: 민생회복 지원금 소비쿠폰 사용처 GS...
  - 셀레니움 크롤링 중: CJ 햇반 솥반 전복내장영양밥 조금 ...
[36/1084] 검색어: 세븐일레븐 CJ)작은햇반발아현미밥130g
  - 누적 API 호출 횟수: 36건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 발아현미 즉석밥 추천, CJ 햇반 발...
  - 셀레니움 크롤링 중: CJ 제일제당 햇반 발아현미밥 130...
  - 셀레니움 크롤링 중: CJ 햇반 발아현미 작은공기 130g...
[37/1084] 검색어: 세븐일레븐 CJ)햇반전복죽267g
  - 누적 API 호출 횟수: 37건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: CJ 햇반 누룽지닭백숙죽 267g  ...
  - 셀레니움 크롤링 중: 햇반 전복내장죽267G 8개 13,9...
  - 셀레니움 크롤링 중: 햇반 맞춤토핑 전복내장죽, 소고기죽...
[38/1084] 검색어: 세븐일레븐 오뚜기)참치마요덮밥(컵밥)
  - 누적 API 호출 횟수: 38건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐-오뚜기 참치마요 덮밥-서울...
  - 셀레니움 크롤링 중: 오뚜기컵밥 계란국 포함 참치마요 덮밥...
  - 셀레니움 크롤링 중: 오뚜기 컵밥 종류 참치마요덮밥, 진짬...
[39/1084] 검색어: 세븐일레븐 오뚜기)골드치킨마요덮밥(컵밥)
  - 누적 API 호출 횟수: 39건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [오뚜기]신제품 골드치킨마요 컵밥 후...
  - 셀레니움 크롤링 중: 오뚜기 골드 치킨마요컵밥...
  - 셀레니움 크롤링 중: 오뚜기 골드 치킨마요 컵밥...
[40/1084] 검색어: 세븐일레븐 빙그레)바나나우유240ml
  - 누적 API 호출 횟수: 40건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐신상 빙그레 무가당 바나나...
  - 셀레니움 크롤링 중: 병오년은 세븐일레븐 유부초밥과 빙그레...
  - 셀레니움 크롤링 중: 세븐일레븐 디저트39 바나나우유 솔직...
  - 중간 저장 완료 (40번째 / 누적 120건)
[41/1084] 검색어: 세븐일레븐 서울)커피우유300ml
  - 누적 API 호출 횟수: 41건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: (세븐일레븐 2+1) 서울우유 딸기우...
  - 셀레니움 크롤링 중: 서울우유 검은콩 블랙라벨 세븐일레븐 ...
  - 셀레니움 크롤링 중: 세븐일레븐 커피우유:)...
[42/1084] 검색어: 세븐일레븐 빙그레)딸기맛우유240ml
  - 누적 API 호출 횟수: 42건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 편의점 딸기우유 빙그레 딸기맛우유 2...
  - 셀레니움 크롤링 중: 빙그레 딸기맛 우유 240ml 바코드...
  - 셀레니움 크롤링 중: 빙그레 단지우유... 바나나우유 딸기...
[43/1084] 검색어: 세븐일레븐 서울)초코우유300ml
  - 누적 API 호출 횟수: 43건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 30...
  - 셀레니움 크롤링 중: 세븐일레븐 초코우유...
  - 셀레니움 크롤링 중: 세븐일레븐 디저트39 초코우유 솔직리...
[44/1084] 검색어: 세븐일레븐 서울)딸기우유300ml
  - 누적 API 호출 횟수: 44건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [편의점우유] 세븐일레븐 딸기우유...
  - 셀레니움 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말...
  - 셀레니움 크롤링 중: (세븐일레븐 2+1) 서울우유 딸기우...
[45/1084] 검색어: 세븐일레븐 남양)초코에몽190ml
  - 누적 API 호출 횟수: 45건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 간식 추천 편의점 음료 회사 간식 초...
  - 셀레니움 크롤링 중: 남양유업 말차에몽 190ml 성분 분...
  - 셀레니움 크롤링 중: 남양 말차에몽 후기 초코에몽·딸기에몽...
[46/1084] 검색어: 세븐일레븐 빙그레)바나나우유무가당240ml
  - 누적 API 호출 횟수: 46건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐신상 빙그레 무가당 바나나...
  - 셀레니움 크롤링 중: 빙그레 바나나우유 유리컵... vs ...
  - 셀레니움 크롤링 중: (대영) 빙그레 바나나우유 무가당 n...
[47/1084] 검색어: 세븐일레븐 매일)허쉬초코팩235ml
  - 누적 API 호출 횟수: 47건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [음료] 매일유업 허쉬초콜릿드링크 프...
  - 셀레니움 크롤링 중: [이벤트] 영어듣기능력평가 대비 리스...
  - 셀레니움 크롤링 중: 4월 편의점 음료 할인 행사 총정리(...
[48/1084] 검색어: 세븐일레븐 빙그레)바나나라이트240ml
  - 누적 API 호출 횟수: 48건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: (세븐일레븐 2+1) 빙그레 바나나 ...
  - 셀레니움 크롤링 중: 빙그레 단지우유 무가당 바나나맛우유 ...
  - 셀레니움 크롤링 중: 빙그레 단지우유 바나나우유라이트 24...
[49/1084] 검색어: 세븐일레븐 서울)커피우유200ml
  - 누적 API 호출 횟수: 49건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 서울우유 커피 200ml 8개...
  - 셀레니움 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말...
  - 셀레니움 크롤링 중: 쿠팡 로켓 배송 서울우유 커피, 20...
[50/1084] 검색어: 세븐일레븐 빙그레)사이즈업아메리카노350ml
  - 누적 API 호출 횟수: 50건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 빙그레 아카페라 사이즈업 디카페인 아...
  - 셀레니움 크롤링 중: 디카페인 아메리카노, 350ml......
  - 셀레니움 크롤링 중: 블랙 무라벨 370ml, 빙그레 아카...
  - 중간 저장 완료 (50번째 / 누적 150건)
[51/1084] 검색어: 세븐일레븐 빙그레)메로나맛우유240ml
  - 누적 API 호출 횟수: 51건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 빙그레 메로나맛우유 240ml 바코드...
  - 셀레니움 크롤링 중: 빙그레 단지우유240ml 3종 12개...
  - 셀레니움 크롤링 중: 빙그레 메로나맛 우유 칼로리, 당 아...
[52/1084] 검색어: 세븐일레븐 서울)초코우유200ml
  - 누적 API 호출 횟수: 52건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐편의점우유후기... 백제신라...
  - 셀레니움 크롤링 중: 세븐일레븐 키티 스트로베리 :: 초코...
  - 셀레니움 크롤링 중: [세븐일레븐우유3총사]... 만든 딸...
[53/1084] 검색어: 세븐일레븐 서울)딸기우유200ml
  - 누적 API 호출 횟수: 53건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐신상 말차 스트로베리] 말...
  - 셀레니움 크롤링 중: [세븐일레븐우유3총사] 각기다른원유로...
  - 셀레니움 크롤링 중: 세븐일레븐 키티 스트로베리 :: 초코...
[54/1084] 검색어: 세븐일레븐 빙그레)사이즈업라떼350ml
  - 누적 API 호출 횟수: 54건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 빙그레 비비빅라떼 vs 롯...
  - 셀레니움 크롤링 중: 비비빅 라떼 / 롯데푸드 마시는 빠삐...
  - 셀레니움 크롤링 중: 빙그레 아카페라 사이즈업 돌체(연유)...
[55/1084] 검색어: 세븐일레븐 PB)오구초코타임200ml
  - 누적 API 호출 횟수: 55건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [알뜰 정보] 세븐일레븐 세이브 세일...
  - 셀레니움 크롤링 중: [CU/GS25/세븐일레븐] 4월 2...
  - 셀레니움 크롤링 중: [CU/GS25/세븐일레븐] 3월 5...
[56/1084] 검색어: 세븐일레븐 매일)바리스타라떼PET475ml
  - 누적 API 호출 횟수: 56건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 수혈은 이걸로? 바리스타룰스 그란데 ...
  - 셀레니움 크롤링 중: 세븐일레븐 커피 바리스타룰스 그란데 ...
  - 셀레니움 크롤링 중: [내돈내산] 매일유업 바리스타룰스 그...
[57/1084] 검색어: 세븐일레븐 덴마크)딸기딸기우유300ml
  - 누적 API 호출 횟수: 57건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 동원 덴마크 라이트&저지방... 딸기...
  - 셀레니움 크롤링 중: 세븐일레븐 : 개콘 덴마크 픽미 딸기...
  - 셀레니움 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 30...
[58/1084] 검색어: 세븐일레븐 남양)초코에몽250ml
  - 누적 API 호출 횟수: 58건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: (세븐일레븐2+1)남양 초코에몽 25...
  - 셀레니움 크롤링 중: [11번가] 세븐일레븐 남양 초코에몽...
  - 셀레니움 크롤링 중: 7월 세븐일레븐 편의점 행사 세븐데이...
[59/1084] 검색어: 세븐일레븐 매일)바리스타아메리카노PET475m
  - 누적 API 호출 횟수: 59건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 몽베스트 생수 500ml 내추럴 미네...
  - 셀레니움 크롤링 중: 세븐일레븐 8월행사 추천 1+1 2+...
  - 셀레니움 크롤링 중: 세븐일레븐 7월행사 추천 7ELEVE...
[60/1084] 검색어: 세븐일레븐 빙그레)사이즈업바닐라라떼350ml
  - 누적 API 호출 횟수: 60건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 빙그레 아카페라 사이즈업 바닐라 라떼...
  - 셀레니움 크롤링 중: 빙그레 아카페라 바닐라 라떼 사이즈업...
  - 셀레니움 크롤링 중: 빙그레 아카페라 사이즈업 바닐라 라떼...
  - 중간 저장 완료 (60번째 / 누적 180건)
[61/1084] 검색어: 세븐일레븐 덴마크)초코초코우유300ml
  - 누적 API 호출 횟수: 61건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 덴마크 초코초코 우유 30...
  - 셀레니움 크롤링 중: 세븐일레븐편의점우유후기... 백제신라...
  - 셀레니움 크롤링 중: 세븐일레븐 초코우유...
[62/1084] 검색어: 세븐일레븐 빙그레)스페셜티예가체프460ml
  - 누적 API 호출 횟수: 62건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 빙그레 아카페라 스페셜티 에티오피아 ...
  - 셀레니움 크롤링 중: 아카페라 스페셜티 에티오피아 예가체프...
  - 셀레니움 크롤링 중: 예가체프] 스페셜티 등급... 가성비...
[63/1084] 검색어: 세븐일레븐 삼립)신선가득꿀호떡200g
  - 누적 API 호출 횟수: 63건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립)신선가득꿀호떡 1+1행사...
  - 셀레니움 크롤링 중: [삼립] 편의점 삼립호떡 미니 꿀호떡...
  - 셀레니움 크롤링 중: 서진이네2 삼립호떡 쌀커스터드 바닐라...
[64/1084] 검색어: 세븐일레븐 삼립)신선한치즈후레쉬팡140g
  - 누적 API 호출 횟수: 64건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 편의점 음식 리뷰 - GS25 삼립 ...
  - 셀레니움 크롤링 중: 플레인,세븐일레븐 쫀쫀 크림... 순...
  - 셀레니움 크롤링 중: 세븐일레븐 샌드위치 삼립)NEW프리미...
[65/1084] 검색어: 세븐일레븐 삼립)정통보름달88g
  - 누적 API 호출 횟수: 65건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [SPC 삼립 보름달 달토끼 방앗간 ...
  - 셀레니움 크롤링 중: 보름달 빵 연단팥 편의점 삼립 신상 ...
  - 셀레니움 크롤링 중: [삼립] 정통 보름달 딸기 시식기 :...
[66/1084] 검색어: 세븐일레븐 PB)쏘스윗카스테라160g
  - 누적 API 호출 횟수: 66건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 모닝콤보 AM 7~11시 ...
  - 셀레니움 크롤링 중: 세븐일레븐 디저트 폭신 달콤한 쏘스윗...
  - 셀레니움 크롤링 중: 세븐일레븐&롯데웰푸드 쏘스윗 카스테라...
[67/1084] 검색어: 세븐일레븐 삼립)로켓단초코롤85g
  - 누적 API 호출 횟수: 67건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 포켓몬 돌아온 로켓단 초코롤, ...
  - 셀레니움 크롤링 중: 삼립 돌아온 로켓단 초코롤 후기 라떼...
  - 셀레니움 크롤링 중: 돌아온 로켓단 초코롤 후기 (scp ...
[68/1084] 검색어: 세븐일레븐 삼립)주종발효단팥크림빵115g
  - 누적 API 호출 횟수: 68건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 주종 발효 단팥 크림빵 반...
  - 셀레니움 크롤링 중: [빵/간식] 안이 빵빵한 삼립 '주종...
  - 셀레니움 크롤링 중: 삼립빵 시리즈 빵추천 주종발효 단팥크...
[69/1084] 검색어: 세븐일레븐 롯데)미니땅콩크림샌드(5입)
  - 누적 API 호출 횟수: 69건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 롯데자이언츠 쌔리라 빠지락라면 메이플...
  - 셀레니움 크롤링 중: 롯데 미니샌드 땅콩크림 CU편의점 구...
  - 셀레니움 크롤링 중: 20241226_롯데_미니샌드 땅콩크...
[70/1084] 검색어: 세븐일레븐 삼립)크림빵75g
  - 누적 API 호출 횟수: 70건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 대왕크림빵 크림대빵 파는곳 가격...
  - 셀레니움 크롤링 중: 삼립 대왕크림빵 크리미대빵 맛보기...
  - 셀레니움 크롤링 중: GS 크림대빵 가격 편의점 삼립 크림...
  - 중간 저장 완료 (70번째 / 누적 210건)
[71/1084] 검색어: 세븐일레븐 엔제이)훈와리밀크카스테라
  - 누적 API 호출 횟수: 71건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 편의점 일본 간식 훈와리밀...
  - 셀레니움 크롤링 중: 프로틴, 오트몬드 프로틴, 훈와리 밀...
  - 셀레니움 크롤링 중: 세븐일레븐 훈와리 밀크 카스테라 칼로...
[72/1084] 검색어: 세븐일레븐 엔제이)소프트카스테라
  - 누적 API 호출 횟수: 72건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐 디저트]바나나우유 향 가...
  - 셀레니움 크롤링 중: 세븐일레븐 신상 엔제이 소프트카스테라...
  - 셀레니움 크롤링 중: 세븐일레븐 일본 엔제이 소프트카스테라...
[73/1084] 검색어: 세븐일레븐 제스트)도쿄브레드소금버터빵
  - 누적 API 호출 횟수: 73건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐신상 도쿄브레드 메이플빵&...
  - 셀레니움 크롤링 중: 세븐일레븐 도쿄브레드 소금버터빵, 소...
  - 셀레니움 크롤링 중: 세븐일레븐 신상 : 도쿄브레드 (초콜...
[74/1084] 검색어: 세븐일레븐 엔제이)훗카이도바나나카스테라
  - 누적 API 호출 횟수: 74건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 디저트]바나나우유 향 가득~ 엔제이 ...
  - 셀레니움 크롤링 중: 세븐일레븐 훗카이도 바나나 카스테라 ...
  - 셀레니움 크롤링 중: 세븐일레븐 일본 엔제이 카스테라 후기...
[75/1084] 검색어: 세븐일레븐 삼립)잘익은찰옥수수이야기110g
  - 누적 API 호출 횟수: 75건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 잘익은 찰 옥수수 이야기 110...
  - 셀레니움 크롤링 중: 매력있었던 삼립 잘익은 흑임자 이야기...
  - 셀레니움 크롤링 중: 삼립 잘 익은 옥수수 이야기 110g...
[76/1084] 검색어: 세븐일레븐 롯데)미니딸기샌드(5입)
  - 누적 API 호출 횟수: 76건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 신상 리뷰 – 연유초코딸기...
  - 셀레니움 크롤링 중: 세븐일레븐 신상 간식 키티 페스츄리 ...
  - 네이버 블로그 외 링크 제외: https://couplestyle.tistory.com/1354
[77/1084] 검색어: 세븐일레븐 삼립)순우유완듀완듀팡110g
  - 누적 API 호출 횟수: 77건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 순우유 완듀완듀팡 맛묵 하다...
  - 셀레니움 크롤링 중: 편의점 간식 삼립 빵 순우유 완듀완듀...
  - 셀레니움 크롤링 중: [CU/편의점/빵/베이커리/삼립]순우...
[78/1084] 검색어: 세븐일레븐 롯데)미니연유크림샌드(5입)
  - 누적 API 호출 횟수: 78건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 롯데 미니샌드 연유크림 빵... 당콩...
  - 셀레니움 크롤링 중: 세븐일레븐 신상 리뷰 – 연유초코딸기...
  - 셀레니움 크롤링 중: cu편의점 빵 추천, 롯데 미니샌드 ...
[79/1084] 검색어: 세븐일레븐 PB)제주첫물녹차카스테라160g
  - 누적 API 호출 횟수: 79건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 이색적인 녹차 카스테라!세븐일레븐 제...
  - 셀레니움 크롤링 중: [세븐일레븐/내돈내산] 세븐-셀렉트 ...
  - 셀레니움 크롤링 중: 세븐일레븐 제주 첫물 녹차 카스테라 ...
[80/1084] 검색어: 세븐일레븐 KBO)롯데자이언츠거인단팥빵100g
  - 누적 API 호출 횟수: 80건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 KBO 롯데자이언츠 마!거...
  - 셀레니움 크롤링 중: KBO 롯데자이언츠 거인단팥빵 세븐일...
  - 셀레니움 크롤링 중: 편의점 신상 레어 간식 KBO 크보빵...
  - 중간 저장 완료 (80번째 / 누적 240건)
[81/1084] 검색어: 세븐일레븐 롯데)미니땅콩샌드65g
  - 누적 API 호출 횟수: 81건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 롯데자이언츠 쌔리라 빠지락라면 메이플...
  - 셀레니움 크롤링 중: 신상 롯데자이언츠 마!쌔리라! 시리즈...
  - 셀레니움 크롤링 중: 20241226_롯데_미니샌드 땅콩크...
[82/1084] 검색어: 세븐일레븐 제스트)도쿄브레드메론빵
  - 누적 API 호출 횟수: 82건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 편의점 신상 제스트 도쿄브레드 메론빵...
  - 셀레니움 크롤링 중: 일본 세븐일레븐 간식 도쿄브레드 메론...
  - 셀레니움 크롤링 중: 세븐일레븐 편의점빵 신상 디저트 일본...
[83/1084] 검색어: 세븐일레븐 제스트)도쿄브레드메이플빵
  - 누적 API 호출 횟수: 83건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [세븐일레븐신상 도쿄브레드 메이플빵&...
  - 셀레니움 크롤링 중: 세븐일레븐 도쿄브레드  메이플 빵 후...
  - 셀레니움 크롤링 중: 일본 세븐일레븐 간식 도쿄브레드 메론...
[84/1084] 검색어: 세븐일레븐 삼립)순우유통통팥팥팡110g
  - 누적 API 호출 횟수: 84건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 순우유통통팥팥팡...
  - 셀레니움 크롤링 중: 편의점빵 삼립 순우유 통통팥팥팡...
  - 셀레니움 크롤링 중: 편의점 신상 삼립 순우유 통통팥팥팡 ...
[85/1084] 검색어: 세븐일레븐 제스트)도쿄브레드훗카이도크림빵
  - 누적 API 호출 횟수: 85건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 신상 도쿄브레드 훗카이도 ...
  - 셀레니움 크롤링 중: 세븐일레븐 도쿄브레드 훗카이도 크림빵...
  - 셀레니움 크롤링 중: 세븐일레븐 도쿄브레드 홋카이도 크림빵...
[86/1084] 검색어: 세븐일레븐 삼립)파이리의핫소스팡90g
  - 누적 API 호출 횟수: 86건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 삼립 포켓몬 빵 파이리의 ...
  - 셀레니움 크롤링 중: 세븐일레븐 판매) 포켓몬스터빵 :: ...
  - 셀레니움 크롤링 중: ( 내돈내산 ) 삼립 파이리의 화르륵...
[87/1084] 검색어: 세븐일레븐 삼립)주종발효카스타드소보루
  - 누적 API 호출 횟수: 87건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 주종발효 카스타드 소보루빵 알리...
  - 셀레니움 크롤링 중: 삼립 408시간 주종발효 카스타드 소...
  - 셀레니움 크롤링 중: 삼립 주종발효 카스타드 소보루 솔직 ...
[88/1084] 검색어: 세븐일레븐 삼립)발효버터빅스위트데니쉬
  - 누적 API 호출 횟수: 88건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 허니카스테라,발효버터빅패스츄리,빅스위...
  - 셀레니움 크롤링 중: 삼립 발효버터 빅스위트 데니쉬 내돈내...
  - 셀레니움 크롤링 중: 삼립 편의점 빵 발효버터 빅스위트데니...
[89/1084] 검색어: 세븐일레븐 삼립)순우유밀크요팡65g
  - 누적 API 호출 횟수: 89건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 순우유 밀크요팡 65g 맛 리뷰...
  - 셀레니움 크롤링 중: 삼립 순우유 밀크요팡 1A등급 우유로...
  - 셀레니움 크롤링 중: 삼립 순우유 밀크요팡 영양정보 내 최...
[90/1084] 검색어: 세븐일레븐 삼립)시그니처카스테라125g
  - 누적 API 호출 횟수: 90건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 시그니처 빵 상큼 레몬 파운드와...
  - 셀레니움 크롤링 중: 삼립 시그니처 카스테라｜부드러운 가성...
  - 셀레니움 크롤링 중: 삼립 시그니처 카스테라 / 시그니처 ...
  - 중간 저장 완료 (90번째 / 누적 270건)
[91/1084] 검색어: 세븐일레븐 삼립)주종발효카스타드단팥빵
  - 누적 API 호출 횟수: 91건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: [편의점/세븐일레븐/빵/삼립] 주종발...
  - 셀레니움 크롤링 중: [세븐일레븐 빵후기] 삼립 주종발효카...
  - 셀레니움 크롤링 중: 삼립 주종발효 카스타드 단팥빵 솔직 ...
[92/1084] 검색어: 세븐일레븐 삼립)주종발효슈크림빵90g
  - 누적 API 호출 횟수: 92건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 SPC 전통 쌀 막걸리 발효 주...
  - 셀레니움 크롤링 중: 편의점 슈크림빵 칼로리 삼립 408시...
  - 셀레니움 크롤링 중: [상품리뷰] 삼립 주종발효 슈크림빵 ...
[93/1084] 검색어: 세븐일레븐 삼립)피카피카치즈케익80g
  - 누적 API 호출 횟수: 93건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: ( 내돈내산 ) 삼립 피카피카 촉촉 ...
  - 셀레니움 크롤링 중: 삼립 포켓몬빵 피카피카 촉촉치즈케익...
  - 셀레니움 크롤링 중: SPC삼립, 포켓몬빵 피카피카 촉촉 ...
[94/1084] 검색어: 세븐일레븐 KBO)기아타이거즈호랑이초코롤85g
  - 누적 API 호출 횟수: 94건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: KBO빵)) 삼립 크보빵 띠부씰 //...
  - 셀레니움 크롤링 중: 삼립 x KBO 기아 타이거즈 호랑이...
  - 셀레니움 크롤링 중: 삼립 KBO 기아 타이거즈 호랑이초코...
[95/1084] 검색어: 세븐일레븐 삼립)잘익은쑥이야기110g
  - 누적 API 호출 횟수: 95건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 먹어봤다/ 삼립 잘 익은 쑥 이야기(...
  - 셀레니움 크롤링 중: 삼립 잘 익은 쑥 이야기 빵 후기 매...
  - 셀레니움 크롤링 중: GS 편의점 빵 삼립 잘 익은 쑥 이...
[96/1084] 검색어: 세븐일레븐 KBO)LG트윈스쌍둥이딸기샌드99g
  - 누적 API 호출 횟수: 96건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 편의점 신상 빵 삼립 LG...
  - 셀레니움 크롤링 중: KBO 크보빵 LG 트윈스 쌍둥이 딸...
  - 셀레니움 크롤링 중: 삼립 크보빵 KBO빵 LG트윈스 쌍둥...
[97/1084] 검색어: 세븐일레븐 롯데)프리미엄패스츄리스위트
  - 누적 API 호출 횟수: 97건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 롯데 프리미엄 패스츄리 스위트...
  - 셀레니움 크롤링 중: 신상 롯데 고참 꿀맛이구마 프리미엄 ...
  - 셀레니움 크롤링 중: 빵 롯데 패스츄리 정년이 프리미엄 패...
[98/1084] 검색어: 세븐일레븐 삼립)초당옥수수크림빵100g
  - 누적 API 호출 횟수: 98건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 초당 옥수수 크림빵 두툼하고 투...
  - 셀레니움 크롤링 중: 광장시장 아베베 베이커리  웨이팅 후...
  - 셀레니움 크롤링 중: 옥수수크림빵 삼립 세븐일레븐...
[99/1084] 검색어: 세븐일레븐 KBO)롯데자이언츠씨앗호떡빵97g
  - 누적 API 호출 횟수: 99건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 세븐일레븐 KBO 롯데자이언츠빵 마!...
  - 셀레니움 크롤링 중: 세븐일레븐 랜덤씰이 있는 롯데자이언츠...
  - 셀레니움 크롤링 중: *세븐일레븐 KBO 롯데자이언츠 빵*...
[100/1084] 검색어: 세븐일레븐 삼립)고오스초코케익80g
  - 누적 API 호출 횟수: 100건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 돌아온 고오스 초코 케익, 80...
  - 셀레니움 크롤링 중: [삼립] 돌아온 고오스 초코케익 리뷰...
  - 셀레니움 크롤링 중: SPC삼립 벗겨먹는 초코 빵, 돌아온...
  - 중간 저장 완료 (100번째 / 누적 300건)
[101/1084] 검색어: 세븐일레븐 삼립)순우유연유요팡80g
  - 누적 API 호출 횟수: 101건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 순우유 연유요팡 무난하게 맛있는 편의...
  - 셀레니움 크롤링 중: 순우유 연유요팡 추억의 학교 매점 삼...
  - 셀레니움 크롤링 중: 빵도감 207 : [삼립] 순우유 연...
[102/1084] 검색어: 세븐일레븐 삼립)미각우유연유카스테라롤128g
  - 누적 API 호출 횟수: 102건 / 일일 한도 25,000건
  - 셀레니움 크롤링 중: 삼립 편의점 신상 미각제빵소 연유커피...
  - 셀레니움 크롤링 중: CU · GS25 · 세븐일레븐......

In [2]:
import os
import time
import random
import pandas as pd
import polars as pl
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# 1. 환경 변수 및 설정
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")
INPUT_DATA_PATH = "/Users/hajiyoon/workspace/data/processed/최종_상품단위_데이터셋.csv"
OUTPUT_PATH = "seven_eleven_remaining_80_reviews.csv"

def get_remaining_products():
    """
    중분류별 매출 누적 비율 80% 이상(매출 기여도가 낮은 나머지 상품군)인 상품들 추출
    """
    print("데이터 로딩 및 하위 매출 상품군(나머지 80% 상품수 기준) 추출 중...")
    
    # 데이터가 큰 경우를 대비해 polars 사용
    lf = pl.scan_csv(INPUT_DATA_PATH)
    
    df = lf.select([
        pl.col("상품중분류명").alias("중분류명"),
        pl.col("상품명"),
        pl.col("총_매출금액").alias("총매출금액")
    ]).collect()

    # 중분류별 총 매출액 계산
    df = df.with_columns([
        pl.col("총매출금액").sum().over("중분류명").alias("중분류총매출금액")
    ])
    
    # 매출 내림차순 정렬 후 누적 비율 계산
    df = df.sort(["중분류명", "총매출금액"], descending=[False, True])
    df = df.with_columns([
        (pl.col("총매출금액").cum_sum().over("중분류명") / pl.col("중분류총매출금액")).alias("누적비율")
    ])

    # 기존 작업(상위 80% 매출 견인 상품)의 반대 조건
    # 누적 비율 0.8 이상인 상품들이 나머지 매출 20%를 구성하는 다수의 상품들임
    df_remaining = df.filter(pl.col("누적비율") >= 0.8)
    
    # 고유 상품명 리스트 반환
    return df_remaining.select("상품명").unique().to_series().to_list()

def setup_driver():
    """
    Selenium Chrome 드라이버 설정
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
    
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)
    return driver

def get_blog_content(driver, url):
    """
    Selenium을 사용하여 블로그 본문 추출
    """
    try:
        driver.get(url)
        wait = WebDriverWait(driver, 5)
        wait.until(EC.presence_of_element_located((By.ID, "mainFrame")))
        driver.switch_to.frame("mainFrame")
        
        selectors = [
            "div.se-main-container",
            "div#postViewArea",
            "div[id^='post-view']",
            "div.se-viewer"
        ]
        
        for selector in selectors:
            try:
                element = driver.find_element(By.CSS_SELECTOR, selector)
                text = element.text.strip()
                if text:
                    return text
            except:
                continue
        return "본문 추출 실패"
    except Exception as e:
        return f"크롤링 오류: {e}"
    finally:
        try:
            driver.switch_to.default_content()
        except:
            pass

def main():
    if not CLIENT_ID or not CLIENT_SECRET:
        print("오류: .env 파일에 NAVER_CLIENT_ID 및 NAVER_CLIENT_SECRET 설정이 필요합니다.")
        return

    # 1. 대상 상품 추출
    items = get_remaining_products()
    print(f"추출된 대상 상품 수: {len(items)}개")
    
    results = []
    driver = setup_driver()
    
    try:
        for i, item in enumerate(items, 1):
            search_query = f"세븐일레븐 {item}"
            print(f"[{i}/{len(items)}] 검색 중: {search_query}")
            
            # 2. 네이버 블로그 검색 API (상위 3개)
            api_url = f"https://openapi.naver.com/v1/search/blog.json?query={quote(search_query)}&display=3&sort=sim"
            api_headers = {
                "X-Naver-Client-Id": CLIENT_ID,
                "X-Naver-Client-Secret": CLIENT_SECRET
            }
            
            try:
                res = requests.get(api_url, headers=api_headers)
                if res.status_code == 200:
                    blog_items = res.json().get('items', [])
                    for blog in blog_items:
                        title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                        link = blog['link']
                        
                        print(f"  - 본문 수집 중: {title[:20]}...")
                        content = get_blog_content(driver, link)
                        
                        results.append({
                            '검색어': search_query,
                            '상품명': item,
                            '블로그제목': title,
                            '블로그링크': link,
                            '본문내용': content
                        })
                        time.sleep(random.uniform(1, 2))
                else:
                    print(f"  - API 호출 실패 (상태코드: {res.status_code})")
            except Exception as e:
                print(f"  - 검색 처리 중 오류: {e}")
            
            # 3. 주기적 저장 (10개 상품마다)
            if i % 10 == 0 and results:
                pd.DataFrame(results).to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
                print(f"--- 현재까지 {len(results)}건 저장 완료 ---")
                
    finally:
        driver.quit()
        if results:
            pd.DataFrame(results).to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
            print(f"\n최종 완료! 총 {len(results)}건의 데이터가 {OUTPUT_PATH}에 저장되었습니다.")
        else:
            print("\n수집된 데이터가 없습니다.")

if __name__ == "__main__":
    main()

데이터 로딩 및 하위 매출 상품군(나머지 80% 상품수 기준) 추출 중...
추출된 대상 상품 수: 8196개
[1/8196] 검색 중: 세븐일레븐 7P)스트롱사와자몽500ml
  - 본문 수집 중: 세븐일레븐 스트롱사와 자몽, 라임 후...
  - 본문 수집 중: 세븐일레븐 스트롱사와 자몽 레몬 시콰...
  - 본문 수집 중: [세븐일레븐신상] 일본 하이볼 스트롱...
[2/8196] 검색 중: 세븐일레븐 삼립)라이츄슈크림데니쉬100g
  - 본문 수집 중: 포켓몬빵 신상 삼립 라이츄의 슈크림데...
  - 본문 수집 중: 삼립. 라이츄 슈크림 데니쉬 후기 -...
  - 본문 수집 중: [일상] 삼립 포켓몬빵 라이츄의 슈크...
[3/8196] 검색 중: 세븐일레븐 APP전용)안유성명장샌드
  - 본문 수집 중: [금주의 신상] 스타벅스 X 해리포터...
[4/8196] 검색 중: 세븐일레븐 던_오리온)참붕어빵8P
  - 본문 수집 중: 경제 일반..네이버(언론사제공) 20...
[5/8196] 검색 중: 세븐일레븐 일신)클래식쌀쿠키300g
  - 본문 수집 중: 9월 편의점 신상 모음 CU GS25...
  - 본문 수집 중: 일신)클래식 쌀쿠키 & 위스트) 크크...
  - 본문 수집 중: [세븐일레븐 신상과자] 클래식 쌀과자...
[6/8196] 검색 중: 세븐일레븐 롯데)와 바닐라190ml
  - 본문 수집 중: 세븐일레븐 7월행사 추천 7ELEVE...
  - 본문 수집 중: 7ELEVEN 세븐일레븐 6월행사 이...
  - 본문 수집 중: 세븐일레븐 8월행사 추천 1+1 2+...
[7/8196] 검색 중: 세븐일레븐 농심)카구리큰사발
  - 본문 수집 중: [농심] 카구리 큰사발...
  - 본문 수집 중: [CU신상 농심 푸팟퐁구리 큰사발] ...
  - 본문 수집 중: [농심] 카구리 큰사발 컵라면...
[8/8196] 검색 중: 세븐일레븐 PB)복숭아아이스티1.5L
  - 본문 수집 중: 가평계곡, 유명산 옛집 오리로스, 세...
  - 본문 수집 중: 산리오 지비츠! 세븐일레븐 PB '복...
  - 본문 수집 중: 세븐일레븐 산리오 지비츠 복숭아 아이...
[9/8196] 검색 중: 세븐일레븐 현대)미에로화이바20입
[10/8196] 검색 중: 세븐일레븐 그린)새우튀김김밥
  - 본문 수집 중: 세븐일레븐 통새우튀김 김밥...
  - 본문 수집 중: 통새우 튀김 김밥[세븐일레븐]...
  - 본문 수집 중: 세븐일레븐<불닭마요소스에 찍어먹는 통...
--- 현재까지 23건 저장 완료 ---
[11/8196] 검색 중: 세븐일레븐 훼밀리)젤리팝시클20g
  - 본문 수집 중: 4월 편의점 과자 1+1 행사 총정리...
[12/8196] 검색 중: 세븐일레븐 G)스틱휘낭시에레몬티39g
  - 본문 수집 중: 세븐일레븐 스틱휘낭시에치즈 39g 솔...
  - 본문 수집 중: 스틱 휘낭시에 치즈 초콜릿 레몬티 후...
  - 본문 수집 중: 일본 편의점 추천 세븐일레븐 간식 음...
[13/8196] 검색 중: 세븐일레븐 삼양)맹구짱구85g
  - 본문 수집 중: [문정] CU - 삼양 맹구짱구 85...
  - 본문 수집 중: CU편의점 과자 삼양 맹구짱구 소금빵...
  - 본문 수집 중: #광고 11번가-삼양 맹구짱구(소금빵...
[14/8196] 검색 중: 세븐일레븐 APP)연태아사간열500ml(2입)
  - 본문 수집 중: [키햐 연태 아사간열500ml] 중국...
  - 본문 수집 중: 연태 아사간열 연태 고량주 키햐에서 ...
  - 본문 수집 중: 연태 아사간열 후기 | 키햐 앱으로 ...
[15/8196] 검색 중: 세븐일레븐 하림)더미식돼지고기김치찌개700g
  - 본문 수집 중: 맛있다 편의점 도시락 세븐일레븐 돼지...
  - 본문 수집 중: [편의점 도시락 리뷰] 세븐일레븐 2...
  - 본문 수집 중: 세븐일레븐 도시락-돼지고기 김치찌개...
[16/8196] 검색 중: 세븐일레븐 티니핑)빛나핑의도라야끼통팥70g
  - 본문 수집 중: [캐치티니핑빵]빛나핑의 도라야끼통팥...
  - 본문 수집 중: [세븐일레븐 신상] 빛나핑의 도라야끼...
  - 본문 수집 중: 티니핑빵 빛나핑의 도라야끼통팥...
[17/8196] 검색 중: 세븐일레븐 25설)제주향기 담은 천혜향 3.0kg
  - 본문 수집 중: 거래처 명절선물 레드향 한라봉 천혜향...
  - 본문 수집 중: 파리바게트 발렌타인데이 케이크 종류 ...
  - 본문 수집 중: |브랜딩 대외활동| 세븐일레븐과 함께...
[18/8196] 검색 중: 세븐일레븐 APP예약)울진대게장유부초밥
  - 본문 수집 중: 【세븐일레븐】 모둠초밥정식 & 울진대...
  - 본문 수집 중: 세븐일레븐 대게딱지장유부초밥...
  - 본문 수집 중: 울진 대게축제 일정 죽변항 맛집 대게...
[19/8196] 검색 중: 세븐일레븐 롯데)옐로우테일오로라팩(쉬라)
  - 본문 수집 중: 레드와인  (feat. 세븐일레븐 옐...
  - 본문 수집 중: 옐로우테일 쉬라즈 Yellow... ...
  - 본문 수집 중: 세븐일레븐 와인 옐로우테일 재미 레드...
[20/8196] 검색 중: 세븐일레븐 삼양)삼양라면1963봉지
  - 본문 수집 중: 삼양1963 우지라면 후기 프리미엄 ...
  - 본문 수집 중: 봉지라면 추천 삼양1963 우지라면...
  - 본문 수집 중: 깊은 국물 맛 프리미엄 라면 즐기고 ...
--- 현재까지 51건 저장 완료 ---
[21/8196] 검색 중: 세븐일레븐 뉴웨이브)다정그래놀라풀믹스초코
  - 본문 수집 중: 대전 디저트 핫플 몽심 팝업｜세븐일레...
  - 본문 수집 중: 세븐일레븐 생초코파이 솔직후기 가격 ...
  - 본문 수집 중: 편의점 신상 세븐일레븐 두바이초코하이...
[22/8196] 검색 중: 세븐일레븐 미성)해씨초콜릿 30g
  - 본문 수집 중: 중국산 해바라기씨 초콜릿 해씨초콜릿 ...
  - 본문 수집 중: 미성 해씨초콜릿 스톤초콜릿 GS더프레...
  - 본문 수집 중: 4월 편의점 과자 1+1 행사 총정리...
[23/8196] 검색 중: 세븐일레븐 롯데)루이마티니소노마까버네750
  - 본문 수집 중: [2월의와인] 루이스 엠 마티니 소노...
  - 본문 수집 중: 루이즈 엠 마티니 소노마카운티 까버네...
  - 본문 수집 중: 세븐일레븐 711 4월의 와인 정보 ...
[24/8196] 검색 중: 세븐일레븐 델리팜)앤디스초콜릿토피132g
[25/8196] 검색 중: 세븐일레븐 그린)초코딸기샌드
  - 본문 수집 중: 세븐일레븐 신상 리뷰 – 연유초코딸기...
  - 본문 수집 중: 세븐일레븐 신상 냉장디저트 초코딸기샌...
  - 본문 수집 중: 달콤한 편의점 샌드위치 추천, 세븐일...
[26/8196] 검색 중: 세븐일레븐 오뚜기)오뚜기큰밥300g*4입
  - 본문 수집 중: [세븐일레븐/오뚜기] 이비가 짬뽕라면...
  - 본문 수집 중: [세븐일레븐신상 오뚜기 WOW 새우진...
  - 본문 수집 중: 오뚜기 맛있는 오뚜기밥 큰밥 300g...
[27/8196] 검색 중: 세븐일레븐 랏소베어)마우스패드set(단품)
  - 본문 수집 중: 세븐일레븐 발렌타인데이 기획 블루밍테...
  - 본문 수집 중: 세븐일레븐 2월행사 발렌타인데이 랏소...
  - 본문 수집 중: 세븐일레븐 디즈니 토이스토리 랏소 마...
[28/8196] 검색 중: 세븐일레븐 동원)고등어캔300g
  - 본문 수집 중: 세븐일레븐 / 동원고추참치라면...
  - 본문 수집 중: 400g, 300g 캔 종류별 최저가...
  - 본문 수집 중: 동원 고등어 통조림, 300g, 3개...
[29/8196] 검색 중: 세븐일레븐 유앤)공룡무빙피규어캔디10g
  - 본문 수집 중: 스핀캔디 ! 최초 ! 구독자 이벤트 ...
  - 본문 수집 중: 많이 구매한 상품 best 순위 (8...
[30/8196] 검색 중: 세븐일레븐 하림)매움주의장인라면봉지2입
  - 본문 수집 중: 5800원 명품라면 하림 매움주의 장...
  - 본문 수집 중: 맛있게 겁나 매운 신상라면 하림 장인...
  - 본문 수집 중: 노브랜드 라면왕그릇, 하림 더미식 매...
--- 현재까지 77건 저장 완료 ---
[31/8196] 검색 중: 세븐일레븐 프레시팜)제주노지감귤800g
  - 본문 수집 중: 제주 감귤 체험 : 제주도 예래팜 2...
  - 본문 수집 중: 귤 10kg 새콤달콤한 조생감귤 (+...
  - 본문 수집 중: 마흔두번째 마켓컬리 이용기_ 제주 무...
[32/8196] 검색 중: 세븐일레븐 롯데)와일드바디타이거70ml
  - 본문 수집 중: 와일드바디 타이거 내돈내산 후기! 세...
  - 본문 수집 중: [세븐일레븐/롯데] 와일드바디 케이크...
  - 본문 수집 중: 롯데제과 와일드바디 타이거 70ml...
[33/8196] 검색 중: 세븐일레븐 훈스)옥수수콘마요빵110g
  - 본문 수집 중: 세븐일레븐 편의점 신상 옥수수콘마요빵...
  - 본문 수집 중: 2026년 2월1주차 편의점신상 (G...
  - 본문 수집 중: 세븐일레븐 신상 롯데자이언츠 마!쌔리...
[34/8196] 검색 중: 세븐일레븐 코카)태양의원차보리500ml
  - 본문 수집 중: [코카콜라] 구수함이 가득 "태양의 ...
  - 본문 수집 중: 코카콜라 태양의 원차 주전자차 보리차...
  - 본문 수집 중: 태양의원차 주전자차 보리 ㅣ정유미 보...
[35/8196] 검색 중: 세븐일레븐 3블루밍)스티커기획set
  - 본문 수집 중: 세븐일레븐 발렌타인데이 기획 블루밍테...
  - 본문 수집 중: 콜라보 기획팩 3종(마우스패드, 스티...
  - 본문 수집 중: 세븐일레븐 키티 텀블러 키캡 이나피스...
[36/8196] 검색 중: 세븐일레븐 제주)제주위트에일500ml캔
  - 본문 수집 중: [주류 128][캔-500ml] 제주...
  - 본문 수집 중: 세븐일레븐 1월 행사 편의점 맥주 와...
  - 본문 수집 중: 제주 위트 에일 맥주 한입잔 증정품...
[37/8196] 검색 중: 세븐일레븐 매크로)키도크리미버터샌드90g
  - 본문 수집 중: 키드오 크래커 딸기 키드오 딸기맛 편...
  - 본문 수집 중: 나 샌드 추천 BEST 3! 입안 가...
  - 본문 수집 중: GS25 9월 5주차 신상 앨범 공개...
[38/8196] 검색 중: 세븐일레븐 5쿠로미)스마트폰거치대set
  - 본문 수집 중: 세븐일레븐 빵빵이 콜라보 제품 후기 ...
  - 본문 수집 중: 세븐일레븐 빵빵이 옥지... 케이스 ...
  - 본문 수집 중: 발렌타인데이 빵빵이의 일상 X 세븐일...
[39/8196] 검색 중: 세븐일레븐 APP전용)럭히밥불고기킹토스트
  - 본문 수집 중: 세븐일레븐 럭히밥불고기킹 토스트 솔직...
  - 본문 수집 중: 세븐일레븐 럭히밥 불고기킹 토스트 후...
  - 본문 수집 중: 히밥과 콜라보, 세븐일레븐 럭히밥 불...
[40/8196] 검색 중: 세븐일레븐 SAMG)로열티니핑컬러팝콘45g
  - 본문 수집 중: cu편의점 로열티니핑 컬러팝콘 45g...
  - 본문 수집 중: 티니핑 팝콘 : 로열티니핑 컬러팝콘 ...
  - 본문 수집 중: [모든 편의점] 로열티니핑 컬러팝콘,...
--- 현재까지 107건 저장 완료 ---
[41/8196] 검색 중: 세븐일레븐 CJ)정희원교수의렌틸콩현미밥190g*4입
  - 본문 수집 중: 저속노화 정희원교수와 CJ 햇반의 콜...
  - 본문 수집 중: 저속노화 정희원 교수 햇반 렌틸콩 현...
  - 본문 수집 중: 다이어트식단 CJ 햇반 라이스플랜 렌...
[42/8196] 검색 중: 세븐일레븐 25설)오레팜새턴버드1~6MIX(24개입)
  - 본문 수집 중: (주)오레팜 새턴버드 스페셜티 콜드브...
  - 본문 수집 중: 매일경제뉴스 요약,[2026.01.3...
  - 본문 수집 중: 정책지식 2026.4.2....
[43/8196] 검색 중: 세븐일레븐 25추_성경)종합F호
  - 본문 수집 중: 科學의 (자연의 이해‘Knowledg...
  - 본문 수집 중: 食이 地名‘자리가 달라서 관계가다르다...
  - 본문 수집 중: 食이 地名‘자리가 달라서 관계가다르다...
[44/8196] 검색 중: 세븐일레븐 PB)질러핫크레이지나쵸70g
  - 본문 수집 중: 세븐일레븐 신상 질러 크레이지핫나쵸 ...
  - 본문 수집 중: 질러 크레이지 핫나쵸 세븐일레븐 8월...
  - 본문 수집 중: 세븐일레븐 질러 크레이지핫 나쵸 과연...
[45/8196] 검색 중: 세븐일레븐 CSR)샴페인쟈끄송디지테레루즈
[46/8196] 검색 중: 세븐일레븐 MZ)밀카네잎클로버패키지
  - 본문 수집 중: 미리미리 준비하는 화이트데이 선물 추...
  - 본문 수집 중: 단디과자점 대명동두쫀쿠 휘낭시에 후기...
  - 본문 수집 중: 25년 8월 여름휴가(2) - 이나다...
[47/8196] 검색 중: 세븐일레븐 대호)벤티아메리카노스위트500ml
  - 본문 수집 중: 세븐일레븐 6월 한달 아이스커피 최대...
  - 본문 수집 중: 전국 커피전문점 자료 (2020년12...
  - 본문 수집 중: [세븐일레븐] 편의점 10월 세븐카페...
[48/8196] 검색 중: 세븐일레븐 특판)펩시콜라210ml
  - 본문 수집 중: 잠실 펩시 팝업스토어 오픈! 세븐일레...
  - 본문 수집 중: 잠실 놀거리 팝업스토어 전시 3월 펩...
  - 본문 수집 중: [잠실 세븐일레븐 X 펩시 컨셉스토어...
[49/8196] 검색 중: 세븐일레븐 직납)블루하와이바
  - 본문 수집 중: [하와이/정보] 하와이 푸드... 하...
  - 본문 수집 중: [24.03.20] 하와이 17일차....
  - 본문 수집 중: 부천 콜키지프리 되는 조개구이 맛집 ...
[50/8196] 검색 중: 세븐일레븐 바프)체다치즈맛아몬드40g
  - 본문 수집 중: 신상 바프 체다치즈맛 아몬드앤프레첼...
  - 본문 수집 중: 품절 임박 HBAF 바프 아몬드 40...
  - 본문 수집 중: 편의점 맥주안주 추천 바프 체다치즈맛...
--- 현재까지 134건 저장 완료 ---
[51/8196] 검색 중: 세븐일레븐 오리온)스윙칩나폴리피자맛50g
  - 본문 수집 중: 오리온 스윙칩 나폴리피자 맛 리뷰! ...
  - 본문 수집 중: 오리온 스윙칩 나폴리 피자맛 50g ...
  - 본문 수집 중: 신상 봉지과자 오리온의 스윙칩 나폴리...
[52/8196] 검색 중: 세븐일레븐 롯데)구구콘솔티카라멜160ml
  - 본문 수집 중: [롯데/구구콘-솔티카라멜],[해태/쌍...
  - 본문 수집 중: [구구콘 솔티카라멜] 단짠단짠 아이스...
  - 본문 수집 중: 구구콘 솔티카라멜 내돈내산 후기! 아...
[53/8196] 검색 중: 세븐일레븐 삼립)저당단팥호빵(1입)
  - 본문 수집 중: 세븐일레븐 신상 삼립 간식 저당 단팥...
  - 본문 수집 중: 편의점 신상 삼립호빵 저당단팥호빵 맛...
  - 본문 수집 중: 삼립호빵 신상 감주통팥, 흑당단팥 1...
[54/8196] 검색 중: 세븐일레븐 한양)꽃보다오징어매코미150g
  - 본문 수집 중: CU편의점 맥주 안주, 한양식품 꽃보...
  - 본문 수집 중: 민생회복 지원금 소비쿠폰 사용처 GS...
  - 본문 수집 중: 맥주안주 꽃보다오징어 (feat.세븐...
[55/8196] 검색 중: 세븐일레븐 APP예약)그릴리직화후랑크&제육도시락
  - 본문 수집 중: 도시락 리뷰] 총동원 그릴리직화후랑크...
  - 본문 수집 중: 세븐일레븐 총동원 그릴리직화후랑크 &...
  - 본문 수집 중: 편의점 도시락 예약 총동원 그릴리 직...
[56/8196] 검색 중: 세븐일레븐 빙그레)토핑요플레(쿠앤크)120g
  - 본문 수집 중: 빙그레 신상품 토핑 요플레 쿠앤크 후...
  - 본문 수집 중: 빙그레 요플레 토핑 쿠앤크 당신이 쿠...
  - 본문 수집 중: 빙그레 요플레 토핑 쿠앤크 (신상 요...
[57/8196] 검색 중: 세븐일레븐 정관장)활력28리부스트100ml
  - 본문 수집 중: 단종) [정관장] 활력28 리부스트 ...
  - 본문 수집 중: 정관장 활력28 리부스트 먹고 활기 ...
  - 본문 수집 중: 정관장 활력28리부스트...
[58/8196] 검색 중: 세븐일레븐 에이트)뽀로로짜장떡볶이
  - 본문 수집 중: 일본일상 뽀로로 짜장 떡볶이 세븐일레...
  - 본문 수집 중: 뽀로로 짜장떡볶이 세븐일레븐 아이가 ...
  - 본문 수집 중: 뽀로로 떡볶이 3종 - 짜장, 크림,...
[59/8196] 검색 중: 세븐일레븐 대상)저당비빔면소스270g(튜브)
  - 본문 수집 중: 입맛 살리는 저당비빔장 청정원 순창 ...
  - 본문 수집 중: [금주의 신상] 팔도비빔면 더 블루 ...
  - 본문 수집 중: 청정원 순창 저당 초고추장으로 만드는...
[60/8196] 검색 중: 세븐일레븐 투데이)스위즐스드럼스틱오리지널라즈베리&밀크100g
  - 본문 수집 중: [세븐일레븐 스위즐스 드럼스틱] 영국...
  - 본문 수집 중: 스위즐스 스쿼시 드럼스틱 3종 후기 ...
  - 본문 수집 중: 영국 스위즐스 드럼스틱 젤리 4종 스...
--- 현재까지 164건 저장 완료 ---
[61/8196] 검색 중: 세븐일레븐 G)파스키에팡올레280g
  - 본문 수집 중: 내돈내산 최화정 빵으로 유명한 프랑스...
  - 본문 수집 중: 트레이더스 4월 셋째주 할인상품 멤버...
  - 본문 수집 중: TV 홈쇼핑 방송 편성표_202505...
[62/8196] 검색 중: 세븐일레븐 오뚜기)뉴슈가60g
  - 본문 수집 중: 한지붕, 오뚜기 뉴슈가 가격 비교| ...
[63/8196] 검색 중: 세븐일레븐 롯데)허쉬해리포터바밀크43g
  - 본문 수집 중: 허쉬 해리포터 밀크초콜릿...
  - 본문 수집 중: 해리포터x허쉬 콜라보 초콜릿 구매:)...
  - 본문 수집 중: 해리포터 X 허쉬 초콜릿 콜라보 내돈...
[64/8196] 검색 중: 세븐일레븐 새롬)샤인머스캣(200g)
  - 본문 수집 중: [세븐일레븐]2ELEVEN 2025/...
  - 본문 수집 중: 내 친구 시집가는 날...
  - 본문 수집 중: 25년 7월 후쿠오카 1박2일중 1일...
[65/8196] 검색 중: 세븐일레븐 삼립)불고기맛후랑크70g
  - 본문 수집 중: [SPC삼립] 불고기맛 후랑크 70g...
  - 본문 수집 중: [에스피씨삼립] 불고기맛 후랑크 : ...
  - 본문 수집 중: 이마트편의점에서 구매한 삼립 불고기맛...
[66/8196] 검색 중: 세븐일레븐 MQ)프링글스오리지널70g
  - 본문 수집 중: 편의점 10월 행사/세븐일레븐: 맥주...
  - 본문 수집 중: 세븐일레븐 편의점 1월 행사 도시락,...
  - 본문 수집 중: 세븐일레븐 711데이 7월 9일부터 ...
[67/8196] 검색 중: 세븐일레븐 34-02동원)단호
  - 본문 수집 중: 김장용 쓰레기봉투 여기서 구입하세요!...
  - 본문 수집 중: 간추린 과학기술 250706일16오후...
  - 본문 수집 중: 간추린 생활경제 250624화17 뉴...
[68/8196] 검색 중: 세븐일레븐 지비)로스트포엣750ml
  - 본문 수집 중: 2020(로스트 포엣 레드 2020)...
  - 본문 수집 중: 711 세븐일레븐 편의점 2024년 ...
  - 본문 수집 중: 24년 4월 세븐일레븐(711)와인 ...
[69/8196] 검색 중: 세븐일레븐 오비)오비라거500ml캔
  - 본문 수집 중: 올림픽 거실 1열 관람중 (오비,배민...
  - 본문 수집 중: OB맥주, 오비라거...
  - 본문 수집 중: [리뷰] 커스텀포라온 커스텀맥주잔ㅣ오...
[70/8196] 검색 중: 세븐일레븐 스퀴즈)세츠애플사이다500ml캔
  - 본문 수집 중: 스퀴즈맥주 애플사이더 더 세츠 사과주...
  - 본문 수집 중: 맥주 대신 마실 것 (GS25·CU·...
  - 본문 수집 중: 사과주 더 세츠 애플사이더 과실주 하...
--- 현재까지 192건 저장 완료 ---
[71/8196] 검색 중: 세븐일레븐 칠성)핫식스더킹메가제로500ml
  - 본문 수집 중: 롯데칠성, 제로 칼로리 에너지음료 '...
  - 본문 수집 중: 롯데칠성음료 신상 [핫식스 더킹 파인...
  - 본문 수집 중: [내돈내산] 신제품 핫식스 더킹 아이...
[72/8196] 검색 중: 세븐일레븐 삼립)잘익은흑임자이야기110g
  - 본문 수집 중: 매력있었던 삼립 잘익은 흑임자 이야기...
  - 본문 수집 중: 씨유 편의점 간식 [삼립빵 잘 익은 ...
  - 본문 수집 중: 삼립 잘 익은 흑임자이야기, 흑임자빵...
[73/8196] 검색 중: 세븐일레븐 APP)노떼로사바시아
  - 본문 수집 중: 세븐일레븐에서 만나는 인기와인 할인!...
  - 본문 수집 중: 2025년 11월 15일 06시 ~ ...
[74/8196] 검색 중: 세븐일레븐 PB)오가다레몬꿀물280ml(8입 판매용)
  - 본문 수집 중: 편의점행사정보;세븐일레븐 12월 프로...
  - 본문 수집 중: 삿포로 4박 5일 커플 여행 일정 비...
  - 본문 수집 중: 세븐일레븐 8월행사 1+1 총정리(카...
[75/8196] 검색 중: 세븐일레븐 효성)한주본소금1kg
  - 본문 수집 중: 웨딩촬영 끝나니까 11월이야.....
  - 본문 수집 중: 세부 어학연수 #7주차 [잊지 못할 ...
  - 본문 수집 중: 호주 생활 17주차 - 빅토리아 윈터...
[76/8196] 검색 중: 세븐일레븐 쟈뎅)카페라떼230ml
  - 본문 수집 중: 죠리퐁 라떼 - 세븐일레븐 편의점 신...
  - 본문 수집 중: [세븐일레븐]죠리퐁카페라떼...
  - 본문 수집 중: 4월 편의점 음료 할인 행사 총정리(...
[77/8196] 검색 중: 세븐일레븐 7P)스트롱사와라임350ml
  - 본문 수집 중: 세븐일레븐 스트롱사와 라임맛 가격 도...
  - 본문 수집 중: 세븐일레븐 스트롱사와 라임맛 후기...
  - 본문 수집 중: 스트롱사와 시콰사 도수 용량 세븐일레...
[78/8196] 검색 중: 세븐일레븐 해태)오사쯔60g
  - 본문 수집 중: 세븐일레븐 과자 추천 해태 오사쯔빠스...
  - 본문 수집 중: 오사쯔 맛탕 과자 세븐일레븐 9월행사...
  - 본문 수집 중: 해태 오사쯔 맛탕 달달하구 고소해!...
[79/8196] 검색 중: 세븐일레븐 에이)시크릿쥬쥬사과220ml
  - 본문 수집 중: 슈가롤리 솜사탕(마카롱)  vs 시크...
  - 본문 수집 중: 인천 고은약국 판매제품 리스트,의약품...
  - 본문 수집 중: 365검단우리약국 23.07.16 재...
[80/8196] 검색 중: 세븐일레븐 세븐브로이)더굿바이브논알콜355
  - 본문 수집 중: 더굿바이브 비엔나 라거. 내가 좋아했...
  - 본문 수집 중: 광안리 맥주집 남영탉  세븐브로이 콜...
  - 본문 수집 중: 우체국 족발덮밥 우티쏨땀 태국 세븐일...
--- 현재까지 221건 저장 완료 ---
[81/8196] 검색 중: 세븐일레븐 아영)라벨5 700ml
  - 본문 수집 중: 세븐일레븐 711 4월의 와인 정보 ...
  - 본문 수집 중: 어울리는 [라벨5 스카치... 할인가...
  - 본문 수집 중: 711 세븐일레븐 편의점 2025년 ...
[82/8196] 검색 중: 세븐일레븐 매크로)하이츄사우어(딸기맛)
  - 본문 수집 중: [모리나가] 하이츄 버라이어티팩...
  - 본문 수집 중: 빵떡이를 위한 일본 편의점 간식 추천...
  - 본문 수집 중: cu편의점 3월행사 : 3월 화이트데...
[83/8196] 검색 중: 세븐일레븐 동아)모닝케어간솔루션젤리스틱15g
  - 본문 수집 중: 동아제약 그린세라-f 모닝케어 위솔루...
  - 본문 수집 중: 동아제약, '모닝케어 간솔루션 젤리스...
  - 본문 수집 중: 편의점 숙취해소제 임시완 모닝케어 젤...
[84/8196] 검색 중: 세븐일레븐 PB)럭히밥사골곰탕꾹밥225g
  - 본문 수집 중: 편의점 추천 세븐일레븐 히밥 럭히밥 ...
  - 본문 수집 중: [편의점 음식 리뷰] 세븐일레븐 럭히...
  - 본문 수집 중: 럭히밥 사골곰탕 꾹밥 먹어보고 소개합...
[85/8196] 검색 중: 세븐일레븐 롯데)마가렛트크림치즈갈릭176g
  - 본문 수집 중: 롯데 마가렛트 크림치즈갈릭 맛! 갈릭...
  - 본문 수집 중: 제철작물로 만든 2025년 한정판 롯...
  - 본문 수집 중: [내돈내산] 신상과자 롯데 마가렛트 ...
[86/8196] 검색 중: 세븐일레븐 PB)고기만두168g
  - 본문 수집 중: 세븐일레븐 11월 행사 편의점 맥주 ...
  - 본문 수집 중: 일본 편의점 추천 음식 세븐일레븐 간...
  - 본문 수집 중: 2026년 2월 세븐일레븐 행사 1+...
[87/8196] 검색 중: 세븐일레븐 한우 알꼬리 선물세트 2kg
  - 본문 수집 중: 타이밍 이게 맞나 (14k 금 시세,...
  - 본문 수집 중: 명절 선물세트 : 세븐일레븐 2023...
  - 본문 수집 중: 청주명절선물세트 추천하는 한우선물세트...
[88/8196] 검색 중: 세븐일레븐 삼립)야채호빵(찜기낱개)
  - 본문 수집 중: 삼립 호빵 전자레인지 시간 찜기 냉동...
  - 본문 수집 중: 삼립 호빵 전자레인지 피자 호빵 찐빵...
  - 본문 수집 중: 삼립 호빵 보관 냉동보관 전자레인지 ...
[89/8196] 검색 중: 세븐일레븐 25설)천호일품녹용발효홍삼
  - 본문 수집 중: 천호엔케어 일품녹용발효홍삼 명절선물로...
  - 본문 수집 중: 명절선물 녹용 발효홍삼 “천호앤케어 ...
  - 본문 수집 중: 명절선물 추천 | 천호엔케어 일품 녹...
[90/8196] 검색 중: 세븐일레븐 서울)초콜릿우유미니컵100ml
  - 본문 수집 중: 편의점 신상 총정리 (CU vs GS...
  - 본문 수집 중: 일본 편의점 추천 세븐일레븐 간식 과...
  - 본문 수집 중: 일본 편의점 로손 편의점 · 세븐일레...
--- 현재까지 251건 저장 완료 ---
[91/8196] 검색 중: 세븐일레븐 해태)프리츠발효버터34g
  - 본문 수집 중: 해태 맛있는 버터과자 통밀스틱 프리츠...
  - 본문 수집 중: CU 편의점과자 해태 프리츠 발효버터...
  - 본문 수집 중: 해태 프리츠사라다맛 35g 프리츠발효...
[92/8196] 검색 중: 세븐일레븐 세븐브로이)넌강서무알콜355ml캔
  - 본문 수집 중: 저칼로리 세븐브로이맥주 넌강서 논알콜...
  - 본문 수집 중: 무알콜맥주 세븐브로이맥주 넌강서 논알...
  - 본문 수집 중: 향긋한 논알콜맥주 추천 세븐브로이맥주...
[93/8196] 검색 중: 세븐일레븐 APP)식사이론 넛츠포테이토샌드
  - 본문 수집 중: 세븐일레븐 신상 식사이론 넛츠포테이토...
  - 본문 수집 중: 세븐일레븐 서울대벤처타운점... 식사...
  - 본문 수집 중: 세븐일레븐 넛츠포테이토 샌드 칼로리 ...
[94/8196] 검색 중: 세븐일레븐 프로엠)레몬에이드제로320ml
  - 본문 수집 중: 세븐일레븐 편의점 대호 Big블루레몬...
  - 본문 수집 중: 세븐일레븐 편의점 신상 리뷰 ‘티로그...
  - 본문 수집 중: 세븐일레븐 제로음료, 티로그 제로아이...
[95/8196] 검색 중: 세븐일레븐 훈스)불고기&소시지핫도그145g
  - 본문 수집 중: [고속도로 휴게소 맛집 찾기] 서울양...
[96/8196] 검색 중: 세븐일레븐 화요)화요3종세트
  - 본문 수집 중: 카카오 선물하기 추천템 화요 한글에디...
  - 본문 수집 중: 카카오 선물하기 추천  화요 3종 세...
  - 본문 수집 중: 명절 술 선물세트 추천, 화요 소주 ...
[97/8196] 검색 중: 세븐일레븐 트릿지)그랜드감자칩(씨솔트)
  - 본문 수집 중: 세븐일레븐행사상품 편의점3+1행사 발...
  - 본문 수집 중: [발스낵] 그랜드 감자칩...
  - 본문 수집 중: [일상] 버거파크 성신여대점, 햄버거...
[98/8196] 검색 중: 세븐일레븐 SAMG)프린세스아름핑하트젤리50g
  - 본문 수집 중: 프린세스 캐치티니핑 젤리... 왕관젤...
  - 본문 수집 중: 프린세스 티니핑 젤리 뽀니핑,사뿐핑,...
  - 본문 수집 중: 프린세스 아름핑의 하트젤리 리뷰!...
[99/8196] 검색 중: 세븐일레븐 삼립)광천식김우동206g
  - 본문 수집 중: GS25 삼립 하이면 광천식 김우동(...
  - 본문 수집 중: 하이면우동 소문난광천김 김우동 내돈내...
  - 본문 수집 중: 김우동 편의점 컵라면 추천 GS25 ...
[100/8196] 검색 중: 세븐일레븐 하림)사골쌀라면봉지
  - 본문 수집 중: 하림 사골쌀라면 신상 봉지 맛있는 라...
  - 본문 수집 중: 봉지 라면추천 신상라면 하림 사골쌀라...
  - 본문 수집 중: 맛있는 하림라면 봉지 라면추천! 하림...
--- 현재까지 279건 저장 완료 ---
[101/8196] 검색 중: 세븐일레븐 아영)우르바노750ml
[102/8196] 검색 중: 세븐일레븐 삼립)흑백요리사고추잡채호빵(1입)
  - 본문 수집 중: 삼립 고추잡채 호빵 흑백요리사 임태훈...
  - 본문 수집 중: 궁금해서 맛본 삼립호빵 흑백요리사 흑...
  - 본문 수집 중: 삼립호빵 고추잡채 조금 아쉬운 맛이네...
[103/8196] 검색 중: 세븐일레븐 삼양)야키소바불닭볶음면큰컵
  - 본문 수집 중: 삼양 야키소바 불닭볶음면 큰컵 컵라면...
  - 본문 수집 중: 투움바라면, 삼양 야키소바 불닭볶음면...
  - 본문 수집 중: [라면] 삼양 "야키소바 불닭볶음면 ...
[104/8196] 검색 중: 세븐일레븐 삼립)1,900햄뽀끼빅브레드105g
  - 본문 수집 중: 삼립 신상 런치빵 시리즈 4종 솔직 ...
  - 본문 수집 중: [식품 신제품 뉴스] 2025년 2월...
[105/8196] 검색 중: 세븐일레븐 효자원)서주아이스크림
[106/8196] 검색 중: 세븐일레븐 TDF)생미쉘초코도넛180g
[107/8196] 검색 중: 세븐일레븐 그레)비달멀티비타민롤리팝120g
  - 본문 수집 중: 다이소 사탕·껌 가격, 종류...
  - 본문 수집 중: 이마트는 왜 다이소보다 비쌀까? 가격...
[108/8196] 검색 중: 세븐일레븐 드림)비타키링(곰돌이푸)10g
  - 본문 수집 중: [리뷰] 세븐일레븐 곰돌이 푸 비타키...
  - 본문 수집 중: 곰돌이푸 비타키링 때늦은 구매...
  - 본문 수집 중: 귀여운 디즈니 곰돌이푸 비타 키링 편...
[109/8196] 검색 중: 세븐일레븐 해태)열불날만두하지300g
  - 본문 수집 중: 해태 매운만두 열불날만두하지 군만두...
  - 본문 수집 중: 해태 고향만두 신상품 열불날만두하지....
  - 본문 수집 중: 해태 매운 고향만두 신상, '열불날만...
[110/8196] 검색 중: 세븐일레븐 칠성)델몬트망고제로200ml
  - 본문 수집 중: 델몬트드링크 제로칼로리 망고 사과 즐...
  - 본문 수집 중: 델몬트  드링크 제로칼로리 사과주스 ...
  - 본문 수집 중: 푸드페어링 다이어트음료추천 롯데칠성 ...
--- 현재까지 298건 저장 완료 ---
[111/8196] 검색 중: 세븐일레븐 나뚜루)바닐라컵100ml
  - 본문 수집 중: 나뚜루 아이스크림 미니컵 초코 바닐라...
  - 본문 수집 중: 세븐일레븐 편의점 9월 행사 맥주, ...
  - 본문 수집 중: 세븐일레븐 5월 행사 편의점 맥주 도...
[112/8196] 검색 중: 세븐일레븐 APP전용)리얼소프트에그샌드
  - 본문 수집 중: 세븐일레븐 편의점 샌드위치 추천 리얼...
  - 본문 수집 중: 세븐일레븐 리얼 소프트 에그 샌드 후...
  - 본문 수집 중: 편의점샌드위치추천_세븐일레븐 리얼소프...
[113/8196] 검색 중: 세븐일레븐 코카)파워에이드브라스트
  - 본문 수집 중: 괌여행 떠나자! 세븐일레븐 코카콜라 ...
  - 본문 수집 중: 세븐일레븐 7월행사 추천 7ELEVE...
  - 본문 수집 중: 세븐일레븐 이벤트, 파워에이드와 게토...
[114/8196] 검색 중: 세븐일레븐 롯데)알파벳변신로봇캔디7g
  - 본문 수집 중: ABC미니로봇 캔디를 선택한 일등군의...
  - 본문 수집 중: 세븐일레븐 후덕죽 깐풍칩 오잉 65g...
  - 본문 수집 중: 맛있는 후덕죽 셰프의 중화풍 과자 세...
[115/8196] 검색 중: 세븐일레븐 선린)호박찹쌀약과
  - 본문 수집 중: [세븐일레븐] 선린 호박찹쌀약과,7-...
  - 본문 수집 중: 세븐일레븐 10월 할인상품 선린 호박...
  - 본문 수집 중: [밀카 레오, 밀카 그레인, 세븐일레...
[116/8196] 검색 중: 세븐일레븐 나뚜루)퓨어코코넛파인트
  - 본문 수집 중: 나뚜루 퓨어 코코넛 파인트 먹어봤어요...
  - 본문 수집 중: 나뚜루 ㅣ 비건파인트(퓨어코코넛&캐슈...
  - 본문 수집 중: cu 나뚜루 캐슈바닐라, 퓨어코코넛 ...
[117/8196] 검색 중: 세븐일레븐 풀무원)생오리엔탈드레싱115g
  - 본문 수집 중: 시판 샐러드 드레싱(풀무원)  칼로리...
[118/8196] 검색 중: 세븐일레븐 오뚜기)마포식차돌된장찌개
  - 본문 수집 중: 편의점 행사 상품 오뚜기 마포식 차돌...
  - 본문 수집 중: 오뚜기 마포식 차돌된장찌개. 밥도둑 ...
  - 본문 수집 중: 오뚜기 신메뉴 마포식 차돌된장찌개 후...
[119/8196] 검색 중: 세븐일레븐 동원)산양유프로틴70g
  - 본문 수집 중: 편의점 신상 동원 산양유프로틴밀크팡 ...
  - 본문 수집 중: 단백질 간식 동원 산양유 프로틴 밀크...
  - 본문 수집 중: 간식리뷰 동원 산양유 프로틴 밀크팡 ...
[120/8196] 검색 중: 세븐일레븐 훼밀리)골든카레중간맛230g
  - 본문 수집 중: 일본 시부야 여행 필수 코스, 편의점...
  - 본문 수집 중: 순한맛 & 훼밀리) 에스비 골든카레소...
  - 본문 수집 중: 다이어트 식단용 닭가슴살 카레 만들기...
--- 현재까지 326건 저장 완료 ---
[121/8196] 검색 중: 세븐일레븐 롯데)알바리쉬라즈템프라187ml
[122/8196] 검색 중: 세븐일레븐 빙그레)왕실쿠키샌드바닐라120ml
  - 본문 수집 중: 샌드 아이스크림, 빙그레 왕실쿠키샌드...
  - 본문 수집 중: 홈플러스 빙그레 왕실쿠키샌드 바닐라 ...
  - 본문 수집 중: 빙그레 왕실쿠키샌드 바닐라 & 초코맛...
[123/8196] 검색 중: 세븐일레븐 프레시팜)하우스밀감 3입
  - 본문 수집 중: 3월4주차 편의점신상 (GS25,CU...
  - 본문 수집 중: 급할 때 꿀템 3,800원에 대란 1...
  - 본문 수집 중: 2026년 2월3주차 편의점신상 (G...
[124/8196] 검색 중: 세븐일레븐 하림)장인라면맵싸한맛큰컵
  - 본문 수집 중: 하림 장인라면 맵싸한맛 컵 [라면 완...
  - 본문 수집 중: 비싼 매운라면 하림 더 미식 장인라면...
  - 본문 수집 중: 더미식 장인라면 맵싸한맛 담백한맛 얼...
[125/8196] 검색 중: 세븐일레븐 롯데)설레임커피200ml
  - 본문 수집 중: 생애 3번째 마라톤 2025 설레임런...
  - 본문 수집 중: 세븐일레븐 롯데카드 8월행사!!...
  - 본문 수집 중: 세븐일레븐 10월행사 편의점 맥주 와...
[126/8196] 검색 중: 세븐일레븐 제니코)불닭스트링치즈20g
  - 본문 수집 중: 《여덟번째 글》 불닭볶음에 어울리는 ...
  - 본문 수집 중: [내돈먹방]불닭볶음면 후랑크소세지 스...
  - 본문 수집 중: [7월 세븐일레븐 편의점] 1+1, ...
[127/8196] 검색 중: 세븐일레븐 몽블랑)고다큐브치즈100g
  - 본문 수집 중: 와인이나 칵테일 주류에 잘 어울리는 ...
  - 본문 수집 중: 와인팩토리 - 몽블랑 체다... 치즈...
  - 본문 수집 중: 몽블랑 고다 큐브 치즈 100g...
[128/8196] 검색 중: 세븐일레븐 키즈웰)젤리스트로우77g
  - 본문 수집 중: "…MZ들 ‘얼려먹는 젤리’에 꽂혔다...
  - 본문 수집 중: 다이소 마시멜로우·젤리 가격, 종류...
  - 본문 수집 중: [요모조모/젤리특집⑨] 66-세븐일레...
[129/8196] 검색 중: 세븐일레븐 삼립)개굴닌자밀키소다롤85g
  - 본문 수집 중: 삼립. 개굴닌자 밀키소다맛 롤케익 후...
  - 본문 수집 중: [포켓몬스터빵]개굴닌자의 밀키소다맛 ...
  - 본문 수집 중: [일상] 삼립 포켓몬빵 개굴닌자의 밀...
[130/8196] 검색 중: 세븐일레븐 칠성)데일리C레몬워터500ml
  - 본문 수집 중: 롯데칠성 - 데일리C레몬워터 / 데일...
  - 본문 수집 중: 롯데칠성 / 데일리C 레몬워터...
  - 본문 수집 중: [롯데칠성 데일리C 아미노워터 헬씨바...
--- 현재까지 353건 저장 완료 ---
[131/8196] 검색 중: 세븐일레븐 롯데)찰떡아이스X푸하하크림빵
  - 본문 수집 중: [세븐일레븐] 롯데월드몰 ‘푸하하 소...
  - 본문 수집 중: 세븐일레븐 x 롯데 자이언츠 달달꿀빵...
  - 본문 수집 중: 푸하하 크림빵 편의점에서도 구입 가능...
[132/8196] 검색 중: 세븐일레븐 롯데)티처스빠다장조림삼각
  - 본문 수집 중: 세븐일레븐 정승제 조정식 공부 자극템...
  - 본문 수집 중: 당신을 위한 필살기! 세븐일레븐×티처...
  - 본문 수집 중: 세븐일레븐 알바생이 말아주는 <세븐일...
[133/8196] 검색 중: 세븐일레븐 한국술)강쇠13도 375ml
  - 본문 수집 중: (전통주납품)지리산기운내린강쇠...
  - 본문 수집 중: 황진이주, 강쇠주 상시 입고되어 있습...
  - 본문 수집 중: [ 사당역 소개팅 / 더리프 라운지바...
[134/8196] 검색 중: 세븐일레븐 매일)페레로란드누아아이스크림70ml
  - 본문 수집 중: 페레로 란드누아 아이스크림바 달콤한 ...
  - 본문 수집 중: 바삭하고 쫀득한 페레로 아이스크림 바...
  - 본문 수집 중: 페레로로쉐아이스크림 란드누아 클래식 ...
[135/8196] 검색 중: 세븐일레븐 유앤)쫀득레인보우마시멜로우150g
[136/8196] 검색 중: 세븐일레븐 신세계)트롤브루자몽500ml캔
  - 본문 수집 중: [주류 302][캔-500ml] 트롤...
  - 본문 수집 중: 트롤브루 자몽 맥주...
  - 본문 수집 중: 트롤브루 자몽 맥주 : Troll B...
[137/8196] 검색 중: 세븐일레븐 PB)수미네묵은지김치찌개라면
  - 본문 수집 중: 편의점 라면 추천 세븐일레븐 수미네 ...
  - 본문 수집 중: 세븐일레븐 수미네 묵은지 김치찌개 라...
  - 본문 수집 중: 세븐일레븐 편의점 컵라면 수미네 묵은...
[138/8196] 검색 중: 세븐일레븐 APP)푸나무소비뇽블랑750ml
  - 본문 수집 중: [시음노트] 흐노디 루아르 소비뇽 블...
  - 본문 수집 중: [시음노트] 펄리셔 소비뇽 블랑 23...
  - 본문 수집 중: [시음노트] 앨런스콧 앙리마티스 블루...
[139/8196] 검색 중: 세븐일레븐 슬러피)펩시(레귤러)
  - 본문 수집 중: [세븐일레븐] 푸드드림 빅바이트 & ...
  - 본문 수집 중: [세븐일레븐] 푸드드림... 빅바이트...
[140/8196] 검색 중: 세븐일레븐 에노)마초걸(틴타피나)750ml
  - 본문 수집 중: 세븐일레븐 편의점 4월 와인 샴페인 ...
  - 본문 수집 중: 카사 로호, 틴타 피나 2019 Ca...
  - 본문 수집 중: 세븐일레븐 3월 와인 샴페인 위스키 ...
--- 현재까지 379건 저장 완료 ---
[141/8196] 검색 중: 세븐일레븐 생지)엘유_모카번80g
[142/8196] 검색 중: 세븐일레븐 나무)동결건조캔디50g
  - 본문 수집 중: 편의점 신상간식 : 동결건조로 돌아온...
  - 본문 수집 중: 편의점 신상 사랑방 동결건조 캔디추억...
  - 본문 수집 중: [제품리뷰]콰삭! 사르르 동결건조 사...
[143/8196] 검색 중: 세븐일레븐 PB)헤이즐넛블랙1L
  - 본문 수집 중: 시로이코이비토 면세점 가격 (+편의점...
  - 본문 수집 중: Coffee)/세븐일레븐 PB상품/세...
  - 본문 수집 중: 세븐일레븐 7월행사 추천 7ELEVE...
[144/8196] 검색 중: 세븐일레븐 서주)두바이스타일초코바90ml
  - 본문 수집 중: 두바이 스타일 피스타치오 초코바...

KeyboardInterrupt:

In [4]:
import os
import time
import random
import pandas as pd
import polars as pl
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from tqdm import tqdm  # 진행률 바 추가!

# 1. 환경 변수 및 설정
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")
INPUT_DATA_PATH = "/Users/hajiyoon/workspace/data/processed/최종_상품단위_데이터셋.csv"
OUTPUT_PATH = "seven_eleven_remaining_80_reviews.csv"

def get_remaining_products():
    """
    중분류별 매출 누적 비율 80% 이상(매출 기여도가 낮은 나머지 상품군)인 상품들 추출
    """
    print("데이터 로딩 및 하위 매출 상품군(나머지 80% 상품수 기준) 추출 중...")
    
    lf = pl.scan_csv(INPUT_DATA_PATH)
    
    df = lf.select([
        pl.col("상품중분류명").alias("중분류명"),
        pl.col("상품명"),
        pl.col("총_매출금액").alias("총매출금액")
    ]).collect()

    df = df.with_columns([
        pl.col("총매출금액").sum().over("중분류명").alias("중분류총매출금액")
    ])
    
    df = df.sort(["중분류명", "총매출금액"], descending=[False, True])
    df = df.with_columns([
        (pl.col("총매출금액").cum_sum().over("중분류명") / pl.col("중분류총매출금액")).alias("누적비율")
    ])

    df_remaining = df.filter(pl.col("누적비율") >= 0.8)
    return df_remaining.select("상품명").unique().to_series().to_list()

def setup_driver():
    """
    Selenium Chrome 드라이버 설정
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
    
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)
    return driver

def get_blog_content(driver, url):
    """
    Selenium을 사용하여 블로그 본문 추출
    """
    try:
        driver.get(url)
        wait = WebDriverWait(driver, 5)
        wait.until(EC.presence_of_element_located((By.ID, "mainFrame")))
        driver.switch_to.frame("mainFrame")
        
        selectors = [
            "div.se-main-container",
            "div#postViewArea",
            "div[id^='post-view']",
            "div.se-viewer"
        ]
        
        for selector in selectors:
            try:
                element = driver.find_element(By.CSS_SELECTOR, selector)
                text = element.text.strip()
                if text:
                    return text
            except:
                continue
        return "본문 추출 실패"
    except Exception as e:
        return f"크롤링 오류: {e}"
    finally:
        try:
            driver.switch_to.default_content()
        except:
            pass

def main():
    if not CLIENT_ID or not CLIENT_SECRET:
        print("오류: .env 파일에 NAVER_CLIENT_ID 및 NAVER_CLIENT_SECRET 설정이 필요합니다.")
        return

    # 1. 대상 상품 추출
    items = get_remaining_products()
    
    # 🌟 이어달리기 로직: 특정 상품 찾아서 그 다음부터 자르기
    resume_item = "롯데)제로쿠키&크림바80ml"
    
    if resume_item in items:
        start_idx = items.index(resume_item) + 1 # 완료된 상품 바로 다음 인덱스
        items = items[start_idx:]
        print(f"\n✅ '{resume_item}' 이후부터 이어서 작업을 시작합니다.")
    else:
        print(f"\n⚠️ '{resume_item}'을 목록에서 찾을 수 없어 처음부터 진행합니다.")
        
    print(f"앞으로 수집할 남은 상품 수: {len(items)}개\n")
    
    batch_results = [] # 10개씩 모아서 저장하고 비울 임시 바구니
    driver = setup_driver()
    
    try:
        # tqdm으로 묶어서 예쁜 진행률 바 생성
        for i, item in enumerate(tqdm(items, desc="크롤링 진행률", ncols=100), 1):
            search_query = f"세븐일레븐 {item}"
            
            api_url = f"https://openapi.naver.com/v1/search/blog.json?query={quote(search_query)}&display=3&sort=sim"
            api_headers = {
                "X-Naver-Client-Id": CLIENT_ID,
                "X-Naver-Client-Secret": CLIENT_SECRET
            }
            
            try:
                res = requests.get(api_url, headers=api_headers)
                if res.status_code == 200:
                    blog_items = res.json().get('items', [])
                    for blog in blog_items:
                        title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                        link = blog['link']
                        
                        content = get_blog_content(driver, link)
                        
                        batch_results.append({
                            '검색어': search_query,
                            '상품명': item,
                            '블로그제목': title,
                            '블로그링크': link,
                            '본문내용': content
                        })
                        time.sleep(random.uniform(1, 2))
                else:
                    tqdm.write(f"⚠️ API 호출 실패 (상품명: {item}, 상태코드: {res.status_code})")
            except Exception as e:
                tqdm.write(f"⚠️ 검색 처리 중 오류 (상품명: {item}): {e}")
            
            # 3. 주기적 이어쓰기 (10개 상품마다)
            if i % 10 == 0 and batch_results:
                df_batch = pd.DataFrame(batch_results)
                
                # 기존 파일이 없으면 새로 만들고, 있으면 아래에 추가(append)
                if not os.path.exists(OUTPUT_PATH):
                    df_batch.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
                else:
                    df_batch.to_csv(OUTPUT_PATH, mode='a', index=False, header=False, encoding='utf-8-sig')
                
                batch_results.clear() # ⭐️ 덮어쓰기 방지: 다 썼으면 바구니 비우기
                
    finally:
        driver.quit()
        # 마지막으로 남은 데이터 털어넣기
        if batch_results:
            df_batch = pd.DataFrame(batch_results)
            if not os.path.exists(OUTPUT_PATH):
                df_batch.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
            else:
                df_batch.to_csv(OUTPUT_PATH, mode='a', index=False, header=False, encoding='utf-8-sig')
                
        print(f"\n🎉 크롤링 종료! 데이터가 {OUTPUT_PATH}에 안전하게 이어쓰기 되었습니다.")

if __name__ == "__main__":
    main()

데이터 로딩 및 하위 매출 상품군(나머지 80% 상품수 기준) 추출 중...

✅ '롯데)제로쿠키&크림바80ml' 이후부터 이어서 작업을 시작합니다.
앞으로 수집할 남은 상품 수: 1062개

크롤링 진행률: 100%|██████████████████████████████████████████| 1062/1062 [2:19:36<00:00,  7.89s/it]

🎉 크롤링 종료! 데이터가 seven_eleven_remaining_80_reviews.csv에 안전하게 이어쓰기 되었습니다.

In [5]:
import os
import time
import random
import pandas as pd
import polars as pl
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from tqdm import tqdm

# 1. 환경 변수 및 설정
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")
INPUT_DATA_PATH = "/Users/hajiyoon/workspace/data/processed/최종_상품단위_데이터셋.csv"
OUTPUT_PATH = "seven_eleven_remaining_80_reviews.csv"

def get_remaining_products():
    print("데이터 로딩 및 하위 매출 상품군 추출 중...")
    lf = pl.scan_csv(INPUT_DATA_PATH)
    df = lf.select([
        pl.col("상품중분류명").alias("중분류명"),
        pl.col("상품명"),
        pl.col("총_매출금액").alias("총매출금액")
    ]).collect()

    df = df.with_columns([
        pl.col("총매출금액").sum().over("중분류명").alias("중분류총매출금액")
    ])
    
    df = df.sort(["중분류명", "총매출금액"], descending=[False, True])
    df = df.with_columns([
        (pl.col("총매출금액").cum_sum().over("중분류명") / pl.col("중분류총매출금액")).alias("누적비율")
    ])

    df_remaining = df.filter(pl.col("누적비율") >= 0.8)
    return df_remaining.select("상품명").unique().to_series().to_list()

def setup_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
    
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)
    return driver

def get_blog_content(driver, url):
    try:
        driver.get(url)
        wait = WebDriverWait(driver, 5)
        wait.until(EC.presence_of_element_located((By.ID, "mainFrame")))
        driver.switch_to.frame("mainFrame")
        
        selectors = [
            "div.se-main-container",
            "div#postViewArea",
            "div[id^='post-view']",
            "div.se-viewer"
        ]
        
        for selector in selectors:
            try:
                element = driver.find_element(By.CSS_SELECTOR, selector)
                text = element.text.strip()
                if text:
                    return text
            except:
                continue
        return "본문 추출 실패"
    except Exception as e:
        return f"크롤링 오류: {e}"
    finally:
        try:
            driver.switch_to.default_content()
        except:
            pass

def main():
    if not CLIENT_ID or not CLIENT_SECRET:
        print("오류: .env 파일에 API 키 설정이 필요합니다.")
        return

    items = get_remaining_products()
    
    start_item = "효성)한주본소금1kg"
    end_item = "롯데)제로쿠키&크림바80ml"
    
    if start_item in items and end_item in items:
        start_idx = items.index(start_item)
        end_idx = items.index(end_item)
        
        if start_idx > end_idx:
            start_idx, end_idx = end_idx, start_idx
            
        items = items[start_idx : end_idx + 1]
        print(f"\n✅ '{start_item}'부터 '{end_item}'까지 총 {len(items)}개의 상품을 다시 수집합니다.")
    else:
        print(f"\n⚠️ 목록에서 상품을 찾을 수 없습니다. 상품명을 다시 확인해 주세요.")
        return

    # 🌟 새롭게 추가된 핵심 로직: 기존 파일에서 '잘못된 데이터' 미리 삭제하기!
    if os.path.exists(OUTPUT_PATH):
        print("\n🧹 크롤링 시작 전, 기존 파일에서 잘못 수집된 옛날 데이터를 청소합니다...")
        try:
            # 1. 기존 파일을 읽어옴
            existing_df = pd.read_csv(OUTPUT_PATH)
            original_len = len(existing_df)
            
            # 2. 이번에 수집할 'items' 리스트에 속하지 않은(~) 정상 데이터만 남김
            cleaned_df = existing_df[~existing_df['상품명'].isin(items)]
            
            # 3. 청소된 데이터로 덮어쓰기 저장
            cleaned_df.to_csv(OUTPUT_PATH, index=False, encoding='utf-8-sig')
            
            deleted_count = original_len - len(cleaned_df)
            print(f"✨ 청소 완료! 잘못된 데이터 {deleted_count}줄을 삭제했습니다.")
            print(f"📊 현재 남은 정상 데이터 수: {len(cleaned_df)}줄\n")
            
        except Exception as e:
            print(f"⚠️ 기존 파일 청소 중 오류 발생: {e}")
            return # 청소하다 에러나면 혹시 모르니 멈춤

    batch_results = []
    driver = setup_driver()
    
    try:
        for i, item in enumerate(tqdm(items, desc="구간 복구 진행률", ncols=100), 1):
            search_query = f"세븐일레븐 {item}"
            
            api_url = f"https://openapi.naver.com/v1/search/blog.json?query={quote(search_query)}&display=3&sort=sim"
            api_headers = {
                "X-Naver-Client-Id": CLIENT_ID,
                "X-Naver-Client-Secret": CLIENT_SECRET
            }
            
            try:
                res = requests.get(api_url, headers=api_headers)
                if res.status_code == 200:
                    blog_items = res.json().get('items', [])
                    for blog in blog_items:
                        title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                        link = blog['link']
                        
                        content = get_blog_content(driver, link)
                        
                        batch_results.append({
                            '검색어': search_query,
                            '상품명': item,
                            '블로그제목': title,
                            '블로그링크': link,
                            '본문내용': content
                        })
                        time.sleep(random.uniform(1, 2))
                else:
                    tqdm.write(f"⚠️ API 실패 (상품: {item})")
            except Exception as e:
                tqdm.write(f"⚠️ 검색 오류 (상품: {item}): {e}")
            
            if i % 10 == 0 and batch_results:
                df_batch = pd.DataFrame(batch_results)
                # 청소된 파일 밑에 안전하게 이어쓰기
                df_batch.to_csv(OUTPUT_PATH, mode='a', index=False, header=False, encoding='utf-8-sig')
                batch_results.clear()
                
    finally:
        driver.quit()
        if batch_results:
            df_batch = pd.DataFrame(batch_results)
            df_batch.to_csv(OUTPUT_PATH, mode='a', index=False, header=False, encoding='utf-8-sig')
                
        print(f"\n🎉 구간 복구 완료! 깨끗한 새 데이터가 {OUTPUT_PATH}에 완벽하게 교체/저장되었습니다.")

if __name__ == "__main__":
    main()

데이터 로딩 및 하위 매출 상품군 추출 중...

✅ '효성)한주본소금1kg'부터 '롯데)제로쿠키&크림바80ml'까지 총 3735개의 상품을 다시 수집합니다.

🧹 크롤링 시작 전, 기존 파일에서 잘못 수집된 옛날 데이터를 청소합니다...
✨ 청소 완료! 잘못된 데이터 6710줄을 삭제했습니다.
📊 현재 남은 정상 데이터 수: 8143줄

구간 복구 진행률: 100%|███████████████████████████████████████| 3735/3735 [8:02:18<00:00,  7.75s/it]

🎉 구간 복구 완료! 깨끗한 새 데이터가 seven_eleven_remaining_80_reviews.csv에 완벽하게 교체/저장되었습니다.

In [6]:
import pandas as pd
import os

# 파일 경로 설정
ORIGINAL_FILE = "seven_eleven_remaining_80_reviews.csv"
ERROR_FILE = "seven_eleven_error_products.csv" # 불량 데이터만 모아둘 새 파일!

def separate_clean_and_error_data():
    if not os.path.exists(ORIGINAL_FILE):
        print(f"⚠️ {ORIGINAL_FILE} 파일이 같은 폴더에 없는 것 같아요!")
        return

    print("🔍 기존 데이터를 스캔하여 '크롤링 오류'를 솎아냅니다...\n")
    df = pd.read_csv(ORIGINAL_FILE)
    
    # 🌟 '크롤링 오류'나 '본문 추출 실패'로 시작하는 불량 데이터 색출!
    error_mask = df['본문내용'].astype(str).str.startswith('크롤링 오류') | df['본문내용'].astype(str).str.startswith('본문 추출 실패')
    
    error_df = df[error_mask]
    clean_df = df[~error_mask]
    
    if error_df.empty:
        print("🎉 대박! 오류 난 데이터가 하나도 없습니다. 바로 팀원들에게 보내도 돼요!")
        return
        
    unique_error_items = error_df['상품명'].unique()
    
    # 1. 깨끗한 데이터는 기존 파일 이름으로 덮어쓰기 (팀원 전달용 🎁)
    clean_df.to_csv(ORIGINAL_FILE, index=False, encoding='utf-8-sig')
    print(f"✅ [청소 완료] 정상 데이터 {len(clean_df)}줄만 남겨서 '{ORIGINAL_FILE}'에 덮어썼습니다.")
    print("   👉 이 파일을 바로 팀원들에게 전달하시면 됩니다!")

    # 2. 에러난 데이터는 새로운 파일로 빼두기 (나중에 복구할 용도 🛠️)
    error_df.to_csv(ERROR_FILE, index=False, encoding='utf-8-sig')
    print(f"\n🚨 [격리 완료] 오류 데이터 {len(error_df)}줄은 '{ERROR_FILE}'에 따로 저장했습니다.")
    print(f"   👉 나중에 다시 크롤링해야 할 상품 종류는 총 {len(unique_error_items)}개입니다.")

if __name__ == "__main__":
    separate_clean_and_error_data()

🔍 기존 데이터를 스캔하여 '크롤링 오류'를 솎아냅니다...

✅ [청소 완료] 정상 데이터 11933줄만 남겨서 'seven_eleven_remaining_80_reviews.csv'에 덮어썼습니다.
   👉 이 파일을 바로 팀원들에게 전달하시면 됩니다!

🚨 [격리 완료] 오류 데이터 6563줄은 'seven_eleven_error_products.csv'에 따로 저장했습니다.
   👉 나중에 다시 크롤링해야 할 상품 종류는 총 2279개입니다.

## 이거 하면 돼!!!!!!!!

In [1]:
import pandas as pd 
import numpy as np

df = pd.read_csv('C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\전처리_EDA\\최종\\pos_data_food_final_상품단위.csv')
print(df.shape)

target_cat = ['컵커피', '냉장안주', '냉장간편식', '샐러드', '기능성드링크', '오징어', '가공미반류', '젤리', '캔', '조리냉동', '흰우유', '냉동간편식', '농산안주', '전통음료', '얼음', '노벨티', '용기면', '스포츠음료', '프로틴 음료', '스낵류', '비스킷류', '육포', '건해산물', '프로틴/시리얼', '초콜릿', '냉장베이커리', '세븐카페', '차음료', '커피음료', '너트류', '냉장주스', '껌', '상온간편식', '간식빵', '파우치', '가공우유', '냉동만두', '젤리류', '원컵', '차', '주스', '구움과자', '스낵안주', '컨셉카페', '냉장간식', '캔디류', '요구르트',
        '기타전통주', '삼각김밥', '떡', '햄버거', '냉장피자', '국산맥주', '양주', '샌드위치', '김밥', '와인', '초밥류', '도시락', '하이볼', '고급', '냉동디저트']

# strip() 후 필터링
filtered_df = df[df['상품중분류명'].str.strip().isin(target_cat)].copy()
print(f"필터링 후: {filtered_df.shape}")
# 저장
output_path = r'C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\전처리_EDA\최종\pos_data_food_final_상품단위_filtered.csv'
filtered_df.to_csv(output_path, index=False, encoding='utf-8-sig')
print("저장 완료:", output_path)

(10579, 26)
필터링 후: (8186, 26)
저장 완료: C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\전처리_EDA\최종\pos_data_food_final_상품단위_filtered.csv

In [2]:
success = pd.read_csv('C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\seven_eleven_blog_reviews_success.csv')
print(success.shape)
success.head(1)

(3181, 4)

,검색어,블로그제목,블로그링크,본문내용
0,세븐일레븐 CJ)둥근햇반210g,[무료배송]CJ제일제당 둥근 햇반 210g 36개,https://blog.naver.com/ccgu4745/223751684668,[11번가] [무료배송]CJ제일제당 둥근 햇반 210g 36개\n냉장/냉동식품>냉장...

In [4]:
success.isnull().sum()

검색어      0
블로그제목    0
블로그링크    0
본문내용     0
dtype: int64

In [3]:
fail = pd.read_csv('C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\seven_eleven_blog_reviews_fail_v1.csv')
print(fail.shape)
fail.head(1)

(74932, 6)

,중분류명,검색어,상품명,블로그제목,블로그링크,본문내용
0,하이볼,세븐일레븐 7P)스트롱사와자몽500ml,7P)스트롱사와자몽500ml,"세븐일레븐 스트롱사와 자몽, 라임 후기 과일 맥주 추천",https://blog.naver.com/lovekra88/223406679573,안녕하세요\n부사오지상 현대리입니다\n오늘은 얼마전 마셨던\n세븐일레븐 스트롱사와\...

In [5]:
fail.isnull().sum()

중분류명         0
검색어          0
상품명          0
블로그제목     3269
블로그링크     3269
본문내용     66075
dtype: int64

In [3]:
import sys
!{sys.executable} -m pip install selenium webdriver-manager

Collecting selenium
  Downloading selenium-4.43.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting certifi>=2026.1.4 (from selenium)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\alexj\anaconda3\lib\site-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: requests in c:\users\alexj\anaconda3\lib\site-packages (from webdriver-manager) (2.31.0)
Requirement already satisfied: python-dotenv in c:\users\alexj\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in c:\users\alexj\appdata\roaming\python\python311\site-packages (from webdriver-manager) (24.2)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: sortedcontainers in c:\users\alexj\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\alexj\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.4)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: cffi>=1.14 in c:\users\alexj\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.15.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\alexj\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\alexj\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: pycparser in c:\users\alexj\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\alexj\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.43.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -------------------- ------------------- 5.0/9.6 MB 23.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 24.5 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 21.3 MB/s eta 0:00:00
Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, websocket-client, urllib3, sniffio, certifi, attrs, outcome, webdriver-manager, trio, trio-websocket, selenium
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 0.58.0
    Uninstalling websocket-client-0.58.0:
      Successfully uninstalled websocket-client-0.58.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.1.31
    Uninstalling certifi-2025.1.31:
      Successfully uninstalled certifi-2025.1.31
  Attempting uninstall: attrs
    Found existing installation: attrs 22.1.0
    Uninstalling attrs-22.1.0:
      Successfully uninstalled attrs-22.1.0
Successfully installed attrs-26.1.0 certifi-2026.2.25 outcome-1.3.0.post0 selenium-4.43.0 sniffio-1.3.1 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 webdriver-manager-4.0.2 websocket-client-1.9.0 wsproto-1.3.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.29.76 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.6.3 which is incompatible.
spyder 5.4.3 requires jedi<0.19.0,>=0.17.2, but you have jedi 0.19.2 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
import time
import random
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import quote
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from queue import Queue

# ─────────────────────────────────────────────
# 1. 환경 변수 및 경로 설정
# ─────────────────────────────────────────────
load_dotenv()
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")
MASTER_PATH = "C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\전처리_EDA\\최종\\pos_data_food_final_상품단위_filtered.csv"
SUCCESS_PATH = "C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\seven_eleven_blog_reviews_success.csv"
FAIL_PATH = "C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\seven_eleven_blog_reviews_fail_v1.csv"
OUTPUT_PATH = 'C:\\Users\\alexj\\2026_캡스톤_디자인\\세븐일레븐_프로젝트\\세븐일레븐_내부데이터\\블로그_나머지상품_크롤링.csv'

# 동시 실행할 드라이버 수 (RAM 여유분 / 300MB 로 조절. 기본값 5)
DRIVER_COUNT = 5

# ───────────────────────────────────────────
# 2. 이어서 크롤링할 대상 추출
#    → 이미 FAIL / SUCCESS 파일에 기록된 검색어는 모두 제외
# ─────────────────────────────────────────────
def get_extra_target_items():
    print("수집 대상 아이템 분석 중...")
    # ── MASTER에서 전체 유니크 상품명 추출 ──────────────────
    df_master = pd.read_csv(MASTER_PATH, low_memory=False)
    master_items = set(df_master['상품명'].dropna().str.strip().unique())
    print(f"MASTER 전체 유니크 상품명: {len(master_items)}개")
    # ── 이미 크롤링 완료된 상품명 수집 (본문내용이 있는 경우만) ──
    done_items = set()
    for path, label in [(SUCCESS_PATH, 'success'), (FAIL_PATH, 'fail')]:
        if not os.path.exists(path):
            print(f"[{label}] 파일 없음, 스킵")
            continue
        df_temp = pd.read_csv(path, low_memory=False)
        if '검색어' not in df_temp.columns:
            print(f"[{label}] '검색어' 컬럼 없음, 스킵")
            continue
        # '본문내용'이 null이 아닌 것만 → 완료로 간주
        if '본문내용' in df_temp.columns:
            df_done = df_temp[df_temp['본문내용'].notna()]
        else:
            df_done = df_temp  # 컬럼 자체가 없으면 전부 완료로 간주
        items = (
            df_done['검색어']
            .dropna()
            .str.replace('세븐일레븐 ', '', n=1, regex=False)
            .str.strip()
        )
        done_items.update(items.tolist())
        print(f"[{label}] 완료 처리된 항목: {len(items)}개")
    print(f"총 완료(제외할) 항목 수: {len(done_items)}개")
    # ── MASTER 기준으로 남은 크롤링 대상 확정 ──────────────────
    df_remaining = df_master[
        df_master['상품명'].str.strip().isin(master_items - done_items)
    ][['상품중분류명', '상품명']].drop_duplicates()
    print(f"남은 크롤링 대상: {len(df_remaining)}개\n")
    return df_remaining.values.tolist()  # → [(카테고리, 상품명), ...] 튜플 리스트

# ─────────────────────────────────────────────
# 3. 드라이버 설정 (이미지/CSS/폰트 차단으로 로딩 가속)
# ─────────────────────────────────────────────
def setup_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--disable-extensions")
    chrome_options.add_argument("--dns-prefetch-disable")
    chrome_options.add_argument("--blink-settings=imagesEnabled=false")
    chrome_options.add_argument(
        "user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )
    chrome_options.add_experimental_option("prefs", {
        "profile.managed_default_content_settings.images": 2,      # 이미지 차단
        "profile.managed_default_content_settings.stylesheets": 2, # CSS 차단
        "profile.managed_default_content_settings.fonts": 2,       # 폰트 차단
    })

    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=chrome_options)


def create_driver_pool(n):
    """드라이버 n개를 Queue에 담아 반환"""
    pool = Queue()
    print(f"드라이버 {n}개 초기화 중...")
    for i in range(n):
        pool.put(setup_driver())
        print(f"  드라이버 {i+1}/{n} 준비 완료")
    return pool


# ─────────────────────────────────────────────
# 4. 블로그 본문 추출 (Selenium, 타임아웃 단축)
# ─────────────────────────────────────────────
def get_blog_content(driver, url):
    try:
        driver.get(url)
        wait = WebDriverWait(driver, 3)  # 5 → 3초
        wait.until(EC.presence_of_element_located((By.ID, "mainFrame")))
        driver.switch_to.frame("mainFrame")

        for selector in ["div.se-main-container", "div#postViewArea", "div.se-viewer"]:
            try:
                element = driver.find_element(By.CSS_SELECTOR, selector)
                text = element.text.strip()
                if text:
                    return text
            except:
                continue
        return "본문 추출 실패"
    except:
        return "크롤링 오류"
    finally:
        try:
            driver.switch_to.default_content()
        except:
            pass


# ─────────────────────────────────────────────
# 5. 상품 1개 처리 (스레드 단위 작업)
# ─────────────────────────────────────────────
def process_item(driver_pool, cat, item):
    driver = driver_pool.get()  # 드라이버 대여
    results = []

    try:
        item_str = str(item)
        search_query = item_str if "세븐일레븐" in item_str else f"세븐일레븐 {item_str}"

        api_url = (
            f"https://openapi.naver.com/v1/search/blog.json"
            f"?query={quote(search_query)}&display=3&sort=sim"
        )
        headers = {
            "X-Naver-Client-Id": CLIENT_ID,
            "X-Naver-Client-Secret": CLIENT_SECRET,
        }

        res = requests.get(api_url, headers=headers, timeout=5)

        if res.status_code == 200:
            blog_items = res.json().get('items', [])

            if not blog_items:
                results.append({
                    '중분류명': cat,
                    '검색어': search_query,
                    '블로그제목': '결과없음',
                    '블로그링크': '',
                    '본문내용': '',
                })
            else:
                for blog in blog_items:
                    title = BeautifulSoup(blog['title'], 'html.parser').get_text()
                    link = blog['link']
                    content = get_blog_content(driver, link)
                    results.append({
                        '중분류명': cat,
                        '검색어': search_query,
                        '블로그제목': title,
                        '블로그링크': link,
                        '본문내용': content,
                    })
                    time.sleep(random.uniform(0.5, 1.0))  # 기존 1~1.5 → 0.5~1.0
        else:
            tqdm.write(f"⚠️ API 호출 실패 (Code: {res.status_code}) - {item}")

    except Exception as e:
        tqdm.write(f"⚠️ 예외 발생: {e} - {item}")

    finally:
        driver_pool.put(driver)  # 드라이버 반납 (필수)

    return results


# ─────────────────────────────────────────────
# 6. 중간 저장 함수
# ─────────────────────────────────────────────
def flush_to_csv(buffer: list):
    if not buffer:
        return
    df_buf = pd.DataFrame(buffer)
    file_exists = os.path.exists(OUTPUT_PATH)
    df_buf.to_csv(
        OUTPUT_PATH,
        mode='a',
        index=False,
        header=not file_exists,   # 파일 없으면 헤더 포함, 있으면 생략
        encoding='utf-8-sig'
    )
    buffer.clear()


# ─────────────────────────────────────────────
# 7. 메인
# ─────────────────────────────────────────────
def main():
    if not CLIENT_ID or not CLIENT_SECRET:
        print("오류: .env 파일에 네이버 API Key가 필요합니다.")
        return

    # ── 이어서 할 대상 추출 ───────────────────────────
    target_items = get_extra_target_items()
    if not target_items:
        print("더 이상 크롤링할 새로운 아이템이 없습니다.")
        return

    print(f"🚀 크롤링 시작: {len(target_items)}개 상품\n")

    # ── 드라이버 풀 생성 ─────────────────────────────
    driver_pool = create_driver_pool(DRIVER_COUNT)
    buffer = []  # 임시 저장 버퍼

    try:
        with ThreadPoolExecutor(max_workers=DRIVER_COUNT) as executor:
            futures = {
                executor.submit(process_item, driver_pool, cat, item): (cat, item)
                for cat, item in target_items
            }

            for i, future in enumerate(
                tqdm(as_completed(futures), total=len(futures),
                     desc="크롤링 진행률", ncols=100), 1
            ):
                try:
                    buffer.extend(future.result())
                except Exception as e:
                    tqdm.write(f"⚠️ future 처리 중 오류: {e}")

                # 50개마다 디스크에 저장 (중단돼도 유실 최소화)
                if i % 50 == 0:
                    flush_to_csv(buffer)
                    tqdm.write(f"💾 중간 저장 완료 ({i}개 처리됨)")

    except KeyboardInterrupt:
        # Ctrl+C 로 중단해도 지금까지 모은 데이터 저장
        tqdm.write("\n⚠️ 사용자 중단 감지 — 현재까지 수집 데이터 저장 중...")

    finally:
        # 드라이버 전부 종료
        while not driver_pool.empty():
            try:
                driver_pool.get_nowait().quit()
            except:
                pass

        # 버퍼 잔여분 저장
        flush_to_csv(buffer)
        print(f"\n🎉 완료! 결과 누적 저장 위치: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()

수집 대상 아이템 분석 중...
MASTER 전체 유니크 상품명: 8118개
[success] 완료 처리된 항목: 3181개
[fail] 완료 처리된 항목: 8857개
총 완료(제외할) 항목 수: 4118개
남은 크롤링 대상: 4016개

🚀 크롤링 시작: 4016개 상품

드라이버 5개 초기화 중...
  드라이버 1/5 준비 완료
  드라이버 2/5 준비 완료
  드라이버 3/5 준비 완료
  드라이버 4/5 준비 완료
  드라이버 5/5 준비 완료

크롤링 진행률:   1%|▌                                           | 50/4016 [02:01<2:20:42,  2.13s/it]

💾 중간 저장 완료 (50개 처리됨)

크롤링 진행률:   2%|█                                          | 100/4016 [04:32<2:12:38,  2.03s/it]

💾 중간 저장 완료 (100개 처리됨)

크롤링 진행률:   4%|█▌                                         | 150/4016 [06:51<2:14:05,  2.08s/it]

💾 중간 저장 완료 (150개 처리됨)

크롤링 진행률:   5%|██▏                                        | 200/4016 [08:47<2:52:45,  2.72s/it]

💾 중간 저장 완료 (200개 처리됨)

크롤링 진행률:   6%|██▋                                        | 250/4016 [10:43<1:53:34,  1.81s/it]

💾 중간 저장 완료 (250개 처리됨)

크롤링 진행률:   7%|███▏                                       | 300/4016 [13:00<3:29:09,  3.38s/it]

💾 중간 저장 완료 (300개 처리됨)

크롤링 진행률:   9%|███▋                                       | 350/4016 [15:06<2:24:26,  2.36s/it]

💾 중간 저장 완료 (350개 처리됨)

크롤링 진행률:  10%|████▎                                      | 400/4016 [17:06<2:11:55,  2.19s/it]

💾 중간 저장 완료 (400개 처리됨)

크롤링 진행률:  11%|████▊                                      | 450/4016 [19:22<2:49:24,  2.85s/it]

💾 중간 저장 완료 (450개 처리됨)

크롤링 진행률:  12%|█████▎                                     | 500/4016 [22:01<2:56:06,  3.01s/it]

💾 중간 저장 완료 (500개 처리됨)

크롤링 진행률:  13%|██████                                       | 542/4016 [24:07<58:20,  1.01s/it]C:\Users\alexj\AppData\Local\Temp\ipykernel_14040\2946490626.py:174: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  title = BeautifulSoup(blog['title'], 'html.parser').get_text()
크롤링 진행률:  14%|█████▉                                     | 550/4016 [24:27<2:42:46,  2.82s/it]

💾 중간 저장 완료 (550개 처리됨)

크롤링 진행률:  15%|██████▍                                    | 600/4016 [26:35<2:24:09,  2.53s/it]

💾 중간 저장 완료 (600개 처리됨)

크롤링 진행률:  16%|██████▉                                    | 650/4016 [28:42<1:26:02,  1.53s/it]

💾 중간 저장 완료 (650개 처리됨)

크롤링 진행률:  17%|███████▌                                   | 701/4016 [31:32<1:33:22,  1.69s/it]

💾 중간 저장 완료 (700개 처리됨)

크롤링 진행률:  19%|████████                                   | 750/4016 [33:48<1:49:24,  2.01s/it]

💾 중간 저장 완료 (750개 처리됨)

크롤링 진행률:  20%|████████▌                                  | 800/4016 [35:42<2:36:50,  2.93s/it]

💾 중간 저장 완료 (800개 처리됨)

크롤링 진행률:  21%|█████████                                  | 850/4016 [38:44<1:31:28,  1.73s/it]

💾 중간 저장 완료 (850개 처리됨)

크롤링 진행률:  22%|█████████▋                                 | 900/4016 [41:23<2:30:04,  2.89s/it]

💾 중간 저장 완료 (900개 처리됨)

크롤링 진행률:  24%|██████████▏                                | 950/4016 [44:05<4:23:26,  5.16s/it]

💾 중간 저장 완료 (950개 처리됨)

크롤링 진행률:  25%|██████████▍                               | 1000/4016 [46:30<2:30:06,  2.99s/it]

💾 중간 저장 완료 (1000개 처리됨)

크롤링 진행률:  26%|██████████▉                               | 1050/4016 [49:20<3:04:03,  3.72s/it]

💾 중간 저장 완료 (1050개 처리됨)

크롤링 진행률:  27%|███████████▌                              | 1100/4016 [52:05<3:00:25,  3.71s/it]

💾 중간 저장 완료 (1100개 처리됨)

크롤링 진행률:  29%|████████████                              | 1150/4016 [54:37<2:01:17,  2.54s/it]

💾 중간 저장 완료 (1150개 처리됨)

크롤링 진행률:  30%|████████████▌                             | 1200/4016 [56:53<2:20:57,  3.00s/it]

💾 중간 저장 완료 (1200개 처리됨)

크롤링 진행률:  31%|█████████████                             | 1250/4016 [59:08<2:09:17,  2.80s/it]

💾 중간 저장 완료 (1250개 처리됨)

크롤링 진행률:  32%|████████████▉                           | 1300/4016 [1:01:39<3:35:27,  4.76s/it]

💾 중간 저장 완료 (1300개 처리됨)

크롤링 진행률:  34%|█████████████▍                          | 1350/4016 [1:03:40<1:38:18,  2.21s/it]

💾 중간 저장 완료 (1350개 처리됨)

크롤링 진행률:  35%|█████████████▉                          | 1400/4016 [1:06:14<2:05:51,  2.89s/it]

💾 중간 저장 완료 (1400개 처리됨)

크롤링 진행률:  36%|██████████████▍                         | 1450/4016 [1:08:40<2:26:22,  3.42s/it]

💾 중간 저장 완료 (1450개 처리됨)

크롤링 진행률:  37%|██████████████▉                         | 1500/4016 [1:10:53<1:55:08,  2.75s/it]

💾 중간 저장 완료 (1500개 처리됨)

크롤링 진행률:  39%|███████████████▍                        | 1550/4016 [1:12:58<1:48:45,  2.65s/it]

💾 중간 저장 완료 (1550개 처리됨)

크롤링 진행률:  40%|███████████████▉                        | 1600/4016 [1:15:15<1:27:34,  2.18s/it]

💾 중간 저장 완료 (1600개 처리됨)

크롤링 진행률:  41%|█████████████████▎                        | 1650/4016 [1:17:22<29:23,  1.34it/s]

💾 중간 저장 완료 (1650개 처리됨)

크롤링 진행률:  42%|████████████████▉                       | 1700/4016 [1:19:36<2:32:34,  3.95s/it]

💾 중간 저장 완료 (1700개 처리됨)

크롤링 진행률:  44%|█████████████████▍                      | 1750/4016 [1:21:31<1:03:34,  1.68s/it]

💾 중간 저장 완료 (1750개 처리됨)

크롤링 진행률:  45%|█████████████████▉                      | 1799/4016 [1:23:25<2:08:24,  3.48s/it]

💾 중간 저장 완료 (1800개 처리됨)

크롤링 진행률:  46%|██████████████████▍                     | 1850/4016 [1:25:38<1:40:38,  2.79s/it]

💾 중간 저장 완료 (1850개 처리됨)

크롤링 진행률:  47%|██████████████████▉                     | 1900/4016 [1:27:37<1:17:26,  2.20s/it]

💾 중간 저장 완료 (1900개 처리됨)

크롤링 진행률:  49%|███████████████████▍                    | 1950/4016 [1:29:36<1:08:41,  1.99s/it]

💾 중간 저장 완료 (1950개 처리됨)

크롤링 진행률:  50%|███████████████████▉                    | 2000/4016 [1:31:34<1:31:27,  2.72s/it]

💾 중간 저장 완료 (2000개 처리됨)

크롤링 진행률:  51%|█████████████████████▍                    | 2050/4016 [1:33:26<58:15,  1.78s/it]

💾 중간 저장 완료 (2050개 처리됨)

크롤링 진행률:  52%|████████████████████▉                   | 2100/4016 [1:35:40<1:06:16,  2.08s/it]

💾 중간 저장 완료 (2100개 처리됨)

크롤링 진행률:  54%|█████████████████████▍                  | 2149/4016 [1:37:40<1:23:11,  2.67s/it]

💾 중간 저장 완료 (2150개 처리됨)

크롤링 진행률:  55%|█████████████████████▉                  | 2200/4016 [1:39:41<1:55:33,  3.82s/it]

💾 중간 저장 완료 (2200개 처리됨)

크롤링 진행률:  56%|██████████████████████▍                 | 2250/4016 [1:41:38<1:04:27,  2.19s/it]

💾 중간 저장 완료 (2250개 처리됨)

크롤링 진행률:  57%|████████████████████████                  | 2300/4016 [1:43:28<56:05,  1.96s/it]

💾 중간 저장 완료 (2300개 처리됨)

크롤링 진행률:  59%|████████████████████████▌                 | 2350/4016 [1:45:32<36:29,  1.31s/it]

💾 중간 저장 완료 (2350개 처리됨)

크롤링 진행률:  60%|███████████████████████▉                | 2400/4016 [1:47:51<1:41:41,  3.78s/it]

💾 중간 저장 완료 (2400개 처리됨)

크롤링 진행률:  61%|█████████████████████████▋                | 2451/4016 [1:49:54<52:13,  2.00s/it]

💾 중간 저장 완료 (2450개 처리됨)

크롤링 진행률:  62%|████████████████████████▉               | 2500/4016 [1:51:40<1:01:43,  2.44s/it]

💾 중간 저장 완료 (2500개 처리됨)

크롤링 진행률:  63%|█████████████████████████▍              | 2550/4016 [1:53:33<1:04:06,  2.62s/it]

💾 중간 저장 완료 (2550개 처리됨)

크롤링 진행률:  65%|█████████████████████████▉              | 2600/4016 [1:55:41<1:23:52,  3.55s/it]

💾 중간 저장 완료 (2600개 처리됨)

크롤링 진행률:  66%|███████████████████████████▋              | 2650/4016 [1:57:31<53:23,  2.35s/it]

💾 중간 저장 완료 (2650개 처리됨)

크롤링 진행률:  67%|████████████████████████████▏             | 2700/4016 [1:59:17<48:59,  2.23s/it]

💾 중간 저장 완료 (2700개 처리됨)

크롤링 진행률:  68%|████████████████████████████▊             | 2750/4016 [2:01:09<56:43,  2.69s/it]

💾 중간 저장 완료 (2750개 처리됨)

크롤링 진행률:  70%|█████████████████████████████▎            | 2800/4016 [2:03:21<58:54,  2.91s/it]

💾 중간 저장 완료 (2800개 처리됨)

크롤링 진행률:  71%|█████████████████████████████▊            | 2850/4016 [2:04:56<37:30,  1.93s/it]

💾 중간 저장 완료 (2850개 처리됨)

크롤링 진행률:  72%|██████████████████████████████▎           | 2900/4016 [2:06:40<17:32,  1.06it/s]

💾 중간 저장 완료 (2900개 처리됨)

크롤링 진행률:  73%|██████████████████████████████▊           | 2950/4016 [2:08:45<49:27,  2.78s/it]

💾 중간 저장 완료 (2950개 처리됨)

크롤링 진행률:  75%|█████████████████████████████▉          | 3000/4016 [2:10:46<1:10:09,  4.14s/it]

💾 중간 저장 완료 (3000개 처리됨)

크롤링 진행률:  76%|███████████████████████████████▉          | 3050/4016 [2:12:23<36:41,  2.28s/it]

💾 중간 저장 완료 (3050개 처리됨)

크롤링 진행률:  77%|████████████████████████████████▍         | 3100/4016 [2:14:17<24:43,  1.62s/it]

💾 중간 저장 완료 (3100개 처리됨)

크롤링 진행률:  78%|████████████████████████████████▉         | 3150/4016 [2:15:53<18:21,  1.27s/it]

💾 중간 저장 완료 (3150개 처리됨)

크롤링 진행률:  80%|█████████████████████████████████▍        | 3200/4016 [2:18:09<48:45,  3.59s/it]

💾 중간 저장 완료 (3200개 처리됨)

크롤링 진행률:  81%|█████████████████████████████████▉        | 3250/4016 [2:20:07<15:17,  1.20s/it]

💾 중간 저장 완료 (3250개 처리됨)

크롤링 진행률:  82%|██████████████████████████████████▌       | 3301/4016 [2:22:14<15:34,  1.31s/it]

💾 중간 저장 완료 (3300개 처리됨)

크롤링 진행률:  83%|███████████████████████████████████       | 3350/4016 [2:24:08<17:25,  1.57s/it]

💾 중간 저장 완료 (3350개 처리됨)

크롤링 진행률:  85%|███████████████████████████████████▌      | 3400/4016 [2:25:59<26:43,  2.60s/it]

💾 중간 저장 완료 (3400개 처리됨)

크롤링 진행률:  86%|████████████████████████████████████      | 3450/4016 [2:27:51<21:51,  2.32s/it]

💾 중간 저장 완료 (3450개 처리됨)

크롤링 진행률:  87%|████████████████████████████████████▌     | 3500/4016 [2:29:50<11:41,  1.36s/it]

💾 중간 저장 완료 (3500개 처리됨)

크롤링 진행률:  88%|█████████████████████████████████████▏    | 3550/4016 [2:31:48<23:27,  3.02s/it]

💾 중간 저장 완료 (3550개 처리됨)

크롤링 진행률:  90%|█████████████████████████████████████▋    | 3600/4016 [2:33:30<11:51,  1.71s/it]

💾 중간 저장 완료 (3600개 처리됨)

크롤링 진행률:  91%|██████████████████████████████████████▏   | 3650/4016 [2:35:29<13:38,  2.24s/it]

💾 중간 저장 완료 (3650개 처리됨)

크롤링 진행률:  92%|██████████████████████████████████████▋   | 3700/4016 [2:37:21<14:19,  2.72s/it]

💾 중간 저장 완료 (3700개 처리됨)

크롤링 진행률:  93%|███████████████████████████████████████▏  | 3750/4016 [2:39:05<11:34,  2.61s/it]

💾 중간 저장 완료 (3750개 처리됨)

크롤링 진행률:  95%|███████████████████████████████████████▋  | 3800/4016 [2:40:43<05:51,  1.63s/it]

💾 중간 저장 완료 (3800개 처리됨)

크롤링 진행률:  96%|████████████████████████████████████████▎ | 3850/4016 [2:42:42<03:37,  1.31s/it]

💾 중간 저장 완료 (3850개 처리됨)

크롤링 진행률:  97%|████████████████████████████████████████▊ | 3900/4016 [2:44:20<03:47,  1.96s/it]

💾 중간 저장 완료 (3900개 처리됨)

크롤링 진행률:  98%|█████████████████████████████████████████▎| 3950/4016 [2:46:22<01:15,  1.15s/it]

💾 중간 저장 완료 (3950개 처리됨)

크롤링 진행률: 100%|█████████████████████████████████████████▊| 4000/4016 [2:48:26<00:29,  1.86s/it]

💾 중간 저장 완료 (4000개 처리됨)

크롤링 진행률: 100%|██████████████████████████████████████████| 4016/4016 [2:49:03<00:00,  2.53s/it]

🎉 완료! 결과 누적 저장 위치: C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\블로그_나머지상품_크롤링.csv

In [2]:
df_rest = pd.read_csv(r'C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\블로그_나머지상품_크롤링.csv')
print(df_rest.shape)
df_rest.head()

(11011, 5)

,중분류명,검색어,블로그제목,블로그링크,본문내용
0,고급,세븐일레븐 G)크라시에유자셔벗140ml,세븐일레븐 아이스크림 크라시에 유자셔벗,https://blog.naver.com/osolo123/223862672512,좋은하루 보내셨나요?\n길을 걷다가 디저트가\n먹고 싶더라고요 ㅋ ㅋ\n날씨도 덥고...
1,가공우유,세븐일레븐 뉴초이스)아쌈밀크티300ml,[찐후기] ASSAM 아쌈 밀크티 세븐일레븐,https://blog.naver.com/namunorae/223285206929,안녕하세요\n오늘의 [ #찐후기 ]는\n#편의점 #음료수 찐후기입니다\n(모든 찐후...
2,가공우유,세븐일레븐 뉴초이스)아쌈밀크티300ml,세븐일레븐 아쌈 밀크티 이거 뭐지? 맛은 솔직히 말하면,https://blog.naver.com/memory_mj0329/224140125473,세븐일레븐에서 뭐 마실 거 없나 보다가\n괜히 밀크티가 땡겨서 하나 집어 들었다.\...
3,가공우유,세븐일레븐 뉴초이스)아쌈밀크티300ml,일본 세븐일레븐 편의점 홍차 밀크티 머신 자판기,https://blog.naver.com/areacorea/224105382748,일본 세븐일레븐 편의점 홍차 밀크티 머신 자판기\n글/ 나그네제이 사진/ 버선언니\...
4,국산맥주,세븐일레븐 오비)카스500ml캔,MLB 월드투어 서울시리즈 굿즈 오비맥주 카스 500ml 맥주잔...,https://blog.naver.com/oisuloi/223385089447,메이저리그 개막전 서울시리즈가\n이번주 핫한 키워드네요.\n전설적인 LA다저스 팀과...

In [3]:
df_rest.isnull().sum()

중분류명       0
검색어        0
블로그제목      0
블로그링크    380
본문내용     380
dtype: int64

In [7]:
df_rest[df_rest['본문내용'].isnull()]['검색어'].unique()

array(['세븐일레븐 롯데)자일리톨F24g', '세븐일레븐 동아)박카스F120ml',
       '세븐일레븐 훼밀리)복숭아무케루푸루푸루구미40g', '세븐일레븐 현대)미에로화이바350ml',
       '세븐일레븐 에프투)두레미니족발400g', '세븐일레븐 26년)얼음컵(벤티)', '세븐일레븐 아미)얼음컵(그란데)',
       '세븐일레븐 26년)얼음컵(그란데)', '세븐일레븐 제스)오레오바닐라바92ml', '세븐일레븐 오리온)초코송이4P',
       '세븐일레븐 MZ)호올스자몽27.9g', '세븐일레븐 해태)홈런볼128g', '세븐일레븐 썬푸드)오잉츄40g',
       '세븐일레븐 그래)여명808140ml', '세븐일레븐 현대)미에로화이바210ml', '세븐일레븐 유앤)쌀강정80g',
       '세븐일레븐 MQ)켈로그단백질바K50g', '세븐일레븐 현대)미에로화이바스파클링350ml',
       '세븐일레븐 빙그레)폴라포스포츠Zero120ml', '세븐일레븐 훼미리)아폴로35g',
       '세븐일레븐 MZ)호올스멘토립토스27.9g', '세븐일레븐 올리)순얼음3kg',
       '세븐일레븐 MDS)NEW투움바파스타230g', '세븐일레븐 쥬맥스)랭거스(망고)449ml',
       '세븐일레븐 예스)지렁이젤리샤우워', '세븐일레븐 직납)트롤리구미샤크100g', '세븐일레븐 쥬맥스)모구모구(멜론)',
       '세븐일레븐 유한)내일N100ml', '세븐일레븐 호연)꿀물180ml', '세븐일레븐 하겐)마카롱블루베리바',
       '세븐일레븐 일신)푸쉬팝', '세븐일레븐 매크로)파인아메캔디108.1g',
       '세븐일레븐 이노엔)티로그자두아이스티500ml', '세븐일레븐 현대)미에로화이바100ml',
       '세븐일레븐 MZ)밀카레오33g', '세븐일레븐 예스)트롤리XXL버거50g', '세븐일레븐 PB)참징어1마리60g',
       '세븐일레븐 일신)푸시팝플립앤딥25g', '세븐일레븐 엔제이)앙도넛100g', '세븐일레븐 시원)자두야핸드폰캔디12g',
       '세븐일레븐 PB)착한비스킷소보로66g', '세븐일레븐 오뚜기)황도400g',
       '세븐일레븐 미스티)산리오자판기캔디30g', '세븐일레븐 쥬맥스)애리조나그린티진생650ml',
       '세븐일레븐 선우)치콜라타피스타치오80g', '세븐일레븐 큐피트)밭두렁45g',
       '세븐일레븐 삼경)필러즈미스터리큐브46g', '세븐일레븐 큐피트)꾀돌이45g', '세븐일레븐 네슬레)다막바클라바60G',
       '세븐일레븐 올리)순얼음1kg', '세븐일레븐 그린)29피자벅', '세븐일레븐 해태)락맛동산165g',
       '세븐일레븐 나무)워헤드올믹스드업젤리45g', '세븐일레븐 썬푸드)실속삼색오징어75g',
       '세븐일레븐 오리온)비쵸비5P', '세븐일레븐 배상면)산사춘300ml',
       '세븐일레븐 MDS)NEW베이컨까르보나라230g', '세븐일레븐 PB)리얼딸기앙모스160g',
       '세븐일레븐 비비통)렌지뽀글이', '세븐일레븐 훼밀리)BBQ롤젤리15g', '세븐일레븐 몽뜨)추억의쫀디기',
       '세븐일레븐 농심)고구마깡83g', '세븐일레븐 훼밀리)포도무케루푸루푸루구미40g',
       '세븐일레븐 일신)쥬시드롭디퍼즈96g', '세븐일레븐 동원)불참치90g',
       '세븐일레븐 훼밀리)사과무케루푸루푸루구미40g', '세븐일레븐 삼양)사또밥67g', '세븐일레븐 슬러피1200(R)',
       '세븐일레븐 페르)말리부200ml페트', '세븐일레븐 거림)주당비책100ml',
       '세븐일레븐 제이탑)불빛팽이프로펠러6g', '세븐일레븐 훈스)롱피자페파로니120g',
       '세븐일레븐 대림)크라비아180g(90gx2)', '세븐일레븐 제스)픽스타치오제로바80ml',
       '세븐일레븐 대상)아르포텐100ml', '세븐일레븐 PKJ)추억의팝콘강냉이300g',
       '세븐일레븐 오리온)헤피베리다쿠아즈8p', '세븐일레븐 본죽)야채죽270g',
       '세븐일레븐 그레)비달롤라벨타콜라향20g', '세븐일레븐 장성)원글라스까버네100ml',
       '세븐일레븐 끌레도르)더단백바카라멜85ml', '세븐일레븐 효성)옥수수쫀드기(3겹)88g',
       '세븐일레븐 리커)알카까베네쇼비뇽750ml', '세븐일레븐 효자원)서주아이스크림',
       '세븐일레븐 선우)도라에몽참악세서리젤리20g', '세븐일레븐 G)크라시에청포도셔벗140ml',
       '세븐일레븐 효성)호박쫀드기(3겹)88g', '세븐일레븐 미정)얼음동동물냉면245g',
       '세븐일레븐 유앤)크리스피초코봉12g', '세븐일레븐 홍선)쇠고기육포채16g', '세븐일레븐 에프비)후룻엔젤파인75g',
       '세븐일레븐 CW)칸테라까버네쇼비뇽750ml', '세븐일레븐 유로)에스프레소(샷추가)',
       '세븐일레븐 MH)샹동가든스프리츠750ml', '세븐일레븐 쥬맥스)애리조나레몬650ml',
       '세븐일레븐 디앤피스)볼스핑크자몽', '세븐일레븐 제이탑)망고파르페85g', '세븐일레븐 오뚜기)백도400g',
       '세븐일레븐 대광)찰진순대273g', '세븐일레븐 델리팜)앤디스초콜릿토피132g', '세븐일레븐 태웅)레모나340ml',
       '세븐일레븐 페르)깔루아200ml', '세븐일레븐 G)파스키에브레첼270g', '세븐일레븐 풀무원)생칼국수600g',
       '세븐일레븐 수리아)사와준마이10.5 900ml', '세븐일레븐 나무)빵빵이DIY솜사탕11g',
       '세븐일레븐 아영)우르바노750ml', '세븐일레븐 CW)리베라까버네쇼비뇽750ml',
       '세븐일레븐 에이원)스위트롤리팝', '세븐일레븐 올리)리유저블얼음컵230g',
       '세븐일레븐 씨믹스)공룡(다이노)젤리11g', '세븐일레븐 지비)보발로사로제750ml',
       '세븐일레븐 해태)자일리톨은단청용기90g', '세븐일레븐 SAMG)캐치티니핑요술봉10g',
       '세븐일레븐 고운벗)샤비파인애플비스킷', '세븐일레븐 우진)루첸테 750ml', '세븐일레븐 ★여리수)엔드리스하트',
       '세븐일레븐 PB)한돈햄200g', '세븐일레븐 스위트)트롤리어드벤트캘린더603g',
       '세븐일레븐 MZ)호올스멘토립터스쉐어백140g', '세븐일레븐 피치)크리스피콘스낵60g',
       '세븐일레븐 유앤)쫀득레인보우마시멜로우150g', '세븐일레븐 밀팜)39초코스콘슈120g',
       '세븐일레븐 현대)미에로화이바100ml10입', '세븐일레븐 아미)컵얼음(레귤러)', '세븐일레븐 지비)오퍼링',
       '세븐일레븐 코코)몰랑캔디콤팩트9g', '세븐일레븐 디앤피스)글랜로티스12년', '세븐일레븐 ★미루)물망초',
       '세븐일레븐 글로브)버큇칩매콤280g', '세븐일레븐 시원)불빛팽이UFO8g',
       '세븐일레븐 직납)트롤리옥토푸스100g', '세븐일레븐 유앤)짱구낮잠말랑이12g', '세븐일레븐 풀무원)생쫄면 2인분',
       '세븐일레븐 ★미루)원형부케', '세븐일레븐 에이트)스트라이킹금박스티커캔', '세븐일레븐 제이)화이트맥케이트리플머쳐드',
       '세븐일레븐 선우)가락엿30g', '세븐일레븐 엔제이)머그컵카스테라볼90g',
       '세븐일레븐 태웅)아샷추복숭아제로320ml', '세븐일레븐 ★미루)로즈마리(소)', '세븐일레븐 ★미루)골드벨(소)',
       '세븐일레븐 ★미루)빅하트', '세븐일레븐 ★미루)골드벨(대)', '세븐일레븐 현대)미에로화이바20입',
       '세븐일레븐 ★여리수)피규어디스펜서', '세븐일레븐 엔제이)카바야염분캔디81g', '세븐일레븐 ★해광)포켓부케',
       '세븐일레븐 ★미루)모나리자', '세븐일레븐 델리팜)투시버킷믹스255g', '세븐일레븐 ★미루)하트캔',
       '세븐일레븐 아영)M750ml(by빌라엠)', '세븐일레븐 조닌프로세코750ml', '세븐일레븐 M_맥키스333ml',
       '세븐일레븐 TDF)생미쉘초코도넛180g', '세븐일레븐 아미)얼음컵(레귤러)',
       '세븐일레븐 디핀)다츠앤체리바75ml', '세븐일레븐 제이스)발두지리제르바까버네750',
       '세븐일레븐 SAMG)캐치캐치비타씨44g', '세븐일레븐 몽뜨)맛기차콘84g',
       '세븐일레븐 에이트)뮤스트라이킹블루베리맛', '세븐일레븐 APP전용)럭히밥함박킹버거',
       '세븐일레븐 코코)몰랑이아크릴스탠드9g', '세븐일레븐 직납)아이스도넛', '세븐일레븐 페르)비피터700ml',
       '세븐일레븐 ★미루)베스트바구니 ', '세븐일레븐 유앤)포켓몬안전호루라기10g', '세븐일레븐 여리수)빼빼로9입캐리어',
       '세븐일레븐 에이트)도라에몽판박이젤리50g', '세븐일레븐 우진)에푸2021',
       '세븐일레븐 M_니혼사카리)혼죠조나마겐슈', '세븐일레븐 ★여리수)지관바구니25000',
       '세븐일레븐 SF9화보매거진기획set', '세븐일레븐 아영)비알레또로쏘750ml',
       '세븐일레븐 담터)콤부차라임10T(팽돌이)', '세븐일레븐 M_로아커웨하스쿼드라티니다크초',
       '세븐일레븐 롯데)알바리까버네쇼비뇽187ml', '세븐일레븐 미스티)BT21스핀피즈1.5g',
       '세븐일레븐 고운벗)크룽지18g', '세븐일레븐 유앤)포켓몬비타톤멀티비타캔디', '세븐일레븐 ★여리수)기프트머그컵',
       '세븐일레븐 예스)트롤리우주젤리19g', '세븐일레븐 유앤)플리퍼즈(LOL)6.3g',
       '세븐일레븐 디앤피스)바카리삼부카', '세븐일레븐 프로엠)트윙클다이아set', '세븐일레븐 제이탑)NEW미니전자총4g',
       '세븐일레븐 코코)몰랑이세탁기캔디15g', '세븐일레븐 코코)먼작귀캔디스탬프9g', '세븐일레븐 풀무원)생소면600g',
       '세븐일레븐 빵빵이캐리어(단품)', '세븐일레븐 빙그레)쿠앤크바 카라멜70ml', '세븐일레븐 효성)가평잣가락엿35g',
       '세븐일레븐 M_직납)끌치즈레몬바', '세븐일레븐 레뱅드)마시깜포피오린750ml',
       '세븐일레븐 APP)휴잇슨건메탈리슬링', '세븐일레븐 디아)텐커레이넘버텐700ml',
       '세븐일레븐 드링크)임페리얼12년450ml', '세븐일레븐 스타벅스파이크플_ICE(PB얼음컵)',
       '세븐일레븐 미스티)포켓몬스핀피즈1.5g', '세븐일레븐 시원)대교알루자동차8g', '세븐일레븐 M_다이긴죠나마겐슈',
       '세븐일레븐 대명)고래밥(휴)', '세븐일레븐 선우)콘젤리100g', '세븐일레븐 롯데)바이파뚜프레피노누아',
       '세븐일레븐 한국술)담솔375ml', '세븐일레븐 PKJ)크리스탈민트캔디72g', '세븐일레븐 직납)요구르트바',
       '세븐일레븐 레뱅드)요리오750ml', '세븐일레븐 나무)캐치티니핑쥬얼핑보석함',
       '세븐일레븐 선우)말랑이(토끼&개구리)21g', '세븐일레븐 파이)초코리치바70ml', '세븐일레븐 제이)달모어15년',
       '세븐일레븐 M_비바에스파냐레드750ml', '세븐일레븐 디핀)다두블랙콘150g',
       '세븐일레븐 디앤피스)하일랜드파크12년', '세븐일레븐 M_직납)쿠키오민트', '세븐일레븐 직납)연유콘',
       '세븐일레븐 직납)서주커스터드콘', '세븐일레븐 하늘)순고칩70g', '세븐일레븐 M_직납)빅구슬스크류',
       '세븐일레븐 이델리)붕어빵(단팥슈크림)65g', '세븐일레븐 M_직납)서주캔디바닐라',
       '세븐일레븐 APP)밀담52도360ml', '세븐일레븐 페르)몰피진레몬700ml',
       '세븐일레븐 레뱅드)부띠노샴페인기라포르주', '세븐일레븐 마즈)엠앤엠즈머그컵set(옐로)',
       '세븐일레븐 청솔)지리산꿀물120ml', '세븐일레븐 에이플)포켓몬핑거보드10g',
       '세븐일레븐 유앤)티니핑롤러스탬프15g', '세븐일레븐 장안)캐치티니핑사과200ml',
       '세븐일레븐 블루밍)러그(단품)', '세븐일레븐 아영)빌라M750', '세븐일레븐 롯데)아맛나80ml',
       '세븐일레븐 문경)조지아180ml', '세븐일레븐 M_양갱바', '세븐일레븐 MZ)호올스자몽',
       '세븐일레븐 금양)글루바인1000ml', '세븐일레븐 리커)제네시스메를로750ml', '세븐일레븐 샤또에메750ml',
       '세븐일레븐 신세계)콤럼비아크레스트까쇼', '세븐일레븐 디핀)다두블루콘150g', '세븐일레븐 디앤피스)볼스 카시스',
       '세븐일레븐 신세계)투핸즈섹시비스트', '세븐일레븐 직납)요거팝초코볼바1200',
       '세븐일레븐 APP)이탈리쿠스 700ml', '세븐일레븐 천하)나트라커피트러플150g',
       '세븐일레븐 레뱅드)상그리아프리산떼275ml', '세븐일레븐 살리솔)칵테일넛50g',
       '세븐일레븐 리커)토마스파클링750ml', '세븐일레븐 청정)말랑말랑한글젤리66g', '세븐일레븐 직납)피스타쵸바',
       '세븐일레븐 레뱅드)도메니꼬끌레리꼬750ml', '세븐일레븐 APP)아방가르데',
       '세븐일레븐 디아)텐커레이 750ml', '세븐일레븐 더동진)참징어1마리60g', '세븐일레븐 선우)풍선부는공룡20g',
       '세븐일레븐 M_빙그레)카페오레바', '세븐일레븐 직납)초코멜로바', '세븐일레븐 알엔디)초코에몽초코쭈쭈바130ml',
       '세븐일레븐 레뱅드)버블넘버원로제750ml', '세븐일레븐 직납)깐도리', '세븐일레븐 정지선)어향육사덮밥295g',
       '세븐일레븐 인스터)모짜르트하우스레드187ml', '세븐일레븐 한국술)솔송주375ml',
       '세븐일레븐 M_비달)베지마시멜로우150g', '세븐일레븐 마즈)몰티저스카랴멜골드버켓', '세븐일레븐 ★초코폴러브유',
       '세븐일레븐 아영)바독까버네', '세븐일레븐 직납)요구르트차', '세븐일레븐 ★여리수)부엉이저금통',
       '세븐일레븐 대성)순유유밀키앙꼬팡(천등산)', '세븐일레븐 M_쥬시쿨자두소', '세븐일레븐 아미)순웰빙얼음3kg',
       '세븐일레븐 직납)모히또바', '세븐일레븐 직납)아이스자두', '세븐일레븐 M_씨제이)자른햇당면300g',
       '세븐일레븐 ★미루)캔디손가방', '세븐일레븐 롯데)거북이바90ml', '세븐일레븐 씨믹스)과일모양롤리팝26g',
       '세븐일레븐 CSR)아다라스칼리조750ml', '세븐일레븐 델토리)빅먹태리아나쵸칩300g',
       '세븐일레븐 APP)하쿠시카쿠로마츠쥰마이모찌요단', '세븐일레븐 광동)경옥진100ml',
       '세븐일레븐 롯데)알바리쉬라즈템프라187ml', '세븐일레븐 롯데)거북알130ml',
       '세븐일레븐 APP)메종카스텔메를로750ml', '세븐일레븐 마다마)올리브30g',
       '세븐일레븐 APP)타케츠루퓨어몰트', '세븐일레븐 직납)초코에몽모나카', '세븐일레븐 조닌끼안티750ml',
       '세븐일레븐 APP)보르고산레오로쏘750ml', '세븐일레븐 드림)젤리밤50g',
       '세븐일레븐 삼립)미국식콥샐러드178g', '세븐일레븐 대한)산토리나짱오렌지425ml',
       '세븐일레븐 PB)달고나24g', '세븐일레븐 훈스)콘버터&소시지핫도그145g',
       '세븐일레븐 삼경)리콜라아이시멘톨31g', '세븐일레븐 이정후)후스틱55g',
       '세븐일레븐 동아)박카스F120ml10입(판매전용) ', '세븐일레븐 SAMG)하츄핑의반지캔디13g',
       '세븐일레븐 빙그레)까페오레75ml', '세븐일레븐 에이스)경주빵32g', '세븐일레븐 대한)산토리나짱사과425ml',
       '세븐일레븐 로투스)비스코프37.5g', '세븐일레븐 나무)워헤즈사우어밤50g', '세븐일레븐 PB)초코별말차별60g',
       '세븐일레븐 하림)볶짜면큰컵', '세븐일레븐 쥬맥스)카나비스250ml', '세븐일레븐 스위트)부르봉루몽드크레페88g',
       '세븐일레븐 아띠)다네시타버터쿠키340g', '세븐일레븐 스윗)콘톡톡콤비네이션피자랩105g',
       '세븐일레븐 코주부)맛다리20g', '세븐일레븐 효성)미니언즈페즈캔디25.5g', '세븐일레븐 ★미루)토이페페',
       '세븐일레븐 엔제이)타쿠미야딸기타르트144g', '세븐일레븐 던_오리온)리찌알맹이6P',
       '세븐일레븐 ★미루)러브밸리즈', '세븐일레븐 삼립)꿀고물렛75g', '세븐일레븐 7P)요세미티로드샤도네이750ml',
       '세븐일레븐 롯데)K빈트너스샤롯데750ml', '세븐일레븐 ★미루)큐리티러브', '세븐일레븐 ★미루)사랑비',
       '세븐일레븐 고운벗)너즈캔디14g', '세븐일레븐 ★몽뜨)하트베어', '세븐일레븐 ★미루)로즈원',
       '세븐일레븐 던_오리온)다쿠아즈8P', '세븐일레븐 시원)캐쳐크레인10g', '세븐일레븐 ★미루)파스텔페페',
       '세븐일레븐 ★몽뜨)초코폴러브유', '세븐일레븐 던_오리온)키위알맹이6P', '세븐일레븐 ★몽뜨)앤틱스타',
       '세븐일레븐 ★몽뜨)베이직러브', '세븐일레븐 던_오리온)자두알맹이6P', '세븐일레븐 걸프)펩시(레귤러)',
       '세븐일레븐 선진)군밤츄(휴)', '세븐일레븐 CSR)아다라스알데아750ml', '세븐일레븐 직납)망설임',
       '세븐일레븐 스위트)25년어드벤트캘린더632g', '세븐일레븐 에이블)명가꽈배기(참깨맛)500g',
       '세븐일레븐 해태)아이비58g', '세븐일레븐 H직납)에이스', '세븐일레븐 직납)허쉬초코앤크림콘',
       '세븐일레븐 직납)빵또아티라미수', '세븐일레븐 ★몽뜨)보고타', '세븐일레븐 아포틱인페르노750ml',
       '세븐일레븐 에이블)카피바라금고저금통캔디', '세븐일레븐 ★미루)베스트바구니', '세븐일레븐 ★미루)사랑의프로포즈',
       '세븐일레븐 직납)구슬아이스크림', '세븐일레븐 걸프)펩시(라지)', '세븐일레븐 M_부르스터스)오레오',
       '세븐일레븐 APP)페나솔블랑코1L', '세븐일레븐 CSR)샴페인쟈끄송디지테레루즈',
       '세븐일레븐 페르)마르텔VSOP레드700ml', '세븐일레븐 페르)임페리얼17년트리플450ml',
       '세븐일레븐 디앤피스)페이머스그라우스700ml', '세븐일레븐 디아)베일리스350ml',
       '세븐일레븐 H직납)크라운산도크림', '세븐일레븐 H직납)쵸코하임(대)', '세븐일레븐 트롤리캐터필터100g',
       '세븐일레븐 APP)하리보어드밴트캘린더309g', '세븐일레븐 M_오프룻)블루베리',
       '세븐일레븐 페르)페리에주엘에포크로제', '세븐일레븐 하리보)해리포터3종덤프빈',
       '세븐일레븐 M_흥선)BBQ마쉬멜로우225g', '세븐일레븐 직납)롤링바', '세븐일레븐 카르멘멜롯750ml',
       '세븐일레븐 M_쥬시쿨복숭아소', '세븐일레븐 M_부르스터스)바닐라', '세븐일레븐 종가)파김치2.5kg',
       '세븐일레븐 APP)해지람480ml', '세븐일레븐 APP)캡틴모건오리지널스파이스럼',
       '세븐일레븐 코피코카푸치노캔디봉(휴)', '세븐일레븐 지비)파니케이아조진판델18', '세븐일레븐 제라헌스페셜세트',
       '세븐일레븐 여리수)키도크래커샌드90g', '세븐일레븐 직납)천혜향바', '세븐일레븐 지비)탈마템프라니요750ml',
       '세븐일레븐 직납)시모나바밤바'], dtype=object)

In [9]:
import os
import pandas as pd

# ── 경로 설정 ──────────────────────────────────────────────────────────
MASTER_PATH  = r"C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\전처리_EDA\최종\pos_data_food_final_상품단위_filtered.csv"
SUCCESS_PATH = r"C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\seven_eleven_blog_reviews_success.csv"
FAIL_PATH    = r"C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\seven_eleven_blog_reviews_fail_v1.csv"
OUTPUT_PATH  = r"C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\블로그_나머지상품_크롤링.csv"
FINAL_PATH   = r"C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\블로그_전체상품_통합.csv"

COLS = ['중분류명', '검색어', '블로그제목', '블로그링크', '본문내용']

# ── 1. MASTER 로드 → 상품명:중분류명 매핑 ──────────────────────────────
df_master = pd.read_csv(MASTER_PATH, low_memory=False)
master_items = set(df_master['상품명'].dropna().str.strip().unique())

# 상품명 → 중분류명 매핑 딕셔너리
item_to_cat = (
    df_master.dropna(subset=['상품명', '상품중분류명'])
    .drop_duplicates(subset=['상품명'])
    .assign(상품명=lambda x: x['상품명'].str.strip())  # ← 체인 내부에서 strip
    .set_index('상품명')['상품중분류명']                 # ← 같은 DataFrame 참조
    .to_dict()
)
print(f"MASTER 전체 유니크 상품명: {len(master_items)}개")

# ── 2. OUTPUT 로드 → 이미 있는 상품명 파악 ───────────────────────────
df_output = pd.read_csv(OUTPUT_PATH, low_memory=False) if os.path.exists(OUTPUT_PATH) else pd.DataFrame(columns=COLS)

# OUTPUT의 검색어에서 상품명 추출
output_items = set(
    df_output['검색어']
    .dropna()
    .str.replace('세븐일레븐 ', '', n=1, regex=False)
    .str.strip()
)
print(f"OUTPUT에 이미 있는 상품명: {len(output_items)}개")

# ── 3. MASTER 기준으로 OUTPUT에 없는 상품 찾기 ───────────────────────
missing_items = master_items - output_items
print(f"OUTPUT에 없는 상품명: {len(missing_items)}개 → SUCCESS/FAIL에서 탐색")

# ── 4. SUCCESS / FAIL에서 누락 상품 데이터 수집 ──────────────────────
collected = []

for path, label in [(SUCCESS_PATH, 'success'), (FAIL_PATH, 'fail')]:
    if not os.path.exists(path):
        print(f"[{label}] 파일 없음, 스킵")
        continue

    df_src = pd.read_csv(path, low_memory=False)

    if '검색어' not in df_src.columns:
        print(f"[{label}] '검색어' 컬럼 없음, 스킵")
        continue

    # 검색어에서 상품명 추출 (prefix 제거)
    df_src['_상품명'] = (
        df_src['검색어']
        .dropna()
        .str.replace('세븐일레븐 ', '', n=1, regex=False)
        .str.strip()
    )

    # 누락 상품에 해당하는 행만 필터
    df_hit = df_src[df_src['_상품명'].isin(missing_items)].copy()
    print(f"[{label}] 누락 상품 중 {len(df_hit)}행 발견")

    if df_hit.empty:
        continue

    # 중분류명이 없으면 MASTER에서 채우기
    if '중분류명' not in df_hit.columns:
        df_hit['중분류명'] = df_hit['_상품명'].map(item_to_cat)
    else:
        mask = df_hit['중분류명'].isna()
        df_hit.loc[mask, '중분류명'] = df_hit.loc[mask, '_상품명'].map(item_to_cat)

    # 필요한 컬럼만 정리
    for col in COLS:
        if col not in df_hit.columns:
            df_hit[col] = ''

    collected.append(df_hit[COLS])

# ── 5. OUTPUT + 누락분 병합 후 저장 ──────────────────────────────────
if collected:
    df_extra = pd.concat(collected, ignore_index=True)
    print(f"\n추가할 행 수: {len(df_extra)}개")

    df_final = pd.concat([df_output[COLS], df_extra], ignore_index=True)
else:
    print("\n추가할 데이터 없음 (OUTPUT이 이미 완전함)")
    df_final = df_output[COLS].copy()

df_final.to_csv(FINAL_PATH, index=False, encoding='utf-8-sig')
print(f"\n✅ 통합 완료: {len(df_final)}행 → {FINAL_PATH}")

# ── 6. 커버리지 검증 ─────────────────────────────────────────────────
final_items = set(
    df_final['검색어']
    .dropna()
    .str.replace('세븐일레븐 ', '', n=1, regex=False)
    .str.strip()
)
still_missing = master_items - final_items
print(f"통합 후 여전히 누락된 상품: {len(still_missing)}개")
if still_missing:
    print("누락 상품 샘플:", list(still_missing)[:10])

MASTER 전체 유니크 상품명: 8118개
OUTPUT에 이미 있는 상품명: 4011개
OUTPUT에 없는 상품명: 4107개 → SUCCESS/FAIL에서 탐색
[success] 누락 상품 중 3148행 발견
[fail] 누락 상품 중 8857행 발견

추가할 행 수: 12005개

✅ 통합 완료: 23016행 → C:\Users\alexj\2026_캡스톤_디자인\세븐일레븐_프로젝트\세븐일레븐_내부데이터\블로그_전체상품_통합.csv
통합 후 여전히 누락된 상품: 0개

In [10]:
# df_final의 고유 상품 개수 (검색어에서 prefix 제거 후 기준)
unique_items_final = (
    df_final['검색어']
    .dropna()
    .str.replace('세븐일레븐 ', '', n=1, regex=False)
    .str.strip()
    .nunique()
)

print(f"df_final 고유 상품 수 : {unique_items_final}개")
print(f"MASTER  고유 상품 수  : {len(master_items)}개")
print(f"커버리지              : {unique_items_final / len(master_items) * 100:.1f}%")

df_final 고유 상품 수 : 8118개
MASTER  고유 상품 수  : 8118개
커버리지              : 100.0%

In [11]:
df_final.isnull().sum()

중분류명       0
검색어        0
블로그제목      0
블로그링크    380
본문내용     380
dtype: int64

In [13]:
df_final[df_final['본문내용'].isnull()]

         중분류명                        검색어 블로그제목 블로그링크 본문내용
16          껌          세븐일레븐 롯데)자일리톨F24g  결과없음   NaN  NaN
143    기능성드링크         세븐일레븐 동아)박카스F120ml  결과없음   NaN  NaN
147       젤리류  세븐일레븐 훼밀리)복숭아무케루푸루푸루구미40g  결과없음   NaN  NaN
251    기능성드링크       세븐일레븐 현대)미에로화이바350ml  결과없음   NaN  NaN
360      냉장안주       세븐일레븐 에프투)두레미니족발400g  결과없음   NaN  NaN
...       ...                        ...   ...   ...  ...
10915       떡             세븐일레븐 제라헌스페셜세트  결과없음   NaN  NaN
10925    비스킷류       세븐일레븐 여리수)키도크래커샌드90g  결과없음   NaN  NaN
10963     노벨티              세븐일레븐 직납)천혜향바  결과없음   NaN  NaN
10967      와인      세븐일레븐 지비)탈마템프라니요750ml  결과없음   NaN  NaN
10989     노벨티            세븐일레븐 직납)시모나바밤바  결과없음   NaN  NaN

[380 rows x 5 columns]